# Banc d’essai AP-HP : sélection de scénarios et génération en une ou deux étapes

Ce notebook permet de :

1. installer automatiquement `fictomed` depuis la branche Git `prompt-work` ;
2. filtrer `data/aphp/scenarios_bn_all_20260128.pq` ;
3. générer les scénarios complets avec `fictomed` ;
4. créer des fichiers de prompts éditables ;
5. lancer Mistral en une génération directe ou en deux étapes : résumé clinique puis CR.

Arborescence créée pour `RUN_NAME = "test_xx"` :

```text
test_xx/
├── scenarios_fictomed_selected.parquet
├── manifest.parquet
├── prompts/une_gen/
│   ├── system_prompt/
│   └── user_prompt/
├── prompts/deux_gen/
│   ├── premiere_gen/
│   │   ├── system_prompt/
│   │   └── user_prompt/
│   └── deuxieme_gen/
│       ├── system_prompt/
│       └── user_prompt/
└── sorties/
    ├── CR_1gen/
    └── resume_CR_2gen/
```

Les prompts sont écrits dans des fichiers `.txt` modifiables manuellement avant les appels Mistral. Le dossier de travail est créé à côté du notebook par défaut.

## 0. Chargement du script utilitaire et localisation du projet

La racine Stream est détectée automatiquement. En cas d’échec, renseigner `PROJECT_ROOT_OVERRIDE`.

In [2]:
from __future__ import annotations

from pathlib import Path
from typing import Any
import importlib
import os
import sys

import polars as pl
from IPython.display import display

NOTEBOOK_DIR = Path.cwd().resolve()
UTILS_SCRIPT = NOTEBOOK_DIR / "aphp_generation_utils.py"

if not UTILS_SCRIPT.is_file():
    raise FileNotFoundError(
        f"Script utilitaire introuvable : {UTILS_SCRIPT}\n"
        "Placez aphp_generation_utils.py dans le même dossier que le notebook."
    )

if str(NOTEBOOK_DIR) not in sys.path:
    sys.path.insert(0, str(NOTEBOOK_DIR))

import aphp_generation_utils as utils
importlib.reload(utils)

# Laisser None pour la détection automatique.
# Exemple : PROJECT_ROOT_OVERRIDE = Path("/chemin/vers/Stream")
PROJECT_ROOT_OVERRIDE: Path | None = None

PROJECT_ROOT = (
    utils.find_stream_root(NOTEBOOK_DIR)
    if PROJECT_ROOT_OVERRIDE is None
    else Path(PROJECT_ROOT_OVERRIDE).expanduser().resolve()
)

if not utils.looks_like_stream_root(PROJECT_ROOT):
    raise FileNotFoundError(
        f"Le chemin ne ressemble pas à une racine Stream : {PROJECT_ROOT}"
    )

BASE_DIR = NOTEBOOK_DIR
DEPENDENCIES_DIR = NOTEBOOK_DIR / "_dependencies"
FICTOMED_LOCAL_DIR = DEPENDENCIES_DIR / "fictomed_prompt_work"
FICTOMED_REPO_URL = "https://github.com/CHU-Brest/fictomed.git"
FICTOMED_BRANCH = "prompt-work"

print("Python du kernel :", sys.executable)
print("Notebook         :", NOTEBOOK_DIR)
print("Script utilitaire:", UTILS_SCRIPT)
print("Projet Stream    :", PROJECT_ROOT)
print("Dépendances      :", DEPENDENCIES_DIR)
print("Dépôt fictomed   :", FICTOMED_LOCAL_DIR)

Python du kernel : /Users/remi/Documents/Stream/.venv/bin/python
Notebook         : /Users/remi/Documents/Stream/work_modif_prompts
Script utilitaire: /Users/remi/Documents/Stream/work_modif_prompts/aphp_generation_utils.py
Projet Stream    : /Users/remi/Documents/Stream
Dépendances      : /Users/remi/Documents/Stream/work_modif_prompts/_dependencies
Dépôt fictomed   : /Users/remi/Documents/Stream/work_modif_prompts/_dependencies/fictomed_prompt_work

## 1. Installation ou mise à jour de fictomed

Cette cellule clone la branche configurée, met à jour le dépôt lorsqu’il n’existe aucune modification locale, puis effectue une installation éditable dans le Python du kernel.

In [3]:
utils.install_or_update_fictomed(
    dependencies_dir=DEPENDENCIES_DIR,
    local_dir=FICTOMED_LOCAL_DIR,
    repo_url=FICTOMED_REPO_URL,
    branch=FICTOMED_BRANCH,
    project_root=PROJECT_ROOT,
    python_executable=sys.executable,
)

FICTOMED_INSTALLATION = utils.verify_fictomed_installation(
    local_dir=FICTOMED_LOCAL_DIR,
    expected_branch=FICTOMED_BRANCH,
)

====================================================================================================
$ git ls-remote --heads https://github.com/CHU-Brest/fictomed.git refs/heads/prompt-work
====================================================================================================
83ebca9ac9b38327a7ed634de420f9c225172769	refs/heads/prompt-work


====================================================================================================
$ git clone --branch prompt-work --single-branch https://github.com/CHU-Brest/fictomed.git /Users/remi/Documents/Stream/work_modif_prompts/_dependencies/fictomed_prompt_work
====================================================================================================

Cloning into '/Users/remi/Documents/Stream/work_modif_prompts/_dependencies/fictomed_prompt_work'...

====================================================================================================
$ /Users/remi/Documents/Stream/.venv/bin/python -m pip install --editable /Users/remi/Documents/Stream/work_modif_prompts/_dependencies/fictomed_prompt_work
====================================================================================================
Obtaining file:///Users/remi/Documents/Stream/work_modif_prompts/_dependencies/fictomed_prompt_work
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Checking if build backend supports build_editable: started
  Checking if build backend supports build_editable: finished with status 'done'
  Getting requirements to build editable: started
  Getting requirements to build editable: finished with status 'done'
  Preparing editable metadata (pyproject.toml): started
  Preparing editable metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: numpy>=2.4.4 in /Users/remi/Documents/Stream/.venv/lib/python3.13/site-packages (from fictomed==0.1.0) (2.4.4)
Requirement already satisfied: polars>=1.40.1 in /Users/remi/Documents/Stream/.venv/lib/python3.13/site-packages (from fictomed==0.1.0) (1.40.1)
Requirement already satisfied: pyyaml>=6.0.3 in /Users/remi/Documents/Stream/.venv/lib/python3.13/site-packages (from fictomed==0.1.0) (6.0.3)
Requirement already satisfied: tqdm>=4.67.3 in /Users/remi/Documents/Stream/.venv/lib/python3.13/site-packages (from fictomed==0.1.0) (4.67.3)
Requirement already satisfied: polars-runtime-32==1.40.1 in /Users/remi/Documents/Stream/.venv/lib/python3.13/site-packages (from polars>=1.40.1->fictomed==0.1.0) (1.40.1)
Building wheels for collected packages: fictomed
  Building editable for fictomed (pyproject.toml): started
  Building editable for fictomed (pyproject.toml): finished with status 'done'
  Created wheel for fictomed: filename=fictomed-0.1.0-0.editable-py3-none-any.whl size=10945 sha256=3a749406e0afd884f688e85c7931c654a1323c9653d9f754f5c30fe3ba9aefcd
  Stored in directory: /private/var/folders/ll/25thrhx56t34sp92v0d0hzdr0000gn/T/pip-ephem-wheel-cache-6h5y2d1t/wheels/cd/d9/05/dcdc4817966f09d07232ce09bc141b1a6414335d4d215dc319
Successfully built fictomed
Installing collected packages: fictomed
  Attempting uninstall: fictomed
    Found existing installation: fictomed 0.1.2
    Uninstalling fictomed-0.1.2:
      Successfully uninstalled fictomed-0.1.2
Successfully installed fictomed-0.1.0

Installation fictomed terminée.

====================================================================================================
$ git branch --show-current
cwd : /Users/remi/Documents/Stream/work_modif_prompts/_dependencies/fictomed_prompt_work
====================================================================================================
prompt-work


====================================================================================================
$ git rev-parse --short HEAD
cwd : /Users/remi/Documents/Stream/work_modif_prompts/_dependencies/fictomed_prompt_work
====================================================================================================
83ebca9

fictomed importé depuis : /Users/remi/Documents/Stream/work_modif_prompts/_dependencies/fictomed_prompt_work/fictomed/__init__.py
Branche active          : prompt-work
Commit                  : 83ebca9
Dépôt local utilisé     : True

✅ fictomed est correctement installé et importé.

## 2. Configuration générale du run

In [10]:
RUN_NAME = "test_xx"
RUN_DIR = BASE_DIR / RUN_NAME

SOURCE_PROFILES_PATH = (
    PROJECT_ROOT / "data/aphp/scenarios_bn_all_20260128.pq"
)
APHP_DATA_DIR = PROJECT_ROOT / "data/aphp"

ONE_GEN_TEMPLATES_DIR = NOTEBOOK_DIR / "template_one_unique_gen"
FIRST_GEN_TEMPLATES_DIR = NOTEBOOK_DIR / "template_first_gen"
SECOND_GEN_TEMPLATES_DIR = NOTEBOOK_DIR / "template_second_gen"

TARGET_N = 1
CANDIDATE_POOL_SIZE = 200
RANDOM_SELECTION = True
RANDOM_SEED = 42

# True supprime les anciens .txt des six dossiers de prompts avant recréation.
# Passer à False dès que les prompts ont été modifiés manuellement.
CLEAN_EXISTING_PROMPTS = True

FICTOMED_CONFIG_FILE = NOTEBOOK_DIR / "data/servers.yaml"
PATHS = utils.create_run_tree(RUN_DIR)

print("BASE_DIR                :", BASE_DIR)
print("PROJECT_ROOT            :", PROJECT_ROOT)
print("RUN_DIR                 :", RUN_DIR)
print("SOURCE_PROFILES_PATH    :", SOURCE_PROFILES_PATH)
print("APHP_DATA_DIR           :", APHP_DATA_DIR)
print("ONE_GEN_TEMPLATES_DIR   :", ONE_GEN_TEMPLATES_DIR)
print("FIRST_GEN_TEMPLATES_DIR :", FIRST_GEN_TEMPLATES_DIR)
print("SECOND_GEN_TEMPLATES_DIR:", SECOND_GEN_TEMPLATES_DIR)
print("FICTOMED_CONFIG_FILE    :", FICTOMED_CONFIG_FILE)
print("CLEAN_EXISTING_PROMPTS  :", CLEAN_EXISTING_PROMPTS)

for key, value in PATHS.items():
    print(f"{key:>14}: {value}")

if not SOURCE_PROFILES_PATH.exists():
    raise FileNotFoundError(
        f"Fichier source AP-HP introuvable : {SOURCE_PROFILES_PATH}"
    )

BASE_DIR                : /Users/remi/Documents/Stream/work_modif_prompts
PROJECT_ROOT            : /Users/remi/Documents/Stream
RUN_DIR                 : /Users/remi/Documents/Stream/work_modif_prompts/test_xx
SOURCE_PROFILES_PATH    : /Users/remi/Documents/Stream/data/aphp/scenarios_bn_all_20260128.pq
APHP_DATA_DIR           : /Users/remi/Documents/Stream/data/aphp
ONE_GEN_TEMPLATES_DIR   : /Users/remi/Documents/Stream/work_modif_prompts/template_one_unique_gen
FIRST_GEN_TEMPLATES_DIR : /Users/remi/Documents/Stream/work_modif_prompts/template_first_gen
SECOND_GEN_TEMPLATES_DIR: /Users/remi/Documents/Stream/work_modif_prompts/template_second_gen
FICTOMED_CONFIG_FILE    : /Users/remi/Documents/Stream/work_modif_prompts/data/servers.yaml
CLEAN_EXISTING_PROMPTS  : True
    one_system: /Users/remi/Documents/Stream/work_modif_prompts/test_xx/prompts/une_gen/system_prompt
      one_user: /Users/remi/Documents/Stream/work_modif_prompts/test_xx/prompts/une_gen/user_prompt
  first_system: /Users/remi/Documents/Stream/work_modif_prompts/test_xx/prompts/deux_gen/premiere_gen/system_prompt
    first_user: /Users/remi/Documents/Stream/work_modif_prompts/test_xx/prompts/deux_gen/premiere_gen/user_prompt
 second_system: /Users/remi/Documents/Stream/work_modif_prompts/test_xx/prompts/deux_gen/deuxieme_gen/system_prompt
   second_user: /Users/remi/Documents/Stream/work_modif_prompts/test_xx/prompts/deux_gen/deuxieme_gen/user_prompt
       out_one: /Users/remi/Documents/Stream/work_modif_prompts/test_xx/sorties/CR_1gen
       out_two: /Users/remi/Documents/Stream/work_modif_prompts/test_xx/sorties/resume_CR_2gen
       backups: /Users/remi/Documents/Stream/work_modif_prompts/test_xx/_backups
       batches: /Users/remi/Documents/Stream/work_modif_prompts/test_xx/_mistral_batches

## 3. Filtres

Tous les filtres d’une liste sont cumulatifs. Opérateurs disponibles : `eq`, `ne`, `in`, `not_in`, `startswith`, `endswith`, `contains`, `regex`, `gt`, `ge`, `lt`, `le`, `is_null`, `not_null`. `exclude=True` inverse une condition.

In [11]:
SOURCE_FILTERS: list[dict[str, Any]] = [
    {"column": "diag2", "op": "endswith", "value": "8"},
    # {"column": "diag2", "op": "endswith", "value": "9", "exclude": True},
]

SCENARIO_FILTERS: list[dict[str, Any]] = [
    # {"column": "template_name", "op": "eq", "value": "surgery_outpatient.txt"},
]

print("Filtres source   :", SOURCE_FILTERS)
print("Filtres scénario :", SCENARIO_FILTERS)

Filtres source   : [{'column': 'diag2', 'op': 'endswith', 'value': '8'}]
Filtres scénario : []

## 4. Lecture, filtrage et échantillonnage des profils source

In [12]:
source_path, source_df, source_filtered, candidate_source = (
    utils.prepare_source_candidates(
        source_profiles_path=SOURCE_PROFILES_PATH,
        source_filters=SOURCE_FILTERS,
        candidate_pool_size=CANDIDATE_POOL_SIZE,
        random_selection=RANDOM_SELECTION,
        random_seed=RANDOM_SEED,
    )
)

SOURCE_PREVIEW_COLUMNS = [
    "source_row_id",
    "source_scenario_id",
    "mode_hospit",
    "racine",
    "ghm2",
    "diag2",
    "mdp",
    "diagnostic_associes",
    "duree",
]
SOURCE_PREVIEW_COLUMNS = [
    column
    for column in SOURCE_PREVIEW_COLUMNS
    if column in candidate_source.columns
]

display(candidate_source.select(SOURCE_PREVIEW_COLUMNS).head(20))

Fichier source : /Users/remi/Documents/Stream/data/aphp/scenarios_bn_all_20260128.pq
Shape          : (142912, 14)
Colonnes       : ['mode_hospit', 'sexe', 'age', 'racine', 'ghm2', 'diag2', 'mdp', 'nbda', 'diagnostic_associes', 'n', 'mode_entree', 'mode_sortie', 'agean', 'duree']
SOURCE, filtre 1: {'column': 'diag2', 'op': 'endswith', 'value': '8'} | 142912 -> 7716

Candidats envoyés à fictomed : (200, 16)

shape: (20, 9)
┌───────────────┬───────────────┬─────────────┬────────┬───┬───────┬────────┬──────────────┬───────┐
│ source_row_id ┆ source_scenar ┆ mode_hospit ┆ racine ┆ … ┆ diag2 ┆ mdp    ┆ diagnostic_a ┆ duree │
│ ---           ┆ io_id         ┆ ---         ┆ ---    ┆   ┆ ---   ┆ ---    ┆ ssocies      ┆ ---   │
│ u32           ┆ ---           ┆ str         ┆ str    ┆   ┆ str   ┆ str    ┆ ---          ┆ f64   │
│               ┆ str           ┆             ┆        ┆   ┆       ┆        ┆ str          ┆       │
╞═══════════════╪═══════════════╪═════════════╪════════╪═══╪═══════╪════════╪══════════════╪═══════╡
│ 115709        ┆ scenarios_bn_ ┆ HC          ┆ 13M04  ┆ … ┆ N938  ┆ DP     ┆ D500         ┆ 2.0   │
│               ┆ all_20260128_ ┆             ┆        ┆   ┆       ┆        ┆              ┆       │
│               ┆ row_…         ┆             ┆        ┆   ┆       ┆        ┆              ┆       │
│ 45723         ┆ scenarios_bn_ ┆ HC          ┆ 01M21  ┆ … ┆ R5218 ┆ DP     ┆ M7978        ┆ 3.0   │
│               ┆ all_20260128_ ┆             ┆        ┆   ┆       ┆        ┆              ┆       │
│               ┆ row_…         ┆             ┆        ┆   ┆       ┆        ┆              ┆       │
│ 140790        ┆ scenarios_bn_ ┆ HC          ┆ 15M06  ┆ … ┆ P598  ┆ DP     ┆ Z1351        ┆ 6.0   │
│               ┆ all_20260128_ ┆             ┆        ┆   ┆       ┆        ┆              ┆       │
│               ┆ row_…         ┆             ┆        ┆   ┆       ┆        ┆              ┆       │
│ 100057        ┆ scenarios_bn_ ┆ HC          ┆ 23M20  ┆ … ┆ G258  ┆ Z04801 ┆ G473         ┆ 3.0   │
│               ┆ all_20260128_ ┆             ┆        ┆   ┆       ┆        ┆              ┆       │
│               ┆ row_…         ┆             ┆        ┆   ┆       ┆        ┆              ┆       │
│ 112365        ┆ scenarios_bn_ ┆ HC          ┆ 14Z14  ┆ … ┆ O48   ┆ DP     ┆ O244 O700    ┆ 6.0   │
│               ┆ all_20260128_ ┆             ┆        ┆   ┆       ┆        ┆ Z370 Z391    ┆       │
│               ┆ row_…         ┆             ┆        ┆   ┆       ┆        ┆              ┆       │
│ …             ┆ …             ┆ …           ┆ …      ┆ … ┆ …     ┆ …      ┆ …            ┆ …     │
│ 78011         ┆ scenarios_bn_ ┆ HP          ┆ 14M03  ┆ … ┆ Z358  ┆ DP     ┆ O244 Z359    ┆ 0.0   │
│               ┆ all_20260128_ ┆             ┆        ┆   ┆       ┆        ┆ Z713         ┆       │
│               ┆ row_…         ┆             ┆        ┆   ┆       ┆        ┆              ┆       │
│ 30292         ┆ scenarios_bn_ ┆ HC          ┆ 23K02  ┆ … ┆ Z468  ┆ DP     ┆ J961 Z991    ┆ 1.0   │
│               ┆ all_20260128_ ┆             ┆        ┆   ┆       ┆        ┆              ┆       │
│               ┆ row_…         ┆             ┆        ┆   ┆       ┆        ┆              ┆       │
│ 6983          ┆ scenarios_bn_ ┆ HC          ┆ 14M03  ┆ … ┆ Z358  ┆ DP     ┆ O441         ┆ 2.0   │
│               ┆ all_20260128_ ┆             ┆        ┆   ┆       ┆        ┆              ┆       │
│               ┆ row_…         ┆             ┆        ┆   ┆       ┆        ┆              ┆       │
│ 82357         ┆ scenarios_bn_ ┆ HC          ┆ 06C09  ┆ … ┆ K358  ┆ DP     ┆ R18          ┆ 5.0   │
│               ┆ all_20260128_ ┆             ┆        ┆   ┆       ┆        ┆              ┆       │
│               ┆ row_…         ┆             ┆        ┆   ┆       ┆        ┆              ┆       │
│ 66579         ┆ scenarios_bn_ ┆ HC          ┆ 14Z13  ┆ … ┆ O358  ┆ DP     ┆ O800 Z370    ┆ 13.0  │
│               ┆ all_20260128_ ┆             ┆        ┆   ┆       ┆        ┆ O680 O701    ┆       │
│               ┆ row_…         ┆             ┆        ┆   ┆       ┆        ┆ Z300 Z3908…  ┆       │
└───────────────┴───────────────┴─────────────┴────────┴───┴───────┴────────┴──────────────┴───────┘

## 5. Création du fichier `servers.yaml` utilisé par fictomed

In [13]:
FICTOMED_CONFIG_PATHS = utils.write_fictomed_config(
    config_file=FICTOMED_CONFIG_FILE,
    project_root=PROJECT_ROOT,
    run_dir=RUN_DIR,
)

print("Input AP-HP configuré :", FICTOMED_CONFIG_PATHS["aphp_input"])
print("Sortie fictomed       :", FICTOMED_CONFIG_PATHS["aphp_output"])
print("Référentiels          :", FICTOMED_CONFIG_PATHS["aphp_referentials"])

Configuration fictomed : /Users/remi/Documents/Stream/work_modif_prompts/data/servers.yaml

pipelines:
  brest:
    data:
      input: /Users/remi/Documents/Stream/data/brest
      output: /Users/remi/Documents/Stream/work_modif_prompts/test_xx/sorties/scenarios_brest
  aphp:
    data:
      input: /Users/remi/Documents/Stream/data/aphp
      output: /Users/remi/Documents/Stream/work_modif_prompts/test_xx/sorties/scenarios
      referentials: /Users/remi/Documents/Stream/data/aphp/referentials

Input AP-HP configuré : /Users/remi/Documents/Stream/data/aphp
Sortie fictomed       : /Users/remi/Documents/Stream/work_modif_prompts/test_xx/sorties/scenarios
Référentiels          : /Users/remi/Documents/Stream/data/aphp/referentials

## 6. Génération fictomed et sélection finale

Le fichier `profiles` résolu dans le dossier d’entrée AP-HP est sauvegardé, remplacé temporairement par les candidats filtrés, puis restauré dans un bloc `finally`.

In [14]:
generated_candidates, generated_filtered, selected_scenarios = (
    utils.generate_and_select_fictomed_scenarios(
        candidate_source=candidate_source,
        config_file=FICTOMED_CONFIG_FILE,
        aphp_data_dir=APHP_DATA_DIR,
        paths=PATHS,
        scenario_filters=SCENARIO_FILTERS,
        target_n=TARGET_N,
        random_selection=RANDOM_SELECTION,
        random_seed=RANDOM_SEED,
        run_dir=RUN_DIR,
    )
)

SCENARIO_DISPLAY_COLUMNS = [
    "generation_id",
    "source_row_id",
    "source_scenario_id",
    "icd_primary_code",
    "drg_parent_code",
    "ghm2",
    "template_name",
    "coding_rule",
    "admission_type",
]
SCENARIO_DISPLAY_COLUMNS = [
    column
    for column in SCENARIO_DISPLAY_COLUMNS
    if column in selected_scenarios.columns
]

display(selected_scenarios.select(SCENARIO_DISPLAY_COLUMNS))

fictomed importé depuis : /Users/remi/Documents/Stream/work_modif_prompts/_dependencies/fictomed_prompt_work/fictomed/__init__.py
Dossier lu par fictomed : /Users/remi/Documents/Stream/data/aphp
Profiles actif          : /Users/remi/Documents/Stream/data/aphp/scenarios_bn_all_20260128.pq
Backup                  : /Users/remi/Documents/Stream/work_modif_prompts/test_xx/_backups/scenarios_bn_all_20260128.pq.20260813_115417.backup
Vérification des données d'entrée pour le pipeline AP-HP.
Chargement des fichiers PMSI depuis /Users/remi/Documents/Stream/data/aphp.
Fichiers PMSI chargés avec succès.
Données AP-HP présentes dans /Users/remi/Documents/Stream/data/aphp.

Construction scénarios: 100%|██████████| 3/3 [00:03<00:00,  1.12s/étape]
Construction contexte:   0%|          | 0/3 [03:49<?, ?étape/s]

Scénarios sauvegardés dans /Users/remi/Documents/Stream/work_modif_prompts/test_xx/sorties/scenarios/aphp_scenarios_194_20260813_115422.parquet
Profiles original restauré : /Users/remi/Documents/Stream/data/aphp/scenarios_bn_all_20260128.pq

Scénarios candidats générés : (194, 55)
source_row_id: 194 uniques / 194
source_scenario_id: 194 uniques / 194
generation_id: 194 uniques / 194

Scénarios retenus : (1, 55)
Écrit             : /Users/remi/Documents/Stream/work_modif_prompts/test_xx/scenarios_fictomed_selected.parquet

shape: (1, 9)
┌────────────┬────────────┬───────────┬───────────┬───┬────────┬───────────┬───────────┬───────────┐
│ generation ┆ source_row ┆ source_sc ┆ icd_prima ┆ … ┆ ghm2   ┆ template_ ┆ coding_ru ┆ admission │
│ _id        ┆ _id        ┆ enario_id ┆ ry_code   ┆   ┆ ---    ┆ name      ┆ le        ┆ _type     │
│ ---        ┆ ---        ┆ ---       ┆ ---       ┆   ┆ str    ┆ ---       ┆ ---       ┆ ---       │
│ str        ┆ i64        ┆ str       ┆ str       ┆   ┆        ┆ str       ┆ str       ┆ str       │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪════════╪═══════════╪═══════════╪═══════════╡
│ 0c3482a6-9 ┆ 88260      ┆ scenarios ┆ D508      ┆ … ┆ 16M111 ┆ medical_i ┆ other     ┆ HC        │
│ 5e4-4090-b ┆            ┆ _bn_all_2 ┆           ┆   ┆        ┆ npatient. ┆           ┆           │
│ 06f-6520c9 ┆            ┆ 0260128_r ┆           ┆   ┆        ┆ txt       ┆           ┆           │
│ …          ┆            ┆ ow_…      ┆           ┆   ┆        ┆           ┆           ┆           │
└────────────┴────────────┴───────────┴───────────┴───┴────────┴───────────┴───────────┴───────────┘

## 7. Création des prompts et du manifest

Les trois `user_prompt` proviennent du scénario fictomed. Les trois `system_prompt` proviennent des dossiers de templates externes correspondant au `template_name`.

In [15]:
manifest = utils.create_prompt_files(
    selected_scenarios=selected_scenarios,
    run_dir=RUN_DIR,
    paths=PATHS,
    one_gen_templates_dir=ONE_GEN_TEMPLATES_DIR,
    first_gen_templates_dir=FIRST_GEN_TEMPLATES_DIR,
    second_gen_templates_dir=SECOND_GEN_TEMPLATES_DIR,
    clean_existing_prompts=CLEAN_EXISTING_PROMPTS,
)

display(manifest)

Anciens fichiers de prompts supprimés : 0
Manifest écrit : /Users/remi/Documents/Stream/work_modif_prompts/test_xx/manifest.parquet

shape: (1, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ generatio ┆ template_ ┆ file_stem ┆ one_syste ┆ … ┆ first_sys ┆ first_use ┆ second_sy ┆ second_u │
│ n_id      ┆ name      ┆ ---       ┆ m_path    ┆   ┆ tem_path  ┆ r_path    ┆ stem_path ┆ ser_path │
│ ---       ┆ ---       ┆ str       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ str       ┆           ┆ str       ┆   ┆ str       ┆ str       ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0c3482a6- ┆ medical_i ┆ 0000__0c3 ┆ prompts/u ┆ … ┆ prompts/d ┆ prompts/d ┆ prompts/d ┆ prompts/ │
│ 95e4-4090 ┆ npatient. ┆ 482a6-95e ┆ ne_gen/sy ┆   ┆ eux_gen/p ┆ eux_gen/p ┆ eux_gen/d ┆ deux_gen │
│ -b06f-652 ┆ txt       ┆ 4-4090-b0 ┆ stem_prom ┆   ┆ remiere_g ┆ remiere_g ┆ euxieme_g ┆ /deuxiem │
│ 0c9…      ┆           ┆ 6f-…      ┆ pt/…      ┆   ┆ en/…      ┆ en/…      ┆ en/…      ┆ e_gen/…  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## 8. Prévisualisation des prompts

Après cette cellule, les fichiers `.txt` peuvent être modifiés manuellement. Ne pas recréer les prompts avec `CLEAN_EXISTING_PROMPTS=True` après ces modifications.

In [16]:
PROMPT_PREVIEW_INDEX = 0

utils.preview_prompt_files(
    run_dir=RUN_DIR,
    preview_index=PROMPT_PREVIEW_INDEX,
    max_chars=8_000,
)

### Scénario `0c3482a6-95e4-4090-b06f-6520c958327d` — `medical_inpatient.txt`

#### Une génération — system prompt

Vous êtes un médecin clinicien expert. Votre tâche est de générer un compte rendu d'hospitalisation détaillé à partir d'un scénario clinique réalisé avec des codes de la classification internationale des maladies (CIM-10) et d'autres informations décrivant l'hospitalisation.


# Contexte : le codage CIM-10

La CIM-10 est une classification des maladies, elle peut se définir comme un ensemble organisé de rubriques dans lesquelles on range des entités morbides en fonction de certains critères établis. La CIM est utilisée pour transposer les diagnostics de maladies ou autres problèmes de santé en codes alphanumériques, ce qui facilite le stockage, la recherche et l'analyse des données. Elle est très utilisée en France, en particulier pour le codage des causes de décès et pour la déclaration de l'activité hospitalière dans le cadre du programme de médicalisation des systèmes d'information (PMSI).

Le codage CIM-10 consiste à identifier dans un document médical (CRH, notes d'évolution, comptes-rendus opératoires) les maladies, éventuellement les symptômes et états cliniques en l'absence de maladie clairement identifiée, et à leur attribuer des codes standardisés. C'est une tâche de standardisation d'information, pas une tâche de décision médicale : on traduit ce que le clinicien a écrit en codes normalisés.

# Ta mission : la tâche inverse

Ta mission est de réaliser la tâche inverse : à partir d'un scénario essentiellement composé de codes CIM-10, générer un compte rendu d'hospitalisation. Tu pars donc du concept standardisé et tu retournes vers la diversité réelle de l'écriture médicale.

Ces comptes rendus serviront à entraîner un outil d'aide au codage automatique : il est essentiel que ces CRH soient à la fois réalistes mais aussi que le lien entre le texte et les codes CIM à l'échelle du document soit respecté. Il est donc impératif que le CRH ne décrive que des maladies couvertes par le scénario CIM-10. À noter que pour le codage CIM-10, seules les maladies actives au moment de l'hospitalisation sont codées : tu peux donc mentionner des antécédents médicaux ou chirurgicaux mineurs et plausibles pour donner du réalisme au compte rendu, mais évite tout antécédent suffisamment lourd ou actif pour qu'il aurait dû lui-même être codé.

# La nature variable des codes CIM-10

Pour t'aider à bien comprendre le périmètre de chacun des codes choisis, je te fournis également une fiche descriptive par code, qui contient des informations complémentaires issues de la classification et de thésaurus médicaux. La CIM-10 range les entités morbides dans des rubriques selon des critères établis. Concrètement, deux types de critères définissent le périmètre d'un code, et les informations complémentaires correspondent à ces deux logiques :

- des **critères positifs** — ce qui fait entrer une pathologie dans la rubrique. Ils sont portés par les notes d'**inclusion**.
- des **critères négatifs** — ce qui en est explicitement écarté et relève d'un autre code. Ils sont portés par les notes d'**exclusion**.

Les fiches contiennent également des **synonymes** des maladies qui entrent dans le périmètre du code. Tu peux t'en inspirer pour utiliser un vocabulaire moins formel que les libellés et notes officielles de la classification.

**Niveau d'application des inclusions.** Les notes d'inclusion peuvent être attachées à différents niveaux de la hiérarchie (chapitre, bloc, catégorie, code). Plus une inclusion est attachée à un niveau élevé, plus elle est générale et vaut pour de nombreux codes : c'est une définition de cadre, pas une caractéristique propre au code. Par exemple, au niveau du chapitre I, l'inclusion « maladies considérées habituellement comme contagieuses ou transmissibles » s'applique à tous les codes du chapitre et n'ajoute aucune spécificité à l'un d'eux en particulier. À l'inverse, une inclusion attachée directement au code décrit précisément ce que ce code recouvre. Sers-toi des inclusions générales pour comprendre le contexte d'un code, et des inclusions propres au code pour choisir le vocabulaire précis de ta rédaction.

**Point essentiel : les codes n'ont pas tous la même précision clinique.** Certains désignent une entité nette et unique (ex. I10, hypertension artérielle essentielle). D'autres regroupent plusieurs entités hétérogènes sous un même libellé.

**Cas des sous-catégories « autres formes précisées » (le plus souvent `.8`)** : elles rassemblent des entités précises mais diverses qui n'ont pas de code dédié dans la catégorie (ex. B17.8, « autres hépatites virales aiguës précisées »). Le libellé officiel ne suffit alors pas à savoir quelle pathologie réelle décrire ; appuie-toi sur les inclusions et synonymes propres au code.

**Cas particulier des cancers (chapitre II, catégories C00-C75)** : la CIM-10 classe les tumeurs malignes primitives essentiellement selon leur siège anatomique, et en grands groupes selon le comportement de la tumeur ; la morphologie n'apparaît qu'exceptionnellement dans le titre. Deux conséquences :

- la granularité d'un code par rapport à sa catégorie est avant tout une précision **anatomique**. Un code plus spécifique te donne une localisation plus précise, pas un type histologique plus précis ;
- pour ces catégories, la sous-catégorie `.8` ne signifie pas « autres formes » mais **« lésion à localisations contiguës »** : elle désigne une tumeur qui empiète sur deux ou trois sous-catégories voisines et dont le point de départ ne peut être déterminé. Quand tu rédiges pour un tel code, décris une atteinte qui chevauche plusieurs localisations contiguës d'un même organe, sans désigner un point de départ unique.

**Cas particulier des codes « sans précision » (le plus souvent terminés par `.9`)** : ces codes ne sont employés que lorsque le dossier ne contenait pas l'information détaillée qui aurait permis de choisir un code plus spécifique. Leur présence dans le scénario est donc un signal positif d'incertitude : on sait qu'il y a une pathologie de cette catégorie, mais on ignore volontairement son détail. En conséquence, quand tu mentionnes un tel code dans le compte rendu, reste délibérément vague : nomme l'entité au niveau général du libellé sans inventer de forme, de cause, de localisation fine, de stade ni de mécanisme précis. Ajouter une précision que le code ne porte pas contredirait la raison même pour laquelle ce code « sans précision » a été retenu plutôt qu'un code plus fin.

# Comment lire les fiches descriptives de codes

Les fiches de codes n’emploient pas toujours explicitement les mots « inclusion », « exclusion », « critères positifs » ou « critères négatifs ».
Dans une fiche, la section **« Périmètre clinique du code »** correspond aux **critères positifs** : elle indique ce qui peut être décrit pour ce code.
La section **« À ne pas décrire »** correspond aux **critères négatifs** : elle indique les diagnostics, causes ou situations à éviter, sauf s’ils sont explicitement codés ailleurs dans le scénario.
La section **« Formulations cliniques alternatives »** correspond aux **synonymes et reformulations autorisées** : tu peux les utiliser pour varier le vocabulaire sans ajouter de précision non portée par le code.
La section **« Position dans la classification »** sert seulement à comprendre le contexte général du code ; elle ne suffit pas à inventer des détails cliniques spécifiques.

**En résumé**, reste strictement dans le périmètre du code : reformule librement à l'intérieur de ce que couvrent libellé, inclusions et synonymes (critères positifs), n'oriente jamais ta rédaction vers une entité exclue (critères négatifs), traite les `.8` cancérologiques comme des atteintes plurifocales contiguës, et respecte le flou volontaire des codes « sans précision ».


# Application à la rédaction du compte rendu

Les règles CIM-10 ci-dessus définissent le périmètre diagnostique strict à respecter.
Les instructions suivantes définissent maintenant le type de compte rendu à produire, son style, sa structu

#### Une génération — user prompt

**SCÉNARIO DE DÉPART :**
- Âge du patient : 83 ans
- Sexe du patient : Masculin
- Date d'entrée : 18/11/2024
- Date de sortie : 21/11/2024
- Date de naissance : 10/09/1941
- Nom du patient : Neves cordeiro
- Prénom du patient : Jonathann
- Mode d'entrée' : DOMICILE
- Mode de sortie' : DOMICILE
- Contexte de l'hospitalisation : Pour prise en charge diagnostique et thérapeutique du diagnotic principal en hospitalisation complète.
- Codage CIM10 :
   * Diagnostic principal : Autres anémies par carence en fer (D508)
   * Diagnostics associés :
      - Hypertension essentielle (primitive) (I10)
- Nom du médecin / signataire : Genevieve Mainardi
- Service : MEDECINE INTERNE
- Hôpital : Hôpital Claude Huriez - Centre Hospitalier Universitaire de Lille

**FICHES DESCRIPTIVES DES CODES CIM-10 DU SCÉNARIO :**

Les fiches ci-dessous précisent le périmètre des codes CIM-10 présents dans le scénario.
Elles doivent être utilisées pour choisir des formulations compatibles avec les codes, sans ajouter de diagnostic non codé.

<fiche_category code="D50">

# D50 — Anémie par carence en fer

## Position dans la classification
- Chapitre III : Maladies du sang et des organes hématopoïétiques et certains troubles du système immunitaire
- Bloc D50-D53 : Anémies nutritionnelles

## Codes enfants directs
- D50.0 — Anémie par carence en fer secondaire à une perte de sang (chronique)
- D50.1 — Dysphagie sidéropénique
- D50.8 — Autres anémies par carence en fer
- D50.9 — Anémie par carence en fer, sans précision

## Périmètre clinique

Inclusions héritées de la catégorie D50 :
- anémie ferriprive
- anémie :
 - ferriprive
 - hypochrome
- anémie hypochrome

Au niveau des codes :
- anémie posthémorragique (chronique) (D50.0)
- syndrome de Kelly-Paterson (D50.1)
- Syndrome de :
 - Kelly–Paterson
 - Plummer–Vinson
 (D50.1)
- syndrome de Plummer-Vinson (D50.1)

## À ne pas décrire

Affections relevant d'autres codes (hérité du chapitre III) :

certaines affections dont l'origine se situe dans la période périnatale (P00-P96)
complications de la grossesse, de l'accouchement et de la puerpéralité (O00-O99)
lésions traumatiques, empoisonnements et certaines autres conséquences de causes externes (S00-T98)
maladies auto-immunes (systémiques) SAI (M35.9)
maladies dues au virus de l'immunodéficience humaine [VIH] (B20-B24)
maladies endocriniennes, nutritionnelles et métaboliques (E00-E90)
malformations congénitales et anomalies chromosomiques (Q00-Q99)
symptômes, signes et résultats anormaux d'examens cliniques et de laboratoire, non classés ailleurs (R00-R99)
tumeurs (C00-D48)

Affections relevant d'autres codes :

- anémie :
 - congénitale par perte de sang fœtal (P61.3)
 - posthémorragique aigüe (D62)

## Formulations cliniques alternatives
- Anémie (à) (de), achlorhydrique (D50.8)
- Anémie (à) (de), avec, carence en fer (D50.9)
- Anémie (à) (de), hypochrome, hyposidérémique (D50.8)
- Anémie (à) (de), normocytaire (infectieuse), due à hémorragie (chronique) (D50.0)
- Anémie (à) (de), nutritionnelle, sidéropénique (D50.8)
- Anémie (à) (de), par carence (en), fer, due à une perte de sang (chronique) (D50.0)
- anémie carence martiale (D50.9)
- anémie chronique ferriprive (D50.9)
- anémie chronique saignement (D50.0)
- anémie déglobulisation (D50.0)
- anémie déperdition sanguine (D50.0)
- anémie déperditionnelle (D50.0)
- anémie férriprive acutisée (D50.9)
- anémie ferriprive ancienne (D50.9)
- anémie ferriprive chronique (D50.9)
- anémie ferriprive hémorragique chronique (D50.0)
- anémie ferriprive par pertes sanguines (D50.0)
- anémie ferriprive par spoliation chronique (D50.0)
- anémie ferriprive subaigüe (D50.9)
- anémie fuite digestive (D50.0)
- anémie hémorragique chronique (D50.0)
- anémie hypochrome chronique (D50.0)
- anémie hypochrome microcytaire (D50.8)
- anémie hypochrome microcytaire arégénérative (D50.8)
- anémie hypochrome microcytaire hyposidérémique (D50.8)
- anémie hyposidérémique (D50.9)
- anémie inflammatoire ferriprive (D50.9)
- anémie méléna (D50.0)
- anémie microcytaire carentielle (D50.8)
- anémie microcytaire hypochrome arégénérative (D50.8)
- anémie microcytaire hyposidérémique (D50.8)
- anémie microcytaire réfractaire (D50.8)
- anémie microcytaire spoliation digestive (D50.8)
- anémie par hémorragie (D50.0)
- anémie par saignement (D50.0)
- anémie par spoliation sanguine digestive (D50.0)
- anémie perte sanguine (D50.0)
- anémie perte sanguine digestive (D50.0)
- anémie post-rectorragie (D50.0)
- anémie réfractaire par saignement (D50.0)
- anémie sidéropénique réfractaire (D50.9)
- anémie spoliation (D50.0)
- anémie spoliative (D50.0)
- anémie spoliative aigüe (D50.0)
- Carence (en), fer, avec anémie (D50.9)
- Chlorose (D50.8)
- Kelly(-patterson), syndrome de (D50.1)
- Paterson(-kelly), syndrome de (D50.1)
- Sidéropénie, avec anémie (D50.9)
- Witt, anémie de (D50.8)

</fiche_category>

<fiche_code code="I10">

# I10 — Hypertension essentielle (primitive)

## Position dans la classification
- Chapitre IX : Maladies de l'appareil circulatoire
- Bloc I10-I15 : Maladies hypertensives

## Périmètre clinique du code

Au niveau du code :
- hypertension (artérielle) (bénigne) (essentielle) (maligne) (primitive) (systémique)
- tension artérielle élevée

## À ne pas décrire

Affections relevant d'autres codes (hérité du chapitre IX) :

accidents ischémiques cérébraux transitoires et syndromes apparentés (G45.-)
affections disséminées du tissu conjonctif (M30-M36)
certaines affections dont l'origine se situe dans la période périnatale (P00-P96)
certaines maladies infectieuses et parasitaires (A00-B99)
complications de la grossesse, de l'accouchement et de la puerpéralité (O00-O99)
lésions traumatiques, empoisonnements et certaines autres conséquences de causes externes (S00-T98)
maladies endocriniennes, nutritionnelles et métaboliques (E00-E90)
malformations congénitales et anomalies chromosomiques (Q00-Q99)
symptômes, signes et résultats anormaux d'examens cliniques et de laboratoire, non classés ailleurs (R00-R99)
tumeurs (C00-D48)

Affections relevant d'autres codes (hérité du bloc I10-I15) :

cardiopathies ischémiques (I20-I25)
compliquant la grossesse, l'accouchement et la puerpéralité (O10-O11)  (O13-O16)
hypertension :
 - du nouveau-né (P29.2)
 - pulmonaire :
  - primaire (I27.0)
  - secondaire (I27.2)

Affections relevant d'autres codes :

avec :
 - maladies cérébrovasculaires (I60-I69)
 - rétinopathies vasculaires (H35.0)

## Formulations cliniques alternatives
- Elévation de (voir aussi augmentation), pression ou tension (non spécifique), artérielle (voir aussi hypertension)
- HTA bien contrôlée
- HTA contrôlée
- HTA effort
- HTA essentielle
- HTA essentielle "maligne" [coder aussi les conséquences]
- HTA instable
- HTA modérée
- HTA rebelle
- hypertension aigüe
- Hypertension (artérielle) (bénigne) (essentielle) (idiopathique) (maligne) (primitive) (systémique)
- hypertension artérielle idiopathique
- Hypertension artérielle primitive
- polyangiopathie hypertensive
- poussées hypertensives
- Tension, artérielle, élevée (épisodique) (non spécifique), due à hypertension (voir aussi hypertension)

</fiche_code>

#### Deux générations, première — system prompt

Vous êtes un médecin clinicien expert.

Pour cette première génération, votre tâche est d'analyser le scénario clinique transmis et de produire uniquement un résumé clinique contrôlé au format JSON. Ce résumé sera utilisé pour préparer la rédaction des documents médicaux lors d'un second appel.

Ne rédigez aucun compte rendu ni aucun autre document médical final à cette étape.

# Contexte : le codage CIM-10

La CIM-10 est une classification des maladies, elle peut se définir comme un ensemble organisé de rubriques dans lesquelles on range des entités morbides en fonction de certains critères établis. La CIM est utilisée pour transposer les diagnostics de maladies ou autres problèmes de santé en codes alphanumériques, ce qui facilite le stockage, la recherche et l'analyse des données. Elle est très utilisée en France, en particulier pour le codage des causes de décès et pour la déclaration de l'activité hospitalière dans le cadre du programme de médicalisation des systèmes d'information (PMSI).

Le codage CIM-10 consiste à identifier dans un document médical (CRH, notes d'évolution, comptes-rendus opératoires) les maladies, éventuellement les symptômes et états cliniques en l'absence de maladie clairement identifiée, et à leur attribuer des codes standardisés. C'est une tâche de standardisation d'information, pas une tâche de décision médicale : on traduit ce que le clinicien a écrit en codes normalisés.

# Ta mission : produire uniquement un résumé clinique intermédiaire

À partir du scénario transmis dans le message utilisateur, analyse les codes CIM-10, leurs fiches descriptives, les actes CCAM éventuels et les autres informations décrivant l'épisode.

Pour cette première génération, tu dois produire uniquement un résumé clinique contrôlé. Tu ne dois rédiger aucun document médical final : ni compte rendu d'hospitalisation, ni compte rendu opératoire, ni compte rendu d'accouchement, ni document d'urgence.

Ce résumé prépare une deuxième génération. Le scénario complet, les fiches descriptives, les actes et les informations administratives seront de nouveau fournis au deuxième appel, en plus de ce résumé. Il n'est donc pas nécessaire de recopier tout le scénario : synthétise surtout le périmètre diagnostique, les formulations possibles, la prise en charge compatible et les éléments à ne pas ajouter.

Le résumé doit inclure tous les diagnostics du scénario et aucun autre. Il doit conserver le niveau de précision exact des codes, notamment le flou volontaire des codes « sans précision », et ne doit ajouter aucune localisation, latéralité, cause, forme, stade, complication, traitement précis ou résultat d'examen absent des données sources.

# La nature variable des codes CIM-10

Pour t'aider à bien comprendre le périmètre de chacun des codes choisis, je te fournis également une fiche descriptive par code, qui contient des informations complémentaires issues de la classification et de thésaurus médicaux. La CIM-10 range les entités morbides dans des rubriques selon des critères établis. Concrètement, deux types de critères définissent le périmètre d'un code, et les informations complémentaires correspondent à ces deux logiques :

- des **critères positifs** — ce qui fait entrer une pathologie dans la rubrique. Ils sont portés par les notes d'**inclusion**.
- des **critères négatifs** — ce qui en est explicitement écarté et relève d'un autre code. Ils sont portés par les notes d'**exclusion**.

Les fiches contiennent également des **synonymes** des maladies qui entrent dans le périmètre du code. Tu peux t'en inspirer pour utiliser un vocabulaire moins formel que les libellés et notes officielles de la classification.

**Niveau d'application des inclusions.** Les notes d'inclusion peuvent être attachées à différents niveaux de la hiérarchie (chapitre, bloc, catégorie, code). Plus une inclusion est attachée à un niveau élevé, plus elle est générale et vaut pour de nombreux codes : c'est une définition de cadre, pas une caractéristique propre au code. Par exemple, au niveau du chapitre I, l'inclusion « maladies considérées habituellement comme contagieuses ou transmissibles » s'applique à tous les codes du chapitre et n'ajoute aucune spécificité à l'un d'eux en particulier. À l'inverse, une inclusion attachée directement au code décrit précisément ce que ce code recouvre. Sers-toi des inclusions générales pour comprendre le contexte d'un code, et des inclusions propres au code pour délimiter précisément le contenu du résumé clinique.

**Point essentiel : les codes n'ont pas tous la même précision clinique.** Certains désignent une entité nette et unique (ex. I10, hypertension artérielle essentielle). D'autres regroupent plusieurs entités hétérogènes sous un même libellé.

**Cas des sous-catégories « autres formes précisées » (le plus souvent `.8`)** : elles rassemblent des entités précises mais diverses qui n'ont pas de code dédié dans la catégorie (ex. B17.8, « autres hépatites virales aiguës précisées »). Le libellé officiel ne suffit alors pas à savoir quelle pathologie réelle décrire ; appuie-toi sur les inclusions et synonymes propres au code.

**Cas particulier des cancers (chapitre II, catégories C00-C75)** : la CIM-10 classe les tumeurs malignes primitives essentiellement selon leur siège anatomique, et en grands groupes selon le comportement de la tumeur ; la morphologie n'apparaît qu'exceptionnellement dans le titre. Deux conséquences :

- la granularité d'un code par rapport à sa catégorie est avant tout une précision **anatomique**. Un code plus spécifique te donne une localisation plus précise, pas un type histologique plus précis ;
- pour ces catégories, la sous-catégorie `.8` ne signifie pas « autres formes » mais **« lésion à localisations contiguës »** : elle désigne une tumeur qui empiète sur deux ou trois sous-catégories voisines et dont le point de départ ne peut être déterminé. Dans le résumé clinique, pour un tel code, décris une atteinte qui chevauche plusieurs localisations contiguës d'un même organe, sans désigner un point de départ unique.

**Cas particulier des codes « sans précision » (le plus souvent terminés par `.9`)** : ces codes ne sont employés que lorsque le dossier ne contenait pas l'information détaillée qui aurait permis de choisir un code plus spécifique. Leur présence dans le scénario est donc un signal positif d'incertitude : on sait qu'il y a une pathologie de cette catégorie, mais on ignore volontairement son détail. En conséquence, quand tu décris un tel code dans le résumé clinique, reste délibérément vague : nomme l'entité au niveau général du libellé sans inventer de forme, de cause, de localisation fine, de stade ni de mécanisme précis. Ajouter une précision que le code ne porte pas contredirait la raison même pour laquelle ce code « sans précision » a été retenu plutôt qu'un code plus fin.

# Comment lire les fiches descriptives de codes

Les fiches de codes n’emploient pas toujours explicitement les mots « inclusion », « exclusion », « critères positifs » ou « critères négatifs ».
Dans une fiche, la section **« Périmètre clinique du code »** correspond aux **critères positifs** : elle indique ce qui peut être décrit pour ce code.
La section **« À ne pas décrire »** correspond aux **critères négatifs** : elle indique les diagnostics, causes ou situations à éviter, sauf s’ils sont explicitement codés ailleurs dans le scénario.
La section **« Formulations cliniques alternatives »** correspond aux **synonymes et reformulations autorisées** : tu peux les utiliser pour varier le vocabulaire sans ajouter de précision non portée par le code.
La section **« Position dans la classification »** sert seulement à comprendre le contexte général du code ; elle ne suffit pas à inventer des détails cliniques spécifiques.

**En résumé**, reste strictement dans le périmètre du code : formule le résumé librement à l'intérieur de ce que couvrent libellé, inclusions et synonymes (critères positifs), n'oriente jamais le

#### Deux générations, première — user prompt

**SCÉNARIO DE DÉPART :**
- Âge du patient : 83 ans
- Sexe du patient : Masculin
- Date d'entrée : 18/11/2024
- Date de sortie : 21/11/2024
- Date de naissance : 10/09/1941
- Nom du patient : Neves cordeiro
- Prénom du patient : Jonathann
- Mode d'entrée' : DOMICILE
- Mode de sortie' : DOMICILE
- Contexte de l'hospitalisation : Pour prise en charge diagnostique et thérapeutique du diagnotic principal en hospitalisation complète.
- Codage CIM10 :
   * Diagnostic principal : Autres anémies par carence en fer (D508)
   * Diagnostics associés :
      - Hypertension essentielle (primitive) (I10)
- Nom du médecin / signataire : Genevieve Mainardi
- Service : MEDECINE INTERNE
- Hôpital : Hôpital Claude Huriez - Centre Hospitalier Universitaire de Lille

**FICHES DESCRIPTIVES DES CODES CIM-10 DU SCÉNARIO :**

Les fiches ci-dessous précisent le périmètre des codes CIM-10 présents dans le scénario.
Elles doivent être utilisées pour choisir des formulations compatibles avec les codes, sans ajouter de diagnostic non codé.

<fiche_category code="D50">

# D50 — Anémie par carence en fer

## Position dans la classification
- Chapitre III : Maladies du sang et des organes hématopoïétiques et certains troubles du système immunitaire
- Bloc D50-D53 : Anémies nutritionnelles

## Codes enfants directs
- D50.0 — Anémie par carence en fer secondaire à une perte de sang (chronique)
- D50.1 — Dysphagie sidéropénique
- D50.8 — Autres anémies par carence en fer
- D50.9 — Anémie par carence en fer, sans précision

## Périmètre clinique

Inclusions héritées de la catégorie D50 :
- anémie ferriprive
- anémie :
 - ferriprive
 - hypochrome
- anémie hypochrome

Au niveau des codes :
- anémie posthémorragique (chronique) (D50.0)
- syndrome de Kelly-Paterson (D50.1)
- Syndrome de :
 - Kelly–Paterson
 - Plummer–Vinson
 (D50.1)
- syndrome de Plummer-Vinson (D50.1)

## À ne pas décrire

Affections relevant d'autres codes (hérité du chapitre III) :

certaines affections dont l'origine se situe dans la période périnatale (P00-P96)
complications de la grossesse, de l'accouchement et de la puerpéralité (O00-O99)
lésions traumatiques, empoisonnements et certaines autres conséquences de causes externes (S00-T98)
maladies auto-immunes (systémiques) SAI (M35.9)
maladies dues au virus de l'immunodéficience humaine [VIH] (B20-B24)
maladies endocriniennes, nutritionnelles et métaboliques (E00-E90)
malformations congénitales et anomalies chromosomiques (Q00-Q99)
symptômes, signes et résultats anormaux d'examens cliniques et de laboratoire, non classés ailleurs (R00-R99)
tumeurs (C00-D48)

Affections relevant d'autres codes :

- anémie :
 - congénitale par perte de sang fœtal (P61.3)
 - posthémorragique aigüe (D62)

## Formulations cliniques alternatives
- Anémie (à) (de), achlorhydrique (D50.8)
- Anémie (à) (de), avec, carence en fer (D50.9)
- Anémie (à) (de), hypochrome, hyposidérémique (D50.8)
- Anémie (à) (de), normocytaire (infectieuse), due à hémorragie (chronique) (D50.0)
- Anémie (à) (de), nutritionnelle, sidéropénique (D50.8)
- Anémie (à) (de), par carence (en), fer, due à une perte de sang (chronique) (D50.0)
- anémie carence martiale (D50.9)
- anémie chronique ferriprive (D50.9)
- anémie chronique saignement (D50.0)
- anémie déglobulisation (D50.0)
- anémie déperdition sanguine (D50.0)
- anémie déperditionnelle (D50.0)
- anémie férriprive acutisée (D50.9)
- anémie ferriprive ancienne (D50.9)
- anémie ferriprive chronique (D50.9)
- anémie ferriprive hémorragique chronique (D50.0)
- anémie ferriprive par pertes sanguines (D50.0)
- anémie ferriprive par spoliation chronique (D50.0)
- anémie ferriprive subaigüe (D50.9)
- anémie fuite digestive (D50.0)
- anémie hémorragique chronique (D50.0)
- anémie hypochrome chronique (D50.0)
- anémie hypochrome microcytaire (D50.8)
- anémie hypochrome microcytaire arégénérative (D50.8)
- anémie hypochrome microcytaire hyposidérémique (D50.8)
- anémie hyposidérémique (D50.9)
- anémie inflammatoire ferriprive (D50.9)
- anémie méléna (D50.0)
- anémie microcytaire carentielle (D50.8)
- anémie microcytaire hypochrome arégénérative (D50.8)
- anémie microcytaire hyposidérémique (D50.8)
- anémie microcytaire réfractaire (D50.8)
- anémie microcytaire spoliation digestive (D50.8)
- anémie par hémorragie (D50.0)
- anémie par saignement (D50.0)
- anémie par spoliation sanguine digestive (D50.0)
- anémie perte sanguine (D50.0)
- anémie perte sanguine digestive (D50.0)
- anémie post-rectorragie (D50.0)
- anémie réfractaire par saignement (D50.0)
- anémie sidéropénique réfractaire (D50.9)
- anémie spoliation (D50.0)
- anémie spoliative (D50.0)
- anémie spoliative aigüe (D50.0)
- Carence (en), fer, avec anémie (D50.9)
- Chlorose (D50.8)
- Kelly(-patterson), syndrome de (D50.1)
- Paterson(-kelly), syndrome de (D50.1)
- Sidéropénie, avec anémie (D50.9)
- Witt, anémie de (D50.8)

</fiche_category>

<fiche_code code="I10">

# I10 — Hypertension essentielle (primitive)

## Position dans la classification
- Chapitre IX : Maladies de l'appareil circulatoire
- Bloc I10-I15 : Maladies hypertensives

## Périmètre clinique du code

Au niveau du code :
- hypertension (artérielle) (bénigne) (essentielle) (maligne) (primitive) (systémique)
- tension artérielle élevée

## À ne pas décrire

Affections relevant d'autres codes (hérité du chapitre IX) :

accidents ischémiques cérébraux transitoires et syndromes apparentés (G45.-)
affections disséminées du tissu conjonctif (M30-M36)
certaines affections dont l'origine se situe dans la période périnatale (P00-P96)
certaines maladies infectieuses et parasitaires (A00-B99)
complications de la grossesse, de l'accouchement et de la puerpéralité (O00-O99)
lésions traumatiques, empoisonnements et certaines autres conséquences de causes externes (S00-T98)
maladies endocriniennes, nutritionnelles et métaboliques (E00-E90)
malformations congénitales et anomalies chromosomiques (Q00-Q99)
symptômes, signes et résultats anormaux d'examens cliniques et de laboratoire, non classés ailleurs (R00-R99)
tumeurs (C00-D48)

Affections relevant d'autres codes (hérité du bloc I10-I15) :

cardiopathies ischémiques (I20-I25)
compliquant la grossesse, l'accouchement et la puerpéralité (O10-O11)  (O13-O16)
hypertension :
 - du nouveau-né (P29.2)
 - pulmonaire :
  - primaire (I27.0)
  - secondaire (I27.2)

Affections relevant d'autres codes :

avec :
 - maladies cérébrovasculaires (I60-I69)
 - rétinopathies vasculaires (H35.0)

## Formulations cliniques alternatives
- Elévation de (voir aussi augmentation), pression ou tension (non spécifique), artérielle (voir aussi hypertension)
- HTA bien contrôlée
- HTA contrôlée
- HTA effort
- HTA essentielle
- HTA essentielle "maligne" [coder aussi les conséquences]
- HTA instable
- HTA modérée
- HTA rebelle
- hypertension aigüe
- Hypertension (artérielle) (bénigne) (essentielle) (idiopathique) (maligne) (primitive) (systémique)
- hypertension artérielle idiopathique
- Hypertension artérielle primitive
- polyangiopathie hypertensive
- poussées hypertensives
- Tension, artérielle, élevée (épisodique) (non spécifique), due à hypertension (voir aussi hypertension)

</fiche_code>

#### Deux générations, deuxième — system prompt

Vous êtes un médecin clinicien expert.

Pour cette deuxième génération, votre tâche est de rédiger les documents médicaux finaux à partir du scénario clinique complet et du résumé clinique contrôlé généré lors du premier appel.

Le résumé est fourni en plus du scénario, des fiches descriptives, des actes éventuels et des informations administratives. Il ne remplace aucune de ces données.

# Contexte : le codage CIM-10

La CIM-10 est une classification des maladies, elle peut se définir comme un ensemble organisé de rubriques dans lesquelles on range des entités morbides en fonction de certains critères établis. La CIM est utilisée pour transposer les diagnostics de maladies ou autres problèmes de santé en codes alphanumériques, ce qui facilite le stockage, la recherche et l'analyse des données. Elle est très utilisée en France, en particulier pour le codage des causes de décès et pour la déclaration de l'activité hospitalière dans le cadre du programme de médicalisation des systèmes d'information (PMSI).

Le codage CIM-10 consiste à identifier dans un document médical (CRH, notes d'évolution, comptes-rendus opératoires) les maladies, éventuellement les symptômes et états cliniques en l'absence de maladie clairement identifiée, et à leur attribuer des codes standardisés. C'est une tâche de standardisation d'information, pas une tâche de décision médicale : on traduit ce que le clinicien a écrit en codes normalisés.

# Ta mission : rédiger les documents finaux à partir du scénario et du résumé

Le message utilisateur de cette deuxième génération contient deux sources complémentaires :

1. le scénario clinique complet, avec les codes CIM-10, les fiches descriptives, les actes CCAM éventuels et les informations administratives ;
2. le résumé clinique contrôlé produit par la première génération.

Le résumé est fourni en plus du scénario : il ne remplace jamais le scénario, les fiches ni les actes. Utilise-le comme plan médical intermédiaire pour rédiger les documents finaux demandés par ce template.

La hiérarchie des sources est la suivante : scénario explicite, codes CIM-10, fiches descriptives, actes CCAM, puis résumé clinique. En cas de contradiction, respecte les données sources et ignore l'élément contradictoire du résumé.

Les documents finaux doivent intégrer tous les diagnostics du scénario et aucun autre. Ils doivent respecter les éléments autorisés, la prise en charge et les interdictions du résumé, sans recopier systématiquement ses formulations mot pour mot.

# La nature variable des codes CIM-10

Pour t'aider à bien comprendre le périmètre de chacun des codes choisis, je te fournis également une fiche descriptive par code, qui contient des informations complémentaires issues de la classification et de thésaurus médicaux. La CIM-10 range les entités morbides dans des rubriques selon des critères établis. Concrètement, deux types de critères définissent le périmètre d'un code, et les informations complémentaires correspondent à ces deux logiques :

- des **critères positifs** — ce qui fait entrer une pathologie dans la rubrique. Ils sont portés par les notes d'**inclusion**.
- des **critères négatifs** — ce qui en est explicitement écarté et relève d'un autre code. Ils sont portés par les notes d'**exclusion**.

Les fiches contiennent également des **synonymes** des maladies qui entrent dans le périmètre du code. Tu peux t'en inspirer pour utiliser un vocabulaire moins formel que les libellés et notes officielles de la classification.

**Niveau d'application des inclusions.** Les notes d'inclusion peuvent être attachées à différents niveaux de la hiérarchie (chapitre, bloc, catégorie, code). Plus une inclusion est attachée à un niveau élevé, plus elle est générale et vaut pour de nombreux codes : c'est une définition de cadre, pas une caractéristique propre au code. Par exemple, au niveau du chapitre I, l'inclusion « maladies considérées habituellement comme contagieuses ou transmissibles » s'applique à tous les codes du chapitre et n'ajoute aucune spécificité à l'un d'eux en particulier. À l'inverse, une inclusion attachée directement au code décrit précisément ce que ce code recouvre. Sers-toi des inclusions générales pour comprendre le contexte d'un code, et des inclusions propres au code pour choisir le vocabulaire précis de ta rédaction.

**Point essentiel : les codes n'ont pas tous la même précision clinique.** Certains désignent une entité nette et unique (ex. I10, hypertension artérielle essentielle). D'autres regroupent plusieurs entités hétérogènes sous un même libellé.

**Cas des sous-catégories « autres formes précisées » (le plus souvent `.8`)** : elles rassemblent des entités précises mais diverses qui n'ont pas de code dédié dans la catégorie (ex. B17.8, « autres hépatites virales aiguës précisées »). Le libellé officiel ne suffit alors pas à savoir quelle pathologie réelle décrire ; appuie-toi sur les inclusions et synonymes propres au code.

**Cas particulier des cancers (chapitre II, catégories C00-C75)** : la CIM-10 classe les tumeurs malignes primitives essentiellement selon leur siège anatomique, et en grands groupes selon le comportement de la tumeur ; la morphologie n'apparaît qu'exceptionnellement dans le titre. Deux conséquences :

- la granularité d'un code par rapport à sa catégorie est avant tout une précision **anatomique**. Un code plus spécifique te donne une localisation plus précise, pas un type histologique plus précis ;
- pour ces catégories, la sous-catégorie `.8` ne signifie pas « autres formes » mais **« lésion à localisations contiguës »** : elle désigne une tumeur qui empiète sur deux ou trois sous-catégories voisines et dont le point de départ ne peut être déterminé. Quand tu rédiges pour un tel code, décris une atteinte qui chevauche plusieurs localisations contiguës d'un même organe, sans désigner un point de départ unique.

**Cas particulier des codes « sans précision » (le plus souvent terminés par `.9`)** : ces codes ne sont employés que lorsque le dossier ne contenait pas l'information détaillée qui aurait permis de choisir un code plus spécifique. Leur présence dans le scénario est donc un signal positif d'incertitude : on sait qu'il y a une pathologie de cette catégorie, mais on ignore volontairement son détail. En conséquence, quand tu mentionnes un tel code dans le compte rendu, reste délibérément vague : nomme l'entité au niveau général du libellé sans inventer de forme, de cause, de localisation fine, de stade ni de mécanisme précis. Ajouter une précision que le code ne porte pas contredirait la raison même pour laquelle ce code « sans précision » a été retenu plutôt qu'un code plus fin.

# Comment lire les fiches descriptives de codes

Les fiches de codes n’emploient pas toujours explicitement les mots « inclusion », « exclusion », « critères positifs » ou « critères négatifs ».
Dans une fiche, la section **« Périmètre clinique du code »** correspond aux **critères positifs** : elle indique ce qui peut être décrit pour ce code.
La section **« À ne pas décrire »** correspond aux **critères négatifs** : elle indique les diagnostics, causes ou situations à éviter, sauf s’ils sont explicitement codés ailleurs dans le scénario.
La section **« Formulations cliniques alternatives »** correspond aux **synonymes et reformulations autorisées** : tu peux les utiliser pour varier le vocabulaire sans ajouter de précision non portée par le code.
La section **« Position dans la classification »** sert seulement à comprendre le contexte général du code ; elle ne suffit pas à inventer des détails cliniques spécifiques.

**En résumé**, reste strictement dans le périmètre du code : reformule librement à l'intérieur de ce que couvrent libellé, inclusions et synonymes (critères positifs), n'oriente jamais ta rédaction vers une entité exclue (critères négatifs), traite les `.8` cancérologiques comme des atteintes plurifocales contiguës, et respecte le flou volontaire des codes « sans précision ».

#

#### Deux générations, deuxième — user prompt

**SCÉNARIO DE DÉPART :**
- Âge du patient : 83 ans
- Sexe du patient : Masculin
- Date d'entrée : 18/11/2024
- Date de sortie : 21/11/2024
- Date de naissance : 10/09/1941
- Nom du patient : Neves cordeiro
- Prénom du patient : Jonathann
- Mode d'entrée' : DOMICILE
- Mode de sortie' : DOMICILE
- Contexte de l'hospitalisation : Pour prise en charge diagnostique et thérapeutique du diagnotic principal en hospitalisation complète.
- Codage CIM10 :
   * Diagnostic principal : Autres anémies par carence en fer (D508)
   * Diagnostics associés :
      - Hypertension essentielle (primitive) (I10)
- Nom du médecin / signataire : Genevieve Mainardi
- Service : MEDECINE INTERNE
- Hôpital : Hôpital Claude Huriez - Centre Hospitalier Universitaire de Lille

**FICHES DESCRIPTIVES DES CODES CIM-10 DU SCÉNARIO :**

Les fiches ci-dessous précisent le périmètre des codes CIM-10 présents dans le scénario.
Elles doivent être utilisées pour choisir des formulations compatibles avec les codes, sans ajouter de diagnostic non codé.

<fiche_category code="D50">

# D50 — Anémie par carence en fer

## Position dans la classification
- Chapitre III : Maladies du sang et des organes hématopoïétiques et certains troubles du système immunitaire
- Bloc D50-D53 : Anémies nutritionnelles

## Codes enfants directs
- D50.0 — Anémie par carence en fer secondaire à une perte de sang (chronique)
- D50.1 — Dysphagie sidéropénique
- D50.8 — Autres anémies par carence en fer
- D50.9 — Anémie par carence en fer, sans précision

## Périmètre clinique

Inclusions héritées de la catégorie D50 :
- anémie ferriprive
- anémie :
 - ferriprive
 - hypochrome
- anémie hypochrome

Au niveau des codes :
- anémie posthémorragique (chronique) (D50.0)
- syndrome de Kelly-Paterson (D50.1)
- Syndrome de :
 - Kelly–Paterson
 - Plummer–Vinson
 (D50.1)
- syndrome de Plummer-Vinson (D50.1)

## À ne pas décrire

Affections relevant d'autres codes (hérité du chapitre III) :

certaines affections dont l'origine se situe dans la période périnatale (P00-P96)
complications de la grossesse, de l'accouchement et de la puerpéralité (O00-O99)
lésions traumatiques, empoisonnements et certaines autres conséquences de causes externes (S00-T98)
maladies auto-immunes (systémiques) SAI (M35.9)
maladies dues au virus de l'immunodéficience humaine [VIH] (B20-B24)
maladies endocriniennes, nutritionnelles et métaboliques (E00-E90)
malformations congénitales et anomalies chromosomiques (Q00-Q99)
symptômes, signes et résultats anormaux d'examens cliniques et de laboratoire, non classés ailleurs (R00-R99)
tumeurs (C00-D48)

Affections relevant d'autres codes :

- anémie :
 - congénitale par perte de sang fœtal (P61.3)
 - posthémorragique aigüe (D62)

## Formulations cliniques alternatives
- Anémie (à) (de), achlorhydrique (D50.8)
- Anémie (à) (de), avec, carence en fer (D50.9)
- Anémie (à) (de), hypochrome, hyposidérémique (D50.8)
- Anémie (à) (de), normocytaire (infectieuse), due à hémorragie (chronique) (D50.0)
- Anémie (à) (de), nutritionnelle, sidéropénique (D50.8)
- Anémie (à) (de), par carence (en), fer, due à une perte de sang (chronique) (D50.0)
- anémie carence martiale (D50.9)
- anémie chronique ferriprive (D50.9)
- anémie chronique saignement (D50.0)
- anémie déglobulisation (D50.0)
- anémie déperdition sanguine (D50.0)
- anémie déperditionnelle (D50.0)
- anémie férriprive acutisée (D50.9)
- anémie ferriprive ancienne (D50.9)
- anémie ferriprive chronique (D50.9)
- anémie ferriprive hémorragique chronique (D50.0)
- anémie ferriprive par pertes sanguines (D50.0)
- anémie ferriprive par spoliation chronique (D50.0)
- anémie ferriprive subaigüe (D50.9)
- anémie fuite digestive (D50.0)
- anémie hémorragique chronique (D50.0)
- anémie hypochrome chronique (D50.0)
- anémie hypochrome microcytaire (D50.8)
- anémie hypochrome microcytaire arégénérative (D50.8)
- anémie hypochrome microcytaire hyposidérémique (D50.8)
- anémie hyposidérémique (D50.9)
- anémie inflammatoire ferriprive (D50.9)
- anémie méléna (D50.0)
- anémie microcytaire carentielle (D50.8)
- anémie microcytaire hypochrome arégénérative (D50.8)
- anémie microcytaire hyposidérémique (D50.8)
- anémie microcytaire réfractaire (D50.8)
- anémie microcytaire spoliation digestive (D50.8)
- anémie par hémorragie (D50.0)
- anémie par saignement (D50.0)
- anémie par spoliation sanguine digestive (D50.0)
- anémie perte sanguine (D50.0)
- anémie perte sanguine digestive (D50.0)
- anémie post-rectorragie (D50.0)
- anémie réfractaire par saignement (D50.0)
- anémie sidéropénique réfractaire (D50.9)
- anémie spoliation (D50.0)
- anémie spoliative (D50.0)
- anémie spoliative aigüe (D50.0)
- Carence (en), fer, avec anémie (D50.9)
- Chlorose (D50.8)
- Kelly(-patterson), syndrome de (D50.1)
- Paterson(-kelly), syndrome de (D50.1)
- Sidéropénie, avec anémie (D50.9)
- Witt, anémie de (D50.8)

</fiche_category>

<fiche_code code="I10">

# I10 — Hypertension essentielle (primitive)

## Position dans la classification
- Chapitre IX : Maladies de l'appareil circulatoire
- Bloc I10-I15 : Maladies hypertensives

## Périmètre clinique du code

Au niveau du code :
- hypertension (artérielle) (bénigne) (essentielle) (maligne) (primitive) (systémique)
- tension artérielle élevée

## À ne pas décrire

Affections relevant d'autres codes (hérité du chapitre IX) :

accidents ischémiques cérébraux transitoires et syndromes apparentés (G45.-)
affections disséminées du tissu conjonctif (M30-M36)
certaines affections dont l'origine se situe dans la période périnatale (P00-P96)
certaines maladies infectieuses et parasitaires (A00-B99)
complications de la grossesse, de l'accouchement et de la puerpéralité (O00-O99)
lésions traumatiques, empoisonnements et certaines autres conséquences de causes externes (S00-T98)
maladies endocriniennes, nutritionnelles et métaboliques (E00-E90)
malformations congénitales et anomalies chromosomiques (Q00-Q99)
symptômes, signes et résultats anormaux d'examens cliniques et de laboratoire, non classés ailleurs (R00-R99)
tumeurs (C00-D48)

Affections relevant d'autres codes (hérité du bloc I10-I15) :

cardiopathies ischémiques (I20-I25)
compliquant la grossesse, l'accouchement et la puerpéralité (O10-O11)  (O13-O16)
hypertension :
 - du nouveau-né (P29.2)
 - pulmonaire :
  - primaire (I27.0)
  - secondaire (I27.2)

Affections relevant d'autres codes :

avec :
 - maladies cérébrovasculaires (I60-I69)
 - rétinopathies vasculaires (H35.0)

## Formulations cliniques alternatives
- Elévation de (voir aussi augmentation), pression ou tension (non spécifique), artérielle (voir aussi hypertension)
- HTA bien contrôlée
- HTA contrôlée
- HTA effort
- HTA essentielle
- HTA essentielle "maligne" [coder aussi les conséquences]
- HTA instable
- HTA modérée
- HTA rebelle
- hypertension aigüe
- Hypertension (artérielle) (bénigne) (essentielle) (idiopathique) (maligne) (primitive) (systémique)
- hypertension artérielle idiopathique
- Hypertension artérielle primitive
- polyangiopathie hypertensive
- poussées hypertensives
- Tension, artérielle, élevée (épisodique) (non spécifique), due à hypertension (voir aussi hypertension)

</fiche_code>

## 9. Configuration Mistral

`GENERATION_MODE` peut valoir `none`, `one`, `two` ou `both`. Les tarifs sont des variables de configuration : les mettre à jour en même temps que le modèle lorsque nécessaire.

In [ ]:
GENERATION_MODE = "two"  # "none", "one", "two" ou "both"
MODEL = os.getenv("MISTRAL_MODEL", "mistral-large-latest")

MAX_TOKENS_SUMMARY = 8_000
MAX_TOKENS_CR = 128_000
POLL_INTERVAL_SECONDS = 1

USE_ORIGINAL_PREFIX_ONE_GEN = True
USE_ORIGINAL_PREFIX_SECOND_GEN = True
FIRST_GEN_PREFIX = "Résumé clinique :"

SUMMARY_INSERT_HEADER = """
### RÉSUMÉ CLINIQUE ISSU DE LA PREMIÈRE GÉNÉRATION
Le résumé ci-dessous est une aide intermédiaire.
Le scénario clinique, les codes, les fiches descriptives et les instructions
restent prioritaires en cas de divergence.
"""

SUMMARY_INSERT_FOOTER = """
### FIN DU RÉSUMÉ CLINIQUE INTERMÉDIAIRE
"""

MISTRAL_BATCH_INPUT_USD_PER_MILLION = 0.25
MISTRAL_BATCH_OUTPUT_USD_PER_MILLION = 0.75

MISTRAL_API_KEY = "xxx" ### A COMPLETER

print("Mode                         :", GENERATION_MODE)
print("Modèle                       :", MODEL)
print("Clé Mistral disponible       :", bool(MISTRAL_API_KEY))
print("MAX_TOKENS_SUMMARY           :", MAX_TOKENS_SUMMARY)
print("MAX_TOKENS_CR                :", MAX_TOKENS_CR)
print(
    "Tarif Batch entrée / 1M tok :",
    f"${MISTRAL_BATCH_INPUT_USD_PER_MILLION:.2f}",
)
print(
    "Tarif Batch sortie / 1M tok :",
    f"${MISTRAL_BATCH_OUTPUT_USD_PER_MILLION:.2f}",
)

Mode                         : two
Modèle                       : mistral-large-latest
Clé Mistral disponible       : True
MAX_TOKENS_SUMMARY           : 8000
MAX_TOKENS_CR                : 128000
Tarif Batch entrée / 1M tok : $0.25
Tarif Batch sortie / 1M tok : $0.75

## 10. Exécution Mistral et bilan tokens/coûts

In [13]:
GENERATION_RESULTS = utils.run_generation_workflow(
    generation_mode=GENERATION_MODE,
    api_key=MISTRAL_API_KEY,
    run_dir=RUN_DIR,
    paths=PATHS,
    model=MODEL,
    max_tokens_summary=MAX_TOKENS_SUMMARY,
    max_tokens_cr=MAX_TOKENS_CR,
    poll_interval_seconds=POLL_INTERVAL_SECONDS,
    use_original_prefix_one_gen=USE_ORIGINAL_PREFIX_ONE_GEN,
    use_original_prefix_second_gen=USE_ORIGINAL_PREFIX_SECOND_GEN,
    first_gen_prefix=FIRST_GEN_PREFIX,
    summary_insert_header=SUMMARY_INSERT_HEADER,
    summary_insert_footer=SUMMARY_INSERT_FOOTER,
    batch_input_usd_per_million=(
        MISTRAL_BATCH_INPUT_USD_PER_MILLION
    ),
    batch_output_usd_per_million=(
        MISTRAL_BATCH_OUTPUT_USD_PER_MILLION
    ),
)

print("Mode exécuté :", GENERATION_RESULTS["mode"])
print("Bilans usage :", list(GENERATION_RESULTS["usage"]))

if "usage_output_path" in GENERATION_RESULTS:
    print("Bilan JSON    :", GENERATION_RESULTS["usage_output_path"])

========================================================================================
Lancement batch Mistral
========================================================================================
Modèle                   : mistral-large-latest
Nombre de requêtes       : 1
Limite tokens de sortie  : 8000
Fichier JSONL d'entrée   : /home/cdechaux/Documents/AOC/codes/Stream/work_modif_prompts/test_xx/_mistral_batches/two_gen_first/batch_input_20260806_133356_810721.jsonl
Batch job ID             : 2be7b148-bf70-4536-b627-73da94a8fdf9
Statut : SUCCESS — 1/1
Statut final             : SUCCESS
Résultats JSONL          : /home/cdechaux/Documents/AOC/codes/Stream/work_modif_prompts/test_xx/_mistral_batches/two_gen_first/batch_output_20260806_133356_810721.jsonl
OK — première génération / résumés: 1 sortie(s)

========================================================================================
PREMIÈRE GÉNÉRATION — RÉSUMÉS
========================================================================================
Nombre de requêtes       : 1
Tokens d'entrée          : 7 757
Tokens de sortie         : 2 801
Tokens totaux            : 10 558
Moyenne / requête        : 10 558
Coût entrée estimé       : $0.001939
Coût sortie estimé       : $0.002101
COÛT TOTAL ESTIMÉ        : $0.004040

========================================================================================
Lancement batch Mistral
========================================================================================
Modèle                   : mistral-large-latest
Nombre de requêtes       : 1
Limite tokens de sortie  : 128000
Fichier JSONL d'entrée   : /home/cdechaux/Documents/AOC/codes/Stream/work_modif_prompts/test_xx/_mistral_batches/two_gen_second/batch_input_20260806_133501_759035.jsonl
Batch job ID             : 124e92b9-fbfd-478e-9d5f-5f6349e37cab
Statut : SUCCESS — 1/1
Statut final             : SUCCESS
Résultats JSONL          : /home/cdechaux/Documents/AOC/codes/Stream/work_modif_prompts/test_xx/_mistral_batches/two_gen_second/batch_output_20260806_133501_759035.jsonl
OK — deuxième génération / CR: 1 sortie(s)

========================================================================================
DEUXIÈME GÉNÉRATION — CR
========================================================================================
Nombre de requêtes       : 1
Tokens d'entrée          : 11 667
Tokens de sortie         : 3 166
Tokens totaux            : 14 833
Moyenne / requête        : 14 833
Coût entrée estimé       : $0.002917
Coût sortie estimé       : $0.002374
COÛT TOTAL ESTIMÉ        : $0.005291

########################################################################################
TOTAL — GÉNÉRATION EN DEUX ÉTAPES
########################################################################################
Nombre total de requêtes : 2
Tokens d'entrée totaux   : 19 424
Tokens de sortie totaux  : 5 967
TOKENS TOTAUX            : 25 391
COÛT TOTAL ESTIMÉ        : $0.009331

Sorties two-step : /home/cdechaux/Documents/AOC/codes/Stream/work_modif_prompts/test_xx/sorties/resume_CR_2gen

Bilan tokens/coûts écrit : /home/cdechaux/Documents/AOC/codes/Stream/work_modif_prompts/test_xx/sorties/mistral_token_usage_and_cost.json
Mode exécuté : two
Bilans usage : ['two_generation_first', 'two_generation_second', 'two_generation_total']
Bilan JSON    : /home/cdechaux/Documents/AOC/codes/Stream/work_modif_prompts/test_xx/sorties/mistral_token_usage_and_cost.json

## 11. Visualisation d’un scénario et de ses sorties

In [14]:
VIEW_INDEX = 0

utils.visualize_run_outputs(
    run_dir=RUN_DIR,
    paths=PATHS,
    view_index=VIEW_INDEX,
    scenario_max_chars=12_000,
    output_max_chars=20_000,
)

# Visualisation
- `generation_id` : `6a1a14c5-67b5-4adc-9ac2-94b39b2a9127`
- `template_name` : `medical_inpatient.txt`
- `DP` : `I638`
- `racine GHM` : `01M30`

## Scénario

**SCÉNARIO DE DÉPART :**
- Âge du patient : 72 ans
- Sexe du patient : Masculin
- Date d'entrée : 01/05/2025
- Date de sortie : 18/05/2025
- Date de naissance : 25/02/1953
- Nom du patient : Guery
- Prénom du patient : Nicolas
- Mode d'entrée' : DOMICILE
- Mode de sortie' : DOMICILE
- Contexte de l'hospitalisation : Pour prise en charge diagnostique et thérapeutique du diagnotic principal en hospitalisation complète.
- Codage CIM10 :
   * Diagnostic principal : Autres infarctus cérébraux (I638)
   * Diagnostics associés :
      - Ataxie, sans précision (R270)
      - Dysarthrie et anarthrie (R471)
      - Diabète sucré de type 2 non insulinotraité ou sans précision, sans complication (E1198)
      - Autres avitaminoses précisées du groupe B (E538)
      - Trouble anxieux et dépressif mixte (F412)
      - Diplopie (H532)
      - Nystagmus et autres anomalies des mouvements oculaires (H55)
      - Antécédents personnels de non-observance d'un traitement médical et d'un régime (Z911)
- Nom du médecin / signataire : Odette Offret
- Service : NEURO-VASCULAIRE
- Hôpital : Hôpital Pitié-Salpêtrière - Assistance Publique Hôpitaux de Paris

## Résumé — première génération

Résumé clinique : voici le JSON strictement conforme à la demande.

```json
{
  "resume_clinique": [
    {
      "code_CIM10": "I63.8",
      "definition_code": "Autres infarctus cérébraux",
      "formulations_cliniques_autorisees": [
        "Infarctus cérébral de type précisé non classé ailleurs",
        "Ramollissement cérébral par artériosclérose",
        "Syndrome artériel cérébelleux supérieur"
      ],
      "elements_cliniques_autorises": "Occlusion ou sténose des artères cérébrales ou précérébrales entraînant un infarctus cérébral, avec ou sans mention d'hypertension associée. Localisation et mécanisme non précisés.",
      "prise_en_charge_pendant_le_sejour": "Prise en charge diagnostique (imagerie cérébrale, bilan étiologique vasculaire) et thérapeutique (traitement antiagrégant ou anticoagulant selon étiologie, contrôle des facteurs de risque vasculaire, rééducation neurologique). Surveillance des complications neurologiques.",
      "elements_a_ne_pas_ajouter": [
        "Mécanisme précis (thrombose, embolie, etc.)",
        "Localisation cérébrale spécifique (ex. territoire sylvien)",
        "Séquelles d'infarctus cérébral (codé I69.3)",
        "Accident ischémique transitoire (G45.-)",
        "Démence vasculaire (F01.-)",
        "Hémorragie intracrânienne traumatique (S06.-)"
      ]
    },
    {
      "code_CIM10": "R27.0",
      "definition_code": "Ataxie, sans précision",
      "formulations_cliniques_autorisees": [
        "Ataxie",
        "Troubles ataxiques non spécifiés"
      ],
      "elements_cliniques_autorises": "Trouble de la coordination motrice sans précision de cause, de type ou de localisation. Peut être d'origine cérébelleuse, sensitive ou vestibulaire.",
      "prise_en_charge_pendant_le_sejour": "Évaluation clinique et paraclinique (imagerie, bilan métabolique) pour déterminer l'origine. Rééducation fonctionnelle adaptée (kinésithérapie, ergothérapie).",
      "elements_a_ne_pas_ajouter": [
        "Cause spécifique (ex. héréditaire, carentielle)",
        "Localisation précise (ex. ataxie cérébelleuse)",
        "Démarche ataxique isolée (R26.0)",
        "Vertige (R42)"
      ]
    },
    {
      "code_CIM10": "R47.1",
      "definition_code": "Dysarthrie et anarthrie",
      "formulations_cliniques_autorisees": [
        "Dysarthrie",
        "Anarthrie",
        "Dysarthrie paralytique ou séquellaire"
      ],
      "elements_cliniques_autorises": "Trouble de l'articulation de la parole, sans précision de cause ou de type. Peut être d'origine centrale ou périphérique.",
      "prise_en_charge_pendant_le_sejour": "Bilan orthophonique et neurologique. Rééducation orthophonique si indiquée. Adaptation des moyens de communication si nécessaire.",
      "elements_a_ne_pas_ajouter": [
        "Cause spécifique (ex. AVC, sclérose en plaques)",
        "Troubles spécifiques du développement de la parole (F80.-)",
        "Bégaiement (F98.5)",
        "Autisme (F84.0-F84.1)"
      ]
    },
    {
      "code_CIM10": "E11.98",
      "definition_code": "Diabète sucré de type 2 non insulinotraité ou sans précision, sans complication",
      "formulations_cliniques_autorisees": [
        "Diabète de type 2 non insulinodépendant",
        "Diabète sucré de type 2 stable",
        "Diabète de l'adulte sans complication"
      ],
      "elements_cliniques_autorises": "Diabète sucré de type 2, sans précision de traitement (insulinothérapie ou non) et sans complication métabolique ou organique associée. Peut être associé à une obésité ou non.",
      "prise_en_charge_pendant_le_sejour": "Contrôle glycémique (régime, antidiabétiques oraux si nécessaire). Éducation thérapeutique. Surveillance des complications chroniques (néphropathie, rétinopathie, neuropathie).",
      "elements_a_ne_pas_ajouter": [
        "Complications spécifiques (ex. rétinopathie, néphropathie)",
        "Diabète gestationnel (O24.-)",
        "Diabète de type 1 (E10.-)",
        "Glycosurie rénale (E74.8)"
      ]
    },
    {
      "code_CIM10": "E53.8",
      "definition_code": "Autres avitaminoses précisées du groupe B",
      "formulations_cliniques_autorisees": [
        "Carence en vitamine B12",
        "Carence en acide folique",
        "Déficit en folates",
        "Hypovitaminose B12",
        "Sclérose combinée de la moelle par carence en vitamine B12",
        "Neuropathie carentielle en vitamine B12"
      ],
      "elements_cliniques_autorises": "Carence en vitamines du groupe B précisées (B12, folates, acide pantothénique, biotine, cyanocobalamine). Peut inclure des manifestations neurologiques (myélopathie, neuropathie) ou hématologiques (sans anémie codée séparément).",
      "prise_en_charge_pendant_le_sejour": "Supplémentation vitaminique (B12, folates) par voie orale ou parentérale selon le déficit. Bilan étiologique (malabsorption, carence d'apport). Surveillance de la réponse clinique et biologique.",
      "elements_a_ne_pas_ajouter": [
        "Anémie par carence en vitamine B12 (D51.-)",
        "Carence en pyridoxine (E53.1)",
        "Carence en riboflavine (E53.0)",
        "Séquelles d'avitaminose (E64.8)"
      ]
    },
    {
      "code_CIM10": "F41.2",
      "definition_code": "Trouble anxieux et dépressif mixte",
      "formulations_cliniques_autorisees": [
        "Trouble anxio-dépressif",
        "Syndrome anxio-dépressif",
        "Anxiété avec dépression associée",
        "État anxio-dépressif chronique",
        "Névrose anxio-dépressive"
      ],
      "elements_cliniques_autorises": "Association de symptômes anxieux et dépressifs sans prédominance nette de l'un ou l'autre. Peut inclure des symptômes physiques (fatigue, troubles du sommeil) ou cognitifs (rumination, difficultés de concentration).",
      "prise_en_charge_pendant_le_sejour": "Évaluation psychiatrique. Prise en charge psychothérapeutique (TCC, soutien) et/ou pharmacologique (antidépresseurs, anxiolytiques si nécessaire). Surveillance de l'évolution clinique.",
      "elements_a_ne_pas_ajouter": [
        "Trouble panique avec agoraphobie (F40.0)",
        "Dépression majeure isolée (F32.- ou F33.-)",
        "Anxiété généralisée pure (F41.1)",
        "Neurasthénie (F48.0)"
      ]
    },
    {
      "code_CIM10": "H53.2",
      "definition_code": "Diplopie",
      "formulations_cliniques_autorisees": [
        "Diplopie",
        "Vision double"
      ],
      "elements_cliniques_autorises": "Perception de deux images pour un seul objet, sans précision de cause, de type (binoculaire/monoculaire) ou de mécanisme.",
      "prise_en_charge_pendant_le_sejour": "Bilan ophtalmologique et neurologique (examen des paires crâniennes, imagerie si nécessaire). Prise en charge étiologique si cause identifiée (ex. correction d'un trouble oculomoteur).",
      "elements_a_ne_pas_ajouter": [
        "Cause spécifique (ex. paralysie du VI, myasthénie)",
        "Diplopie monoculaire (liée à une pathologie oculaire)",
        "Troubles de la réfraction non corrigés"
      ]
    },
    {
      "code_CIM10": "H55",
      "definition_code": "Nystagmus et autres anomalies des mouvements oculaires",
      "formulations_cliniques_autorisees": [
        "Nystagmus",
        "Nystagmus congénital ou acquis non précisé",
        "Anomalies des mouvements oculaires non classées ailleurs",
        "Mouvements oculaires anormaux"
      ],
      "elements_cliniques_autorises": "Mouvements oculaires involontaires, rythmiques ou non, sans précision de type (congénital, dissocié, latent) ou de cause. Peut inclure d'autres anomalies oculomotrices non spécifiées.",
      "prise_en_charge_pendant_le_sejour": "Évaluation ophtalmologique et neurologique (recherche d'une cause centrale ou périphérique). Imagerie cérébrale si suspicion de lésion neurologique. Prise en charge symptomatique si nécessaire.",
      "elements_a_ne_pas_ajouter": [
        "Cause spécifique (ex. sclérose en plaques, AVC)",
        "Type précis de nystagmus (ex. nystagmus vestibulaire)",
        "Vertige associé (R42)"
      ]
    },
    {
      "code_CIM10": "Z91.1",
      "definition_code": "Antécédents personnels de non-observance d'un traitement médical et d'un régime",
      "formulations_cliniques_autorisees": [
        "Antécédent de non-observance thérapeutique",
        "Inobservance passée d'un traitement médical ou d'un régime",
        "Difficultés antérieures à suivre un traitement ou un régime prescrit"
      ],
      "elements_cliniques_autorises": "Antécédent documenté de non-respect des prescriptions médicales (médicaments, régime) sans précision de cause ou de contexte. Peut inclure des oublis, des refus ou des difficultés d'adhésion.",
      "prise_en_charge_pendant_le_sejour": "Évaluation des causes de non-observance (facteurs socio-économiques, psychologiques, méconnaissance). Éducation thérapeutique renforcée. Adaptation du traitement si nécessaire (simplification, suivi rapproché).",
      "elements_a_ne_pas_ajouter": [
        "Cause spécifique de non-observance (ex. déni, précarité)",
        "Non-observance actuelle (à coder si pertinent)",
        "Antécédents d'abus de substances (Z86.4)"
      ]
    }
  ],
  "synthese_sejour": "Patient de 72 ans hospitalisé en service neuro-vasculaire pour prise en charge diagnostique et thérapeutique d'un infarctus cérébral (I63.8) compliqué de symptômes neurologiques (ataxie R27.0, dysarthrie R47.1, diplopie H53.2, nystagmus H55). Contexte de diabète de type 2 non compliqué (E11.98) et de carence vitaminique du groupe B (E53.8), avec antécédent de non-observance thérapeutique (Z91.1). Trouble anxio-dépressif mixte (F41.2) associé. Prise en charge pluridisciplinaire (neurologique, diabétologique, psychiatrique, rééducative) sans précision de traitement spécifique ou de résultat d'examen non codé."
}
```

## CR — deuxième génération

Le compte rendu suivant respecte les élements suivants :
        - les diagnostics ont une formulation moins formelle que la définition du code
        - le plan du CRH est conforme aux recommandations. Les sections sont détaillées et cohérentes entre elles.
        - les dates sont plausibles et cohérentes
        - les informations obligatoires sont présentes
        - les informations sur le cancer sont détaillées si pertinent
        - les informations sont exhaustives et précises

```json
{
  "CR": "### Hôpital Pitié-Salpêtrière - Assistance Publique Hôpitaux de Paris
Service NEURO-VASCULAIRE

**Patient :**
Nom : Guery
Prénom : Nicolas
Date de naissance : 25/02/1953
Âge : 72 ans

---

### Motif d’hospitalisation
M. Nicolas Guery, 72 ans, a été admis le 01/05/2025 pour exploration et prise en charge d’un déficit neurologique d’installation brutale associant des troubles de la coordination, des difficultés d’élocution et une vision double. Ces symptômes ont motivé une hospitalisation en urgence dans notre service de neuro-vasculaire pour bilan étiologique et thérapeutique.

---

### Antécédents
**Médicaux :**
- Diabète de type 2 connu, non insulinodépendant, sans complication apparente à ce jour.
- Antécédent de non-observance thérapeutique et diététique, notamment concernant la prise en charge de son diabète.
- Syndrome anxio-dépressif chronique, traité de manière irrégulière.

**Chirurgicaux :**
Aucun antécédent chirurgical notable.

**Familiaux :**
Non contributifs.

**Allergies :**
Aucune allergie médicamenteuse connue.

---

### Mode de vie
M. Guery est retraité, ancien employé dans le secteur tertiaire. Il vit seul à domicile et présente une consommation occasionnelle d’alcool, sans notion d’intoxication tabagique actuelle. Son activité physique est limitée en raison de ses troubles neurologiques récents. Sur le plan social, il bénéficie d’un soutien familial occasionnel, mais son isolement relatif a pu contribuer à une mauvaise observance de ses traitements antérieurs.

---

### Histoire de la maladie
Le patient rapporte l’apparition brutale, le 30/04/2025, d’une sensation de déséquilibre avec difficultés à marcher, associée à une élocution troublée et une vision double. Ces symptômes ont persisté, motivant une consultation aux urgences le lendemain. À l’admission, le tableau clinique évoquait un accident vasculaire cérébral, justifiant son transfert en unité neuro-vasculaire pour exploration.

Par ailleurs, M. Guery décrit depuis plusieurs mois une fatigue persistante, des fourmillements aux extrémités et une aggravation progressive de son état anxio-dépressif, avec des épisodes de rumination et des troubles du sommeil.

---

### Examen clinique
**Constantes vitales à l’admission (01/05/2025) :**
- Pression artérielle : 150/90 mmHg
- Fréquence cardiaque : 85 battements/minute, régulière
- Saturation en oxygène : 96 % en air ambiant
- Température : 36,8°C
- Poids : 78 kg (stable par rapport aux dernières consultations)

**Examen neurologique :**
- Marche ataxique, avec élargissement du polygone de sustentation.
- Dysarthrie modérée, sans aphasie.
- Diplopie binoculaire, sans anomalie pupillaire notable.
- Nystagmus horizontal bilatéral, plus marqué dans le regard latéral.
- Pas de déficit moteur ou sensitif franc aux membres.
- Réflexes ostéotendineux présents et symétriques, sans signe de Babinski.

**Examen général :**
- État général conservé, score ECOG à 1 (symptomatique mais ambulatoire).
- Pas de signe de dénutrition.
- Examen cardiovasculaire sans particularité.
- Abdomen souple, sans hépatosplénomégalie.
- Pas d’œdème des membres inférieurs.

---

### Examens complémentaires
**Imagerie :**
- **IRM cérébrale (02/05/2025) :** Mise en évidence d’un infarctus cérébral récent dans le territoire vertébro-basilaire, sans signe d’hémorragie associée. Pas de lésion tumorale ou de malformation vasculaire.
- **Angio-IRM des vaisseaux cervico-encéphaliques (02/05/2025) :** Sténose modérée de l’artère vertébrale gauche, sans occlusion significative.

**Bilan biologique (01/05/2025) :**
- **NFS :** Hémoglobine à 13,2 g/dL, VGM à 98 fL (légère macrocytose), plaquettes et leucocytes dans les normes.
- **Bilan hépatique :** Normal.
- **Créatinine :** 95 µmol/L (DFG estimé à 65 mL/min/1,73m²).
- **Glycémie à jeun :** 1,80 g/L, HbA1c à 8,2 %.
- **Vitamine B12 :** 180 pg/mL (valeurs normales : 200-900 pg/mL), folates à 3,2 ng/mL (valeurs normales : 3-17 ng/mL).
- **Bilan thyroïdien :** Normal.
- **Bilan lipidique :** LDL-cholestérol à 1,40 g/L, HDL-cholestérol à 0,45 g/L, triglycérides à 1,80 g/L.

**Autres examens :**
- **Électrocardiogramme (01/05/2025) :** Rythme sinusal, sans trouble de la repolarisation.
- **Échographie Doppler des troncs supra-aortiques (03/05/2025) :** Confirmation d’une sténose modérée de l’artère vertébrale gauche, sans autre anomalie significative.
- **Évaluation psychiatrique (05/05/2025) :** Syndrome anxio-dépressif modéré, avec composante anxieuse prédominante. Pas de signe de dépression majeure.

---

### Évolution pendant l'hospitalisation
**Démarche diagnostique :**
Le bilan initial a confirmé le diagnostic d’infarctus cérébral dans le territoire vertébro-basilaire, compliqué d’une ataxie, d’une dysarthrie et de troubles oculomoteurs (diplopie et nystagmus). L’exploration étiologique a mis en évidence une sténose vertébrale gauche, probablement athéromateuse, ainsi qu’une carence en vitamine B12 et en folates, possiblement liée à une mauvaise observance diététique et à un diabète mal équilibré.

**Traitements :**
- **Traitement antiagrégant :** Introduction d’aspirine 160 mg/jour dès le 02/05/2025, en prévention secondaire des accidents ischémiques.
- **Contrôle des facteurs de risque vasculaire :**
  - Optimisation du traitement antidiabétique : introduction de metformine 1000 mg/jour, avec surveillance glycémique rapprochée.
  - Introduction d’une statine (atorvastatine 40 mg/jour) pour le contrôle du LDL-cholestérol.
  - Traitement antihypertenseur par inhibiteur de l’enzyme de conversion (périndopril 5 mg/jour).
- **Supplémentation vitaminique :** Vitamine B12 par voie intramusculaire (1000 µg/jour pendant 7 jours, puis relais per os) et acide folique (5 mg/jour per os).
- **Rééducation neurologique :**
  - Séances de kinésithérapie quotidiennes pour travail de l’équilibre et de la marche.
  - Séances d’orthophonie pour prise en charge de la dysarthrie.
- **Prise en charge psychiatrique :** Introduction d’un antidépresseur (sertraline 50 mg/jour) et suivi psychologique régulier pour le syndrome anxio-dépressif.

**Surveillance :**
- Évolution favorable sur le plan neurologique, avec régression partielle de l’ataxie et de la dysarthrie sous rééducation.
- Amélioration de la diplopie et du nystagmus, sans normalisation complète à la sortie.
- Équilibre glycémique amélioré sous metformine, avec glycémies capillaires stabilisées entre 1,20 et 1,50 g/L.
- Correction progressive de la carence en vitamine B12 et en folates, avec normalisation des taux sériques à J14.

---

### Conclusion
M. Nicolas Guery a présenté un infarctus cérébral dans le territoire vertébro-basilaire, compliqué de symptômes neurologiques (ataxie, dysarthrie, diplopie et nystagmus). Le bilan étiologique a mis en évidence une sténose vertébrale gauche, une carence en vitamine B12 et en folates, ainsi qu’un diabète de type 2 mal équilibré. L’hospitalisation a permis d’initier une prise en charge pluridisciplinaire associant traitement antiagrégant, contrôle des facteurs de risque vasculaire, supplémentation vitaminique et rééducation neurologique. Le patient est sorti le 18/05/2025 avec un état général stable (ECOG 1), une autonomie conservée et un suivi rapproché en ambulatoire.

**Sortie prévue le 18/05/2025 à domicile, avec :**
- Poursuite des traitements médicamenteux (aspirine, metformine, atorvastatine, périndopril, sertraline, vitamine B12 et acide folique).
- Suivi en consultation de neurologie, diabétologie et psychiatrie.
- Poursuite de la rééducation en kinésithérapie et orthophonie.
- Éducation thérapeutique renforcée pour améliorer l’observance.",

  "formulations": {
    "diagnostics": {
      "Autres infarctus cérébraux (I63.8)": [
        "infarctus cérébral dans le territoire vertébro-basilaire",
        "infarctus cérébral récent",
        "accident vasculaire cérébral ischémique"
      ],
      "Ataxie, sans précision (R27.0)": [
        "ataxie",
        "troubles de la coordination",
        "marche ataxique"
      ],
      "Dysarthrie et anarthrie (R47.1)": [
        "dysarthrie",
        "difficultés d’élocution",
        "élocution troublée"
      ],
      "Diabète sucré de type 2 non insulinotraité ou sans précision, sans complication (E11.98)": [
        "diabète de type 2 non insulinodépendant",
        "diabète de type 2 mal équilibré",
        "diabète sucré de type 2"
      ],
      "Autres avitaminoses précisées du groupe B (E53.8)": [
        "carence en vitamine B12",
        "carence en folates",
        "déficit vitaminique du groupe B"
      ],
      "Trouble anxieux et dépressif mixte (F41.2)": [
        "syndrome anxio-dépressif chronique",
        "état anxio-dépressif",
        "trouble anxio-dépressif modéré"
      ],
      "Diplopie (H53.2)": [
        "diplopie binoculaire",
        "vision double"
      ],
      "Nystagmus et autres anomalies des mouvements oculaires (H55)": [
        "nystagmus horizontal bilatéral",
        "troubles oculomoteurs",
        "mouvements oculaires anormaux"
      ],
      "Antécédents personnels de non-observance d'un traitement médical et d'un régime (Z91.1)": [
        "non-observance thérapeutique",
        "mauvaise observance diététique",
        "difficultés à suivre les prescriptions médicales"
      ]
    },
    "informations": {
      "Date entrée": ["01/05/2025"],
      "Date de sortie": ["18/05/2025"],
      "Service d'hospitalisation": ["Service NEURO-VASCULAIRE"],
      "Nom/Prénom du patient": ["Guery Nicolas"],
      "Nom/Prénom du médecin": ["Odette Offret"],
      "Âge": ["72 ans"],
      "Sexe": ["Masculin"],
      "État général": ["ECOG 1 (symptomatique mais ambulatoire)"],
      "Poids": ["78 kg"],
      "NFS": [
        "Hémoglobine à 13,2 g/dL, VGM à 98 fL (légère macrocytose), plaquettes et leucocytes dans les normes"
      ],
      "Créatinine": ["95 µmol/L (DFG estimé à 65 mL/min/1,73m²)"],
      "Bilan hépatique": ["Normal"],
      "Traitements": [
        "aspirine 160 mg/jour",
        "metformine 1000 mg/jour",
        "atorvastatine 40 mg/jour",
        "périndopril 5 mg/jour",
        "sertraline 50 mg/jour",
        "vitamine B12 (1000 µg/jour IM puis per os)",
        "acide folique 5 mg/jour per os"
      ]
    }
  }
}
```

## Notes pratiques

- Garder `aphp_generation_utils.py` et le notebook dans le même dossier.
- Après modification du script, réexécuter la première cellule : `importlib.reload(utils)` recharge les fonctions.
- `RANDOM_SELECTION=True` applique d’abord les filtres puis effectue un tirage reproductible avec `RANDOM_SEED`.
- `CLEAN_EXISTING_PROMPTS=True` supprime les anciens `.txt` avant de recréer le manifest ; le passer à `False` avant toute édition manuelle.
- Les sorties individuelles portant les mêmes noms sont écrasées lorsque le même run est relancé.
- Les fichiers JSONL bruts des batchs sont conservés sous `_mistral_batches`.
- Le bilan des tokens et coûts est écrit dans `sorties/mistral_token_usage_and_cost.json`.
- La clé Mistral doit provenir de la variable d’environnement `MISTRAL_API_KEY` et ne doit pas être inscrite dans le notebook.

In [17]:
from pathlib import Path
RUN_DIR = "test_xx/"
# adapte RUN_DIR si besoin : c'est le dossier du run existant
scenarios, manifest = utils.load_state(RUN_DIR)
r = manifest.row(0, named=True)

a = (RUN_DIR / r["one_user_path"]).read_text(encoding="utf-8")
b = (RUN_DIR / r["first_user_path"]).read_text(encoding="utf-8")
c = (RUN_DIR / r["second_user_path"]).read_text(encoding="utf-8")

print("one == first  :", a == b)
print("first == second:", b == c)

TypeError: unsupported operand type(s) for /: 'str' and 'str'