# Banc d'essai `bench` — génération AP-HP

Notebook du répertoire `generation/` (spec : `docs/spec_testrun_run_stage.md`),
suite courte d'appels au package `bench` : les fonctions de données sont dans
`bench/scenarios.py`, l'orchestration (gardes, idempotence, messages) dans
`bench/banc.py`. Cycle de vie d'un test : environnement → pool candidat →
montage → seeding/figement → génération → bilan. Toutes les étapes qui
touchent le disque sont **idempotentes** : elles s'exécutent si nécessaire,
sinon elles skippent avec un message d'état — le notebook se ré-exécute
intégralement sur un test déjà préparé. Rien ne se nettoie : pour repartir
de zéro, on crée `runs/NN+1`. Le disque fait foi ; **tout `generation/` est
versionné et partagé** (§9) — « figer » un jeu = commiter son test.

**Mode d'emploi.** Éditer la cellule **PARAMÈTRES COURANTS** (test courant,
parquet source, quotas, graine, `ONLY`), puis exécuter tout. Deux gestes à ne
pas confondre : le **montage** installe le jeu de templates du test dans
`system/one_gen/` depuis le test précédent (l'objet versionné) ; le
**seeding puis figement** crée les dossiers CRH depuis les scénarios, puis
résout le jeu par famille dans chaque dossier (la production du run).

- **Essai rapide d'un nouveau parquet** : `QUOTAS = "couverture"` (un
  scénario par type d'hospitalisation présent) et, au run réel,
  `ONLY = ["0000"]` (un seul appel payant). `preparer_pool` commence par le
  contrôle des prérequis du fichier (`verifier_source`) : colonnes, types,
  encodages, types d'hospitalisation affichés.
- **Itérer après édition du jeu** : changer `SYSTEM_PROMPT_FILE` et
  `OUT_FILE` (paramètres avancés) — les variantes coexistent, rien n'est
  écrasé. Le jeu s'édite dans `runs/<TEST_NUM>/system/one_gen/`.
- **Clé API** : exclusivement `MISTRAL_API_KEY` dans l'environnement du
  noyau, jamais dans le notebook. Tout s'exécute **sans clé** jusqu'aux
  dry-runs inclus ; seules les cellules « run réel » l'exigent.
- Annexes (2-gen, `prompt_local.py`, itération par copie, ajout de DAS) :
  `notebook_annexes.ipynb`.

In [2]:
# --- PARAMÈTRES COURANTS — la seule cellule éditée au quotidien ---
TEST_NUM = "06"    # le test courant (étiquettes tabac/alcool = données, bloc H)
PREV_TEST = "05"   # test précédent de la chaîne (None pour un tout premier test)

# Le parquet de scénarios (chemin depuis la racine du repo, ou absolu) — à
# garder IDENTIQUE d'un test à l'autre de la chaîne (comparabilité).
SOURCE_PROFILES_PATH = "data/aphp/scenarios_C1.parquet"

# Tirage : dict {modalité de QUOTAS_BY: effectif} (un quota à 0 documente une
# strate volontairement exclue ; la somme = la taille du test), OU
# "couverture" (1 scénario par type présent dans le fichier — le smoke d'un
# nouveau parquet), OU None (tirage simple de TARGET_N séjours).
QUOTAS = {
     "Séances simples": 2,
     "HDJ médecine adultes": 2,
     "Médecine adultes > 3 nuits": 2,
     "Chirurgie adultes < 3 nuits": 2,
     "Chirurgie adultes > 3 nuits": 2,
     "Interventionnel adultes < 3 nuits":1,
     "Interventionnel adultes > 3 nuits":1,
     "Accouchement normal mère": 1,
     "Bébé normal": 0,
     "IMG & fausses couches":1,
     "IVG": 0,  # DP en 8 : aucune IVG disponible
     "Greffes de moelle, CAR-T Cells": 0,
     "Brûlés" : 0,
     "Transplantations" : 0,
}
RANDOM_SEED = 42

ONLY = None  # ex. ["0000", "0001"] : run réel partiel (entrée `partial` au journal)


# --- PARAMÈTRES Modifiés
TEST_NUM = "07"
PREV_TEST = "06"
SOURCE_PROFILES_PATH = "data/aphp/scenarios_C1_dp.parquet"
QUOTAS = "couverture"      # un séjour par type : 15 scénarios
ONLY = ["0000"]            # un seul appel payant pour le premier run réel

In [3]:
# --- Bootstrap (ne pas toucher) : racine du repo, import de bench ---
import os
import sys
from pathlib import Path

REPO_ROOT = next((p for p in (Path.cwd().resolve(), *Path.cwd().resolve().parents)
                  if (p / "bench").is_dir() and (p / "core").is_dir()), None)
assert REPO_ROOT, "Racine du repo Stream introuvable — lancer le notebook depuis generation/."
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

import polars as pl
from bench import BenchError, Pricing, generate, load_reports, scenario_dirs
from bench.banc import *
from enrichissement import Politique

# --- PARAMÈTRES AVANCÉS (rarement touchés) ---
MODEL = os.environ.get("MISTRAL_MODEL", "mistral-large-latest")
MAX_TOKENS_SUMMARY = 8_000
MAX_TOKENS_CR = 128_000
# Transport des appels Mistral (spec v3.7) : "sync" = un chat.complete par
# scénario, MAX_WORKERS en parallèle ; "batch" = 50 % moins cher mais reste en
# file indéfiniment depuis septembre 2026 — à réactiver quand Mistral l'aura
# rétabli. Les tarifs (USD / 1M tokens, Mistral Large, https://mistral.ai/pricing)
# suivent le transport.
TRANSPORT = os.environ.get("MISTRAL_TRANSPORT", "sync")
MAX_WORKERS = 3
_TARIFS = {"sync": (0.5, 1.5), "batch": (0.25, 0.75)}
PRICING = Pricing(*_TARIFS[TRANSPORT])

# Sélection et enrichissement — à garder IDENTIQUES d'un test à l'autre de
# la chaîne (comparabilité).
QUOTAS_BY = "DPEC"          # ou "TPEC" — clés de QUOTAS
FILTRE_DP_SUFFIXE = "8"     # séjours dont le DP se termine par « 8 » (sous-
                            # catégories « autres formes précisées ») ; None = pas de filtre
TARGET_N = 15               # tirage simple, quand QUOTAS = None
SCENARIO_FILTERS: list[dict] = [
    # ex. {"column": "template_name", "op": "eq", "value": "surgery_outpatient.txt"},
]
RANDOM_SELECTION = True
ENRICHIR_SCENARIOS = True   # lot E1 : DAS tabac/alcool/corpulence + contexte patient
ENRICHISSEMENT_SEED = RANDOM_SEED
POLITIQUE_ENRICHISSEMENT = Politique()

# Fichiers du run — pour ITÉRER après édition du jeu : changer
# SYSTEM_PROMPT_FILE (ex. prompt_system_one_gen_v2.txt) et OUT_FILE (ex.
# crh_v2.txt) — les variantes coexistent, rien n'est écrasé.
SYSTEM_PROMPT_FILE = "prompt_system_one_gen.txt"
OUT_FILE = "crh_generation.txt"
PARAMS_GEN = dict(
    system=SYSTEM_PROMPT_FILE, user="user_generation.txt", out=OUT_FILE,
    model=MODEL, max_tokens=MAX_TOKENS_CR, pricing=PRICING, prefix_file="prefix.txt",
)

# Vérificateur (optionnel) : textes d'exemple, à adapter à la campagne.
VERIF_SYSTEM = """Tu es un médecin DIM. On te fournit un compte rendu
hospitalier généré automatiquement. Vérifie sa cohérence clinique et sa
conformité aux règles de codage, puis rends un verdict structuré :
CONFORME ou NON CONFORME, suivi de la liste des anomalies constatées."""
VERIF_USER = "Vérifie le compte rendu suivant et rends ton verdict."
VERIF_HEADER = "### COMPTE RENDU À VÉRIFIER"
VERIF_FOOTER = "### FIN DU COMPTE RENDU"
PARAMS_VERIF = dict(
    system="prompt_system_verif.txt", user="user_verification.txt", out="verdict.txt",
    model=MODEL, max_tokens=MAX_TOKENS_SUMMARY, pricing=PRICING,
    context_header=VERIF_HEADER, context_footer=VERIF_FOOTER,
)

pool = None  # rempli par preparer_pool (section 2)
print("Modèle :", MODEL)
print("Transport :", TRANSPORT, "— tarifs ($ / 1M tokens) :", PRICING)
print("MISTRAL_API_KEY présente :", "MISTRAL_API_KEY" in os.environ)

Modèle : mistral-large-latest
Transport : sync — tarifs ($ / 1M tokens) : Pricing(batch_input_usd_per_million=0.5, batch_output_usd_per_million=1.5)
MISTRAL_API_KEY présente : True

## 1. Environnement et pool candidat

`verifier_environnement()` : fictomed est l'éditable attendu (clone
`~/Documents/fictomed`, branche `prompt-work` — `uv sync` / `uv run`
réinstallent le paquet PyPI, wheel sans `regles_atih.yml` quelle que soit
sa version : refaire `uv pip install -e` puis
redémarrer le noyau), les bibliothèques de fiches respectent le contrat
recode-icd (`bench.fiches`, l'index fait foi) et le lecteur fictomed les lit.

`preparer_pool(...)` : contrôle des prérequis du parquet (`verifier_source`,
schéma `SCHEMA_SOURCE`), typologie TPEC/DPEC (conservée si le fichier la
fournit, sinon calculée), identifiants de traçabilité, filtre DP, tirage
(`QUOTAS`), enrichissement, contrôle du contrat côté pool (codes sans fiche
journalisés, codes ajoutés émissibles), couverture par type. Le pool sort
**prêt pour fictomed** — aucun appel Mistral ici.

In [4]:
verifier_environnement()

Racine repo  : /Users/remi/GitHub/Stream
bench        : /Users/remi/GitHub/Stream/bench
fictomed     : /Users/remi/Documents/fictomed/fictomed/__init__.py
Registre fictomed : 15111 fiches exactes, 2054 catégories (index : 15282 / 2097) — le lecteur lit la librairie.

(shape: (15_282, 15)
 ┌─────────┬─────────┬────────────┬────────────┬───┬────────────┬────────────┬──────────┬───────────┐
 │ code    ┆ chapter ┆ fichier    ┆ libelle    ┆ … ┆ source_exi ┆ classe_gen ┆ nb_chars ┆ format_ve │
 │ ---     ┆ ---     ┆ ---        ┆ ---        ┆   ┆ stence     ┆ eration    ┆ ---      ┆ rsion     │
 │ str     ┆ str     ┆ str        ┆ str        ┆   ┆ ---        ┆ ---        ┆ str      ┆ ---       │
 │         ┆         ┆            ┆            ┆   ┆ str        ┆ str        ┆          ┆ str       │
 ╞═════════╪═════════╪════════════╪════════════╪═══╪════════════╪════════════╪══════════╪═══════════╡
 │ A00.0   ┆ I       ┆ I/A00.0.md ┆ À Vibrio   ┆ … ┆ OWL_ANS    ┆ emissible  ┆ 1299     ┆ 1         │
 │         ┆         ┆            ┆ cholerae   ┆   ┆            ┆            ┆          ┆           │
 │         ┆         ┆            ┆ 01, biovar ┆   ┆            ┆            ┆          ┆           │
 │         ┆         ┆            ┆ c…         ┆   ┆            ┆            ┆          ┆           │
 │ A00.1   ┆ I       ┆ I/A00.1.md ┆ À Vibrio   ┆ … ┆ OWL_ANS    ┆ emissible  ┆ 1291     ┆ 1         │
 │         ┆         ┆            ┆ cholerae   ┆   ┆            ┆            ┆          ┆           │
 │         ┆         ┆            ┆ 01, biovar ┆   ┆            ┆            ┆          ┆           │
 │         ┆         ┆            ┆ E…         ┆   ┆            ┆            ┆          ┆           │
 │ A00.9   ┆ I       ┆ I/A00.9.md ┆ Choléra,   ┆ … ┆ OWL_ANS    ┆ emissible  ┆ 1281     ┆ 1         │
 │         ┆         ┆            ┆ sans       ┆   ┆            ┆            ┆          ┆           │
 │         ┆         ┆            ┆ précision  ┆   ┆            ┆            ┆          ┆           │
 │ A01.0   ┆ I       ┆ I/A01.0.md ┆ Fièvre     ┆ … ┆ OWL_ANS    ┆ emissible  ┆ 1886     ┆ 1         │
 │         ┆         ┆            ┆ typhoïde   ┆   ┆            ┆            ┆          ┆           │
 │ A01.1   ┆ I       ┆ I/A01.1.md ┆ Paratyphoï ┆ … ┆ OWL_ANS    ┆ emissible  ┆ 1232     ┆ 1         │
 │         ┆         ┆            ┆ de A       ┆   ┆            ┆            ┆          ┆           │
 │ …       ┆ …       ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …        ┆ …         │
 │ Z99.2+8 ┆ XXI     ┆ XXI/Z99.2+ ┆ Dépendance ┆ … ┆ OWL_ANS    ┆ emissible  ┆ 2398     ┆ 1         │
 │         ┆         ┆ 8.md       ┆ envers une ┆   ┆            ┆            ┆          ┆           │
 │         ┆         ┆            ┆ dialyse …  ┆   ┆            ┆            ┆          ┆           │
 │ Z99.3   ┆ XXI     ┆ XXI/Z99.3. ┆ Dépendance ┆ … ┆ OWL_ANS    ┆ emissible  ┆ 2226     ┆ 1         │
 │         ┆         ┆ md         ┆ envers un  ┆   ┆            ┆            ┆          ┆           │
 │         ┆         ┆            ┆ fauteuil … ┆   ┆            ┆            ┆          ┆           │
 │ Z99.4   ┆ XXI     ┆ XXI/Z99.4. ┆ Dépendance ┆ … ┆ OWL_ANS    ┆ emissible  ┆ 2115     ┆ 1         │
 │         ┆         ┆ md         ┆ envers un  ┆   ┆            ┆            ┆          ┆           │
 │         ┆         ┆            ┆ cœur arti… ┆   ┆            ┆            ┆          ┆           │
 │ Z99.8   ┆ XXI     ┆ XXI/Z99.8. ┆ Dépendance ┆ … ┆ OWL_ANS    ┆ emissible  ┆ 2417     ┆ 1         │
 │         ┆         ┆ md         ┆ envers     ┆   ┆            ┆            ┆          ┆           │
 │         ┆         ┆            ┆ d'autres   ┆   ┆            ┆            ┆          ┆           │
 │         ┆         ┆            ┆ mac…       ┆   ┆            ┆            ┆          ┆           │
 │ Z99.9   ┆ XXI     ┆ XXI/Z99.9. ┆ Dépendance ┆ … ┆ OWL_ANS    ┆ emissible  ┆ 2222     ┆ 1         │
 │         ┆         ┆ md         ┆ envers une ┆   ┆            ┆            ┆          ┆           │
 │         ┆         ┆            ┆ machine …  ┆   ┆            ┆            ┆          ┆           │
 └─────────┴─────────┴────────────┴────────────┴───┴────────────┴────────────┴──────────┴───────────┘,
 shape: (2_097, 12)
 ┌─────────┬─────────┬─────────────┬────────────┬───┬──────────┬────────────┬──────────┬────────────┐
 │ code    ┆ chapter ┆ fichier     ┆ libelle    ┆ … ┆ type_mco ┆ statut_mco ┆ nb_chars ┆ format_ver │
 │ ---     ┆ ---     ┆ ---         ┆ ---        ┆   ┆ ---      ┆ ---        ┆ ---      ┆ sion       │
 │ str     ┆ str     ┆ str         ┆ str        ┆   ┆ str      ┆ str        ┆ str      ┆ ---        │
 │         ┆         ┆             ┆            ┆   ┆          ┆            ┆          ┆ str        │
 ╞═════════╪═════════╪═════════════╪════════════╪═══╪══════════╪════════════╪══════════╪════════════╡
 │ A00     ┆ I       ┆ I/A00.md    ┆ Choléra    ┆ … ┆ 3        ┆ pere_inter ┆ 1502     ┆ 1          │
 │         ┆         ┆             ┆            ┆   ┆          ┆ dit        ┆          ┆            │
 │ A01     ┆ I       ┆ I/A01.md    ┆ Fièvres    ┆ … ┆ 3        ┆ pere_inter ┆ 2477     ┆ 1          │
 │         ┆         ┆             ┆ typhoïde   ┆   ┆          ┆ dit        ┆          ┆            │
 │         ┆         ┆             ┆ et paratyp ┆   ┆          ┆            ┆          ┆            │
 │         ┆         ┆             ┆ hoï…       ┆   ┆          ┆            ┆          ┆            │
 │ A02     ┆ I       ┆ I/A02.md    ┆ Autres sal ┆ … ┆ 3        ┆ pere_inter ┆ 2857     ┆ 1          │
 │         ┆         ┆             ┆ monelloses ┆   ┆          ┆ dit        ┆          ┆            │
 │ A03     ┆ I       ┆ I/A03.md    ┆ Shigellose ┆ … ┆ 3        ┆ pere_inter ┆ 2260     ┆ 1          │
 │         ┆         ┆             ┆            ┆   ┆          ┆ dit        ┆          ┆            │
 │ A04     ┆ I       ┆ I/A04.md    ┆ Autres     ┆ … ┆ 3        ┆ pere_inter ┆ 3149     ┆ 1          │
 │         ┆         ┆             ┆ infections ┆   ┆          ┆ dit        ┆          ┆            │
 │         ┆         ┆             ┆ intestinal ┆   ┆          ┆            ┆          ┆            │
 │         ┆         ┆             ┆ es…        ┆   ┆          ┆            ┆          ┆            │
 │ …       ┆ …       ┆ …           ┆ …          ┆ … ┆ …        ┆ …          ┆ …        ┆ …          │
 │ Y40-Y59 ┆ XX      ┆ XX/Y40-Y59. ┆ Médicament ┆ … ┆ null     ┆ inconnu_at ┆ 537      ┆ 1          │
 │         ┆         ┆ md          ┆ s et       ┆   ┆          ┆ ih         ┆          ┆            │
 │         ┆         ┆             ┆ substances ┆   ┆          ┆            ┆          ┆            │
 │         ┆         ┆             ┆ biol…      ┆   ┆          ┆            ┆          ┆            │
 │ Y85-Y89 ┆ XX      ┆ XX/Y85-Y89. ┆ Séquelles  ┆ … ┆ null     ┆ inconnu_at ┆ 765      ┆ 1          │
 │         ┆         ┆ md          ┆ de causes  ┆   ┆          ┆ ih         ┆          ┆            │
 │         ┆         ┆             ┆ externes   ┆   ┆          ┆            ┆          ┆            │
 │         ┆         ┆             ┆ d…         ┆   ┆          ┆            ┆          ┆            │
 │ Y90-Y98 ┆ XX      ┆ XX/Y90-Y98. ┆ Facteurs   ┆ … ┆ null     ┆ inconnu_at ┆ 506      ┆ 1          │
 │         ┆         ┆ md          ┆ supplément ┆   ┆          ┆ ih         ┆          ┆            │
 │         ┆         ┆             ┆ aires se   ┆   ┆          ┆            ┆          ┆            │
 │         ┆         ┆             ┆ ra…        ┆   ┆          ┆            ┆          ┆            │
 │ Z00-Z13 ┆ XXI     ┆ XXI/Z00-Z13 ┆ Sujets en  ┆ … ┆ null     ┆ inconnu_at ┆ 401      ┆ 1          │
 │         ┆         ┆ .md         ┆ contact    ┆   ┆          ┆ ih         ┆          ┆            │
 │         ┆         ┆             ┆ avec les   ┆   ┆          ┆            ┆          ┆            │
 │         ┆         ┆             ┆ ser…       ┆   ┆          ┆            ┆          ┆            │
 │ Z40-Z54 ┆ XXI     ┆ XXI/Z40-Z54 ┆ Sujets     ┆ … ┆ null     ┆ inconnu_at ┆ 749      ┆ 1          │
 │         ┆         ┆ .md         ┆ ayant      ┆   ┆          ┆ ih         ┆          ┆            │
 │         ┆         ┆             ┆ recours    ┆   ┆          ┆            ┆          ┆            │
 │         ┆         ┆             ┆ aux servi… ┆   ┆          ┆            ┆          ┆            │
 └─────────┴─────────┴─────────────┴────────────┴───┴──────────┴────────────┴──────────┴────────────┘)

In [5]:
pool = preparer_pool(
    SOURCE_PROFILES_PATH, QUOTAS, RANDOM_SEED,
    by=QUOTAS_BY, enrichir=ENRICHIR_SCENARIOS,
    enrichissement_seed=ENRICHISSEMENT_SEED, politique=POLITIQUE_ENRICHISSEMENT,
    filtre_dp_suffixe=FILTRE_DP_SUFFIXE, target_n=TARGET_N,
)

Source : /Users/remi/GitHub/Stream/data/aphp/scenarios_C1_dp.parquet
Shape  : (1087525, 38) — colonnes : ['branche', 'population', 'campagne', 'sexe', 'age', 'cage', 'mode_hospit', 'ghm2', 'racine', 'duree', 'nbda', 'type_unite', 'prep_sc', 'diag2', 'graine', 'diagnostic_associes', 'nb_das', 'diabete', 'diabete_scenario', 'hta', 'hta_scenario', 'mode_entree', 'mode_sortie', 'mdp', 'lettre', 'DPEC', 'TPEC', 'id_profil', 'id_scenario', 'hash_das', 'variante', 'poids', 'source_ref', 'nb_cible', 'nb_variantes_demandees', 'dp_origine', 'dp_substitue', 'repli_substitution']
fichier scenarios_C1_dp.parquet — 1087525 lignes, types d'hospitalisation (fournis) : {'Accouchement normal mère': 1744, 'Accouchement pathologique mère': 17523, 'Autre néonat': 287, 'Brûlés': 1557, 'Bébé normal': 627, 'Bébé néonat chir': 1186, 'Bébé néonat med': 26687, 'Chirurgie adultes < 3 nuits': 82527, 'Chirurgie adultes > 3 nuits': 104473, 'Greffes de moelle, CAR-T Cells': 75, 'HDJ médecine adultes': 71769, 'IMG & fausses couches': 8609, 'IVG': 174, 'Interventionnel adultes < 3 nuits': 57594, 'Interventionnel adultes > 3 nuits': 11000, 'Médecine adultes < 3 nuits': 136953, 'Médecine adultes > 3 nuits': 544190, 'Séances simples': 20489, 'Transplantations': 61}, colonnes OK
  - signalé : agean absente : DÉRIVÉE de cage par deriver_agean (tirage entier uniforme dans la classe, déterministe par id_scenario) — variable dérivée, pas une donnée observée
  - signalé : racine : 372108 valeur(s) nulle(s) — réparées depuis ghm2[:5] (reparer_racine ; compteur au récap, attendu 0 après correction amont)
  - signalé : duree : 97034 valeur(s) nulle(s) tolérée(s)
  - signalé : colonnes supplémentaires hors schéma (ignorées) : ['population', 'campagne', 'prep_sc', 'graine', 'nb_das', 'diabete', 'diabete_scenario', 'hta', 'hta_scenario', 'lettre', 'id_profil', 'hash_das', 'variante', 'poids', 'source_ref', 'nb_cible', 'nb_variantes_demandees']
agean : dérivé de cage, pivot age — 1087525/1087525 lignes (tirage entier uniforme dans la classe, déterministe par id_scenario ; variable DÉRIVÉE, pas une donnée observée).
  - pivot age hors ge_18 / lt_18 sur 372108 ligne(s) (ex. âge numérique en chaîne) : sans effet sur le tirage.
racine : 372108/1087525 réparée(s) depuis ghm2[:5] — après la correction amont, ce compteur doit valoir 0.
Typologie TPEC/DPEC fournie par le fichier — conservée telle quelle.

shape: (19, 3)
┌──────────────────────────────┬─────────────────────────────────┬────────┐
│ TPEC                         ┆ DPEC                            ┆ len    │
│ ---                          ┆ ---                             ┆ ---    │
│ str                          ┆ str                             ┆ u32    │
╞══════════════════════════════╪═════════════════════════════════╪════════╡
│ Chirurgie et interventionnel ┆ Chirurgie adultes < 3 nuits     ┆ 82527  │
│ Chirurgie et interventionnel ┆ Chirurgie adultes > 3 nuits     ┆ 104473 │
│ Chirurgie et interventionnel ┆ Interventionnel adultes < 3 nu… ┆ 57594  │
│ Chirurgie et interventionnel ┆ Interventionnel adultes > 3 nu… ┆ 11000  │
│ Médecine                     ┆ HDJ médecine adultes            ┆ 71769  │
│ …                            ┆ …                               ┆ …      │
│ Obstétrique                  ┆ IMG & fausses couches           ┆ 8609   │
│ Obstétrique                  ┆ IVG                             ┆ 174    │
│ Séjours complexes            ┆ Brûlés                          ┆ 1557   │
│ Séjours complexes            ┆ Greffes de moelle, CAR-T Cells  ┆ 75     │
│ Séjours complexes            ┆ Transplantations                ┆ 61     │
└──────────────────────────────┴─────────────────────────────────┴────────┘

Filtre DP terminant par 8 : 1087525 -> 137332 séjours

shape: (16, 3)
┌──────────────────────────────┬─────────────────────────────────┬──────┐
│ TPEC                         ┆ DPEC                            ┆ len  │
│ ---                          ┆ ---                             ┆ ---  │
│ str                          ┆ str                             ┆ u32  │
╞══════════════════════════════╪═════════════════════════════════╪══════╡
│ Chirurgie et interventionnel ┆ Chirurgie adultes < 3 nuits     ┆ 7621 │
│ Chirurgie et interventionnel ┆ Chirurgie adultes > 3 nuits     ┆ 2238 │
│ Chirurgie et interventionnel ┆ Interventionnel adultes < 3 nu… ┆ 7768 │
│ Chirurgie et interventionnel ┆ Interventionnel adultes > 3 nu… ┆ 564  │
│ Médecine                     ┆ HDJ médecine adultes            ┆ 8644 │
│ …                            ┆ …                               ┆ …    │
│ Néonatalogie                 ┆ Bébé néonat med                 ┆ 4147 │
│ Obstétrique                  ┆ Accouchement normal mère        ┆ 131  │
│ Obstétrique                  ┆ Accouchement pathologique mère  ┆ 1418 │
│ Obstétrique                  ┆ IMG & fausses couches           ┆ 622  │
│ Séjours complexes            ┆ Brûlés                          ┆ 8    │
└──────────────────────────────┴─────────────────────────────────┴──────┘

Séjours incomplets pour fictomed (agean / duree / mode_entree / mode_sortie nuls) : 13588 écarté(s) — 137332 -> 123744 séjours
Couverture : 1 séjour par modalité de DPEC présente (15 modalité(s)).
Tirage stratifié par DPEC : 15 séjours (15 strate(s), seed=42).

shape: (15, 3)
┌──────────────────────────────┬─────────────────────────────────┬─────┐
│ TPEC                         ┆ DPEC                            ┆ len │
│ ---                          ┆ ---                             ┆ --- │
│ str                          ┆ str                             ┆ u32 │
╞══════════════════════════════╪═════════════════════════════════╪═════╡
│ Chirurgie et interventionnel ┆ Chirurgie adultes < 3 nuits     ┆ 1   │
│ Chirurgie et interventionnel ┆ Chirurgie adultes > 3 nuits     ┆ 1   │
│ Chirurgie et interventionnel ┆ Interventionnel adultes < 3 nu… ┆ 1   │
│ Chirurgie et interventionnel ┆ Interventionnel adultes > 3 nu… ┆ 1   │
│ Médecine                     ┆ HDJ médecine adultes            ┆ 1   │
│ …                            ┆ …                               ┆ …   │
│ Néonatalogie                 ┆ Bébé néonat med                 ┆ 1   │
│ Obstétrique                  ┆ Accouchement normal mère        ┆ 1   │
│ Obstétrique                  ┆ Accouchement pathologique mère  ┆ 1   │
│ Obstétrique                  ┆ IMG & fausses couches           ┆ 1   │
│ Séjours complexes            ┆ Brûlés                          ┆ 1   │
└──────────────────────────────┴─────────────────────────────────┴─────┘

spécialité : observee 2, unique 11, tiree 0, repli 2 (sur 15) — mapping type_unite : 5 entrée(s) valide(s) appliquée(s) ; graine composite ['id_scenario', 'duree', 'mode_entree', 'mode_sortie', 'mdp'].
  - repli (pas de ligne Service, le modèle propose) : 2 ligne(s) — racines sans entrée : {'22M02': 1, '28Z17': 1}

shape: (15, 5)
┌────────────────────┬────────────────────────────┬──────────────────────┬───────────────────┬─────┐
│ TPEC               ┆ DPEC                       ┆ specialty            ┆ specialite_source ┆ len │
│ ---                ┆ ---                        ┆ ---                  ┆ ---               ┆ --- │
│ str                ┆ str                        ┆ str                  ┆ str               ┆ u32 │
╞════════════════════╪════════════════════════════╪══════════════════════╪═══════════════════╪═════╡
│ Chirurgie et       ┆ Chirurgie adultes < 3      ┆ GYNECOLOGIE          ┆ unique            ┆ 1   │
│ interventionnel    ┆ nuits                      ┆                      ┆                   ┆     │
│ Chirurgie et       ┆ Chirurgie adultes > 3      ┆ CHIR.PLAST.RECONSTR. ┆ unique            ┆ 1   │
│ interventionnel    ┆ nuits                      ┆                      ┆                   ┆     │
│ Chirurgie et       ┆ Interventionnel adultes <  ┆ HEPATO-GASTRO-ENTERO ┆ unique            ┆ 1   │
│ interventionnel    ┆ 3 nu…                      ┆                      ┆                   ┆     │
│ Chirurgie et       ┆ Interventionnel adultes >  ┆ CARDIOLOGIE          ┆ unique            ┆ 1   │
│ interventionnel    ┆ 3 nu…                      ┆                      ┆                   ┆     │
│ Médecine           ┆ HDJ médecine adultes       ┆ MEDECINE INTERNE     ┆ unique            ┆ 1   │
│ …                  ┆ …                          ┆ …                    ┆ …                 ┆ …   │
│ Néonatalogie       ┆ Bébé néonat med            ┆ NEONATOLOGIE         ┆ observee          ┆ 1   │
│ Obstétrique        ┆ Accouchement normal mère   ┆ OBSTETRIQUE          ┆ unique            ┆ 1   │
│ Obstétrique        ┆ Accouchement pathologique  ┆ OBSTETRIQUE          ┆ unique            ┆ 1   │
│                    ┆ mère                       ┆                      ┆                   ┆     │
│ Obstétrique        ┆ IMG & fausses couches      ┆ GYNECOLOGIE          ┆ unique            ┆ 1   │
│ Séjours complexes  ┆ Brûlés                     ┆ null                 ┆ repli             ┆ 1   │
└────────────────────┴────────────────────────────┴──────────────────────┴───────────────────┴─────┘

Enrichissement : 9/15 ligne(s) enrichie(s), 6 exclue(s), 6 code(s) DAS ajouté(s).
Exclusions : préfixe O ×3, âge < 18 (ou manquant) ×3
Codes ajoutés : E6603×3, F101×1, E6604×1, F1725×1

shape: (9, 9)
┌───────────────┬───────┬──────┬───────────┬───┬──────┬──────────────┬──────────────┬──────────────┐
│ DPEC          ┆ agean ┆ sexe ┆ taille_cm ┆ … ┆ imc  ┆ tabac        ┆ alcool       ┆ codes_ajoute │
│ ---           ┆ ---   ┆ ---  ┆ ---       ┆   ┆ ---  ┆ ---          ┆ ---          ┆ s            │
│ str           ┆ i32   ┆ str  ┆ i64       ┆   ┆ f64  ┆ str          ┆ str          ┆ ---          │
│               ┆       ┆      ┆           ┆   ┆      ┆              ┆              ┆ str          │
╞═══════════════╪═══════╪══════╪═══════════╪═══╪══════╪══════════════╪══════════════╪══════════════╡
│ Brûlés        ┆ 26    ┆ 1    ┆ 189       ┆ … ┆ 22.1 ┆ non          ┆ environ 5    ┆ F101         │
│               ┆       ┆      ┆           ┆   ┆      ┆              ┆ verres/jour  ┆              │
│ Chirurgie     ┆ 46    ┆ 2    ┆ 171       ┆ … ┆ 24.3 ┆ non          ┆ non          ┆              │
│ adultes < 3   ┆       ┆      ┆           ┆   ┆      ┆              ┆              ┆              │
│ nuits         ┆       ┆      ┆           ┆   ┆      ┆              ┆              ┆              │
│ Chirurgie     ┆ 68    ┆ 2    ┆ 159       ┆ … ┆ 23.3 ┆ non          ┆ non          ┆              │
│ adultes > 3   ┆       ┆      ┆           ┆   ┆      ┆              ┆              ┆              │
│ nuits         ┆       ┆      ┆           ┆   ┆      ┆              ┆              ┆              │
│ HDJ médecine  ┆ 63    ┆ 2    ┆ 159       ┆ … ┆ 34.4 ┆ non          ┆ non          ┆ E6604        │
│ adultes       ┆       ┆      ┆           ┆   ┆      ┆              ┆              ┆              │
│ Interventionn ┆ 58    ┆ 2    ┆ 164       ┆ … ┆ 25.3 ┆ non          ┆ non          ┆ E6603        │
│ el adultes <  ┆       ┆      ┆           ┆   ┆      ┆              ┆              ┆              │
│ 3 nu…         ┆       ┆      ┆           ┆   ┆      ┆              ┆              ┆              │
│ Interventionn ┆ 84    ┆ 2    ┆ 155       ┆ … ┆ 21.6 ┆ actif, 12    ┆ non          ┆ F1725        │
│ el adultes >  ┆       ┆      ┆           ┆   ┆      ┆ cigarettes/j ┆              ┆              │
│ 3 nu…         ┆       ┆      ┆           ┆   ┆      ┆ our, 36 …    ┆              ┆              │
│ Médecine      ┆ 68    ┆ 2    ┆ 164       ┆ … ┆ 25.7 ┆ non          ┆ non          ┆ E6603        │
│ adultes < 3   ┆       ┆      ┆           ┆   ┆      ┆              ┆              ┆              │
│ nuits         ┆       ┆      ┆           ┆   ┆      ┆              ┆              ┆              │
│ Médecine      ┆ 82    ┆ 2    ┆ 154       ┆ … ┆ 30.4 ┆ non          ┆ non          ┆              │
│ adultes > 3   ┆       ┆      ┆           ┆   ┆      ┆              ┆              ┆              │
│ nuits         ┆       ┆      ┆           ┆   ┆      ┆              ┆              ┆              │
│ Séances       ┆ 63    ┆ 2    ┆ 166       ┆ … ┆ 26.1 ┆ non          ┆ non          ┆ E6603        │
│ simples       ┆       ┆      ┆           ┆   ┆      ┆              ┆              ┆              │
└───────────────┴───────┴──────┴───────────┴───┴──────┴──────────────┴──────────────┴──────────────┘

Pool : 75 codes distincts, 1 sans fiche à l'index — JOURNAL : ['X3100']
Enrichissement : 4 code(s) ajouté(s) distincts, tous émissibles.
Pool candidat : 15 séjours — agean dérivé de cage, pivot age — racine réparée sur 372108 ligne(s) — 13588 séjour(s) incomplet(s) écarté(s) avant tirage — couverture par type :

shape: (15, 3)
┌──────────────────────────────┬─────────────────────────────────┬─────┐
│ TPEC                         ┆ DPEC                            ┆ len │
│ ---                          ┆ ---                             ┆ --- │
│ str                          ┆ str                             ┆ u32 │
╞══════════════════════════════╪═════════════════════════════════╪═════╡
│ Chirurgie et interventionnel ┆ Chirurgie adultes < 3 nuits     ┆ 1   │
│ Chirurgie et interventionnel ┆ Chirurgie adultes > 3 nuits     ┆ 1   │
│ Chirurgie et interventionnel ┆ Interventionnel adultes < 3 nu… ┆ 1   │
│ Chirurgie et interventionnel ┆ Interventionnel adultes > 3 nu… ┆ 1   │
│ Médecine                     ┆ HDJ médecine adultes            ┆ 1   │
│ …                            ┆ …                               ┆ …   │
│ Néonatalogie                 ┆ Bébé néonat med                 ┆ 1   │
│ Obstétrique                  ┆ Accouchement normal mère        ┆ 1   │
│ Obstétrique                  ┆ Accouchement pathologique mère  ┆ 1   │
│ Obstétrique                  ┆ IMG & fausses couches           ┆ 1   │
│ Séjours complexes            ┆ Brûlés                          ┆ 1   │
└──────────────────────────────┴─────────────────────────────────┴─────┘

## 2. Test courant — montage, seeding puis figement

**Le jeu du test s'édite LÀ : `runs/<TEST_NUM>/system/one_gen/` — un `.txt`
par famille clinique.** Il est monté par copie du jeu du test précédent (la
chaîne des tests est la chaîne des versions) ; pour un tout premier test,
fournir un jeu initial à la main (les jeux historiques sont dans git :
`generation/runs/01`). Un `prefix.txt` dans le jeu remplace le prefix
fictomed au seeding ; quand `ENRICHIR_SCENARIOS` est actif, le contexte
patient (taille, poids, IMC, tabac, alcool) est fourni dans le user prompt et
le prompt système doit le restituer (bloc H du jeu de `runs/05`).

`seeder` : génération fictomed (un scénario par ligne du pool ; skip si le
test est déjà seedé), graine (dossiers CRH, `test.json` annoté), puis
figement du jeu par famille en `SYSTEM_PROMPT_FILE` (skip si déjà figé).

In [6]:
TD, PREV_TD = dossiers_test(TEST_NUM, PREV_TEST)
etat_test(TD, PREV_TD)
monter_jeu(TD, PREV_TD)

Test courant : /Users/remi/GitHub/Stream/generation/runs/07 (existe)
Jeu amont    : /Users/remi/GitHub/Stream/generation/runs/06/system/one_gen
Test               : /Users/remi/GitHub/Stream/generation/runs/07 — présent
Jeu system/one_gen : présent
Dossiers scénario  : 15 ['0000', '0001', '0002', '0003', '0004'] …
Figement (1er dossier, prompt_system_one_gen.txt) : présent
SKIP — jeu déjà monté : /Users/remi/GitHub/Stream/generation/runs/07/system/one_gen

In [7]:
selected_scenarios = seeder(
    TD, pool, source_path=SOURCE_PROFILES_PATH,
    enrichir=ENRICHIR_SCENARIOS, enrichissement_seed=ENRICHISSEMENT_SEED,
    politique=POLITIQUE_ENRICHISSEMENT, seed=RANDOM_SEED,
    scenario_filters=SCENARIO_FILTERS, random_selection=RANDOM_SELECTION,
    system_prompt_file=SYSTEM_PROMPT_FILE,
)

SKIP — test déjà seedé : 15 dossiers scénario.

shape: (15, 18)
┌─────────────┬─────────────┬────────────┬────────────┬───┬──────┬───────┬────────────┬────────────┐
│ TPEC        ┆ DPEC        ┆ generation ┆ template_n ┆ … ┆ imc  ┆ tabac ┆ alcool     ┆ codes_ajou │
│ ---         ┆ ---         ┆ _id        ┆ ame        ┆   ┆ ---  ┆ ---   ┆ ---        ┆ tes        │
│ str         ┆ str         ┆ ---        ┆ ---        ┆   ┆ f64  ┆ str   ┆ str        ┆ ---        │
│             ┆             ┆ str        ┆ str        ┆   ┆      ┆       ┆            ┆ str        │
╞═════════════╪═════════════╪════════════╪════════════╪═══╪══════╪═══════╪════════════╪════════════╡
│ Médecine    ┆ Séances     ┆ a46e798b-7 ┆ medical_ou ┆ … ┆ 26.1 ┆ non   ┆ non        ┆ E6603      │
│             ┆ simples     ┆ 795-4de7-9 ┆ tpatient.t ┆   ┆      ┆       ┆            ┆            │
│             ┆             ┆ 1ce-427dfb ┆ xt         ┆   ┆      ┆       ┆            ┆            │
│             ┆             ┆ …          ┆            ┆   ┆      ┆       ┆            ┆            │
│ Chirurgie   ┆ Chirurgie   ┆ eae727d3-f ┆ surgery_ou ┆ … ┆ 24.3 ┆ non   ┆ non        ┆            │
│ et interven ┆ adultes < 3 ┆ ef3-4917-b ┆ tpatient.t ┆   ┆      ┆       ┆            ┆            │
│ tionnel     ┆ nuits       ┆ 358-8779dc ┆ xt         ┆   ┆      ┆       ┆            ┆            │
│             ┆             ┆ …          ┆            ┆   ┆      ┆       ┆            ┆            │
│ Néonatalogi ┆ Autre       ┆ 05b83d30-6 ┆ medical_in ┆ … ┆ null ┆ null  ┆ null       ┆ null       │
│ e           ┆ néonat      ┆ 4a4-4d5b-b ┆ patient.tx ┆   ┆      ┆       ┆            ┆            │
│             ┆             ┆ f19-38f2e3 ┆ t          ┆   ┆      ┆       ┆            ┆            │
│             ┆             ┆ …          ┆            ┆   ┆      ┆       ┆            ┆            │
│ Obstétrique ┆ Accouchemen ┆ 59136c52-b ┆ delivery_i ┆ … ┆ null ┆ null  ┆ null       ┆ null       │
│             ┆ t pathologi ┆ 64b-46e9-9 ┆ npatient_u ┆   ┆      ┆       ┆            ┆            │
│             ┆ que mère    ┆ 466-4bc406 ┆ rg.txt     ┆   ┆      ┆       ┆            ┆            │
│             ┆             ┆ …          ┆            ┆   ┆      ┆       ┆            ┆            │
│ Néonatalogi ┆ Bébé normal ┆ 29c3e854-d ┆ medical_in ┆ … ┆ null ┆ null  ┆ null       ┆ null       │
│ e           ┆             ┆ e9f-4930-8 ┆ patient.tx ┆   ┆      ┆       ┆            ┆            │
│             ┆             ┆ 9a2-c8333c ┆ t          ┆   ┆      ┆       ┆            ┆            │
│             ┆             ┆ …          ┆            ┆   ┆      ┆       ┆            ┆            │
│ …           ┆ …           ┆ …          ┆ …          ┆ … ┆ …    ┆ …     ┆ …          ┆ …          │
│ Séjours     ┆ Brûlés      ┆ 424c1b40-9 ┆ medical_in ┆ … ┆ 22.1 ┆ non   ┆ environ 5  ┆ F101       │
│ complexes   ┆             ┆ 0bc-46b6-a ┆ patient.tx ┆   ┆      ┆       ┆ verres/jou ┆            │
│             ┆             ┆ 065-4e250f ┆ t          ┆   ┆      ┆       ┆ r          ┆            │
│             ┆             ┆ …          ┆            ┆   ┆      ┆       ┆            ┆            │
│ Médecine    ┆ HDJ         ┆ 7d2fbe77-3 ┆ medical_ou ┆ … ┆ 34.4 ┆ non   ┆ non        ┆ E6604      │
│             ┆ médecine    ┆ 550-483e-b ┆ tpatient.t ┆   ┆      ┆       ┆            ┆            │
│             ┆ adultes     ┆ 4ca-91838d ┆ xt         ┆   ┆      ┆       ┆            ┆            │
│             ┆             ┆ …          ┆            ┆   ┆      ┆       ┆            ┆            │
│ Chirurgie   ┆ Chirurgie   ┆ f223ec6e-1 ┆ surgery_in ┆ … ┆ 23.3 ┆ non   ┆ non        ┆            │
│ et interven ┆ adultes > 3 ┆ bb6-46a7-8 ┆ patient.tx ┆   ┆      ┆       ┆            ┆            │
│ tionnel     ┆ nuits       ┆ 8bb-9aea4c ┆ t          ┆   ┆      ┆       ┆            ┆            │
│             ┆             ┆ …          ┆            ┆   ┆      ┆       ┆            ┆            │
│ Néonatalogi ┆ Bébé néonat ┆ 2223451a-e ┆ medical_in ┆ … ┆ null ┆ null  ┆ null       ┆ null       │
│ e           ┆ med         ┆ a80-4984-b ┆ patient.tx ┆   ┆      ┆       ┆            ┆            │
│             ┆             ┆ e6a-8798eb ┆ t          ┆   ┆      ┆       ┆            ┆            │
│             ┆             ┆ …          ┆            ┆   ┆      ┆       ┆            ┆            │
│ Obstétrique ┆ IMG &       ┆ 8a0b57d8-6 ┆ surgery_in ┆ … ┆ null ┆ null  ┆ null       ┆ null       │
│             ┆ fausses     ┆ e82-4859-a ┆ patient.tx ┆   ┆      ┆       ┆            ┆            │
│             ┆ couches     ┆ 1d8-6c6253 ┆ t          ┆   ┆      ┆       ┆            ┆            │
│             ┆             ┆ …          ┆            ┆   ┆      ┆       ┆            ┆            │
└─────────────┴─────────────┴────────────┴────────────┴───┴──────┴───────┴────────────┴────────────┘

SKIP — prompt_system_one_gen.txt déjà figé dans tous les dossiers.

## 3. Génération — contrôle à sec puis run réel

Le contrôle à sec ne fait aucun appel API et aucune écriture — pas besoin de
clé. C'est aussi le **test de complétude** : `generate` échoue (`BenchError`)
au moindre fichier manquant, aucun dossier n'est sauté en silence. Le run
réel écrase `OUT_FILE` à chaque re-run (geste normal) ; chaque run réel
ajoute son entrée au journal `usage.json` (et une ligne par scénario au
journal CSV global `generation/usage_log.csv`). `ONLY` restreint le run réel
à quelques dossiers (entrée `partial` au journal).

In [7]:
dry = generate(TD, client=None, dry_run=True, **PARAMS_GEN)  # inutile de fournir un client
show_first_prompt(dry)

Scénario : 0000 — famille : medical_outpatient

============================ PROMPT SYSTÈME — 17258 caractère(s) ============================
Vous êtes un médecin clinicien expert. Votre tâche est de générer un compte rendu d'hospitalisation détaillé à partit d'un scénario clinique réalisé avec des codes de la classification internationale des maladies et d'autres informations décrivant l'hospitalisation.


# Contexte : le codage CIM-10

La CIM-10 est une classification des maladies, elle peut se définir comme un ensemble organisé de rubriques dans lesquelles on range des entités morbides en fonction de certains critères établis. La CIM est utilisée pour transposer les diagnostics de maladies ou autres problèmes de santé en codes alphanumériques, ce qui facilite le stockage, la recherche et l'analyse des données. Elle est très utilisée en France, en particulier pour le codage des causes de décès et pour la déclaration de l'activité hospitalière dans le cadre du programme de médicalisation des systèmes d'information (PMSI).

Le codage CIM-10 consiste à identifier dans un document médical (CRH, notes d'évolution, comptes-rendus opératoires) les maladies, éventuellement les symptômes et états cliniques en l'absence de maladie clairement identifiée, et à leur attribuer des codes standardisés. C'est une tâche de standardisation d'information, pas une tâche de décision médicale : on traduit ce que le clinicien a écrit en codes normalisés.

# Ta mission : la tâche inverse

Ta mission est de réaliser la tâche inverse : à partir d'un scénario essentiellement composé de codes CIM-10, générer un compte rendu d'hospitalisation. Tu pars donc du concept standardisé et tu retournes vers la diversité réelle de l'écriture médicale.

Ces comptes rendus serviront à entraîner un outil d'aide au codage automatique : il est essentiel que ces CRH soient à la fois réalistes mais aussi que le lien entre le texte et les codes CIM à l'échelle du document soit respecté. Il est donc impératif que le CRH ne décrive que des maladies couvertes par le scénario CIM-10. À noter que pour le codage CIM-10, seules les maladies actives au moment de l'hospitalisation sont codées : tu peux donc mentionner des antécédents médicaux ou chirurgicaux mineurs et plausibles pour donner du réalisme au compte rendu, mais évite tout antécédent suffisamment lourd ou actif pour qu'il aurait dû lui-même être codé.

# La nature variable des codes CIM-10

Pour t'aider à bien comprendre le périmètre de chacun des codes choisis, je te fournis également une fiche descriptive par code, qui contient des informations complémentaires issues de la classification et de thésaurus médicaux. La CIM-10 range les entités morbides dans des rubriques selon des critères établis. Concrètement, deux types de critères définissent le périmètre d'un code, et les informations complémentaires correspondent à ces deux logiques :

- des **critères positifs** — ce qui fait entrer une pathologie dans la rubrique. Ils sont portés par les notes d'**inclusion**.
- des **critères négatifs** — ce qui en est explicitement écarté et relève d'un autre code. Ils sont portés par les notes d'**exclusion**.

Les fiches contiennent également des **synonymes** des maladies qui entrent dans le périmètre du code. Tu peux t'en inspirer pour utiliser un vocabulaire moins formel que les libellés et notes officielles de la classification.

**Niveau d'application des inclusions.** Les notes d'inclusion peuvent être attachées à différents niveaux de la hiérarchie (chapitre, bloc, catégorie, code). Plus une inclusion est attachée à un niveau élevé, plus elle est générale et vaut pour de nombreux codes : c'est une définition de cadre, pas une caractéristique propre au code. Par exemple, au niveau du chapitre I, l'inclusion « maladies considérées habituellement comme contagieuses ou transmissibles » s'applique à tous les codes du chapitre et n'ajoute aucune spécificité à l'un d'eux en particulier. À l'inverse, une inclusion attachée directement au code décrit précisément ce que ce code recouvre. Sers-toi des inclusions générales pour comprendre le contexte d'un code, et des inclusions propres au code pour choisir le vocabulaire précis de ta rédaction.

**Point essentiel : les codes n'ont pas tous la même précision clinique.** Certains désignent une entité nette et unique (ex. I10, hypertension artérielle essentielle). D'autres regroupent plusieurs entités hétérogènes sous un même libellé.

**Cas des codes regroupant plusieurs entités précises** (ex. G12.2, qui couvre la sclérose latérale amyotrophique, la paralysie bulbaire progressive, l'amyotrophie spinale progressive...) : choisis UNE entité du périmètre, cohérente avec le reste du scénario, et nomme-la comme le ferait un clinicien (nom de la maladie, éponyme ou acronyme usuel : « SLA », « maladie de Charcot »...). Nommer une entité listée dans les inclusions ou synonymes du code n'est PAS ajouter une précision non portée par le code : c'est l'usage attendu des fiches. Ne reste au niveau du libellé générique que pour les codes « sans précision » (.9), où le flou est volontaire.

**Règle absolue de formulation des diagnostics : le libellé officiel d'un code CIM-10 ne doit JAMAIS apparaître tel quel dans le document produit.** C'est la formulation d'un classificateur, pas d'un clinicien. Chaque diagnostic doit être exprimé par une entité nommée, un synonyme clinique ou une reformulation naturelle issus de la fiche du code.

**Cas des sous-catégories « autres formes précisées » (le plus souvent `.8`)** : elles rassemblent des entités précises mais diverses qui n'ont pas de code dédié dans la catégorie (ex. B17.8, « autres hépatites virales aiguës précisées »). Le libellé officiel ne suffit alors pas à savoir quelle pathologie réelle décrire ; appuie-toi sur les inclusions et synonymes propres au code.

**Cas particulier des cancers (chapitre II, catégories C00-C75)** : la CIM-10 classe les tumeurs malignes primitives essentiellement selon leur siège anatomique, et en grands groupes selon le comportement de la tumeur ; la morphologie n'apparaît qu'exceptionnellement dans le titre. Deu
[... tronqué à 6000 caractères]

============================ PROMPT USER — 11590 caractère(s) ============================
**SCÉNARIO DE DÉPART :**
- Âge du patient : 63 ans
- Sexe du patient : Féminin
- Taille : 166 cm
- Poids : 72 kg (IMC 26,1)
- Tabac : non
- Alcool : non
- Date d'entrée : 12/08/2026
- Date de sortie : 12/08/2026
- Date de naissance : 10/06/1963
- Nom du patient : Schambil
- Prénom du patient : Claudia
- Mode d'entrée' : DOMICILE
- Mode de sortie' : DOMICILE
- Contexte de l'hospitalisation : Pour prise en charge en hospitalisation ambulatoire pour Autres formes de chimiothérapie.
- Codage CIM10 :
   * Diagnostic principal : Autres ostéoporoses - Autres localisations (M8188)
   * Diagnostics associés :
      - Cataracte diabétique (E10-E14 avec le quatrième chiffre .3) (H280)
      - Diabète sucré de type 2 insulinotraité, avec complications oculaires (E1130)
      - Anémie au cours d'autres maladies chroniques classées ailleurs (D638)
      - Anémie par carence en fer, sans précision (D509)
      - Surpoids dû à un excès calorique, de l'adulte ou de l'enfant (E6603)
- Nom du médecin / signataire : Jean Rimbert
- Hôpital : Hôpital Haut-Lévêque - CHU de Bordeaux

**FICHES DESCRIPTIVES DES CODES CIM-10 DU SCÉNARIO :**

Les fiches ci-dessous précisent le périmètre des codes CIM-10 présents dans le scénario.
Elles doivent être utilisées pour choisir des formulations compatibles avec les codes, sans ajouter de diagnostic non codé.

<fiche_code code="M81.88">

# M81.88 — Autres ostéoporoses - " Autres "

Statut MCO (kit ATIH 2025) : codable en MCO, pas de restriction.

## Position dans la classification
- Chapitre XIII : Maladies du système ostéoarticulaire, des muscles et du tissu conjonctif
- Bloc M80-M94 : Ostéopathies et chondropathies
- Bloc M80-M85 : Anomalies de la densité et de la structure osseuses

## Localisations anatomiques
- colonne vertébrale
- côtes
- cou
- crâne
- tête
- tronc

Bloc d'inclusion :
colonne vertébrale
côtes
cou
crâne
tête
tronc

## Périmètre clinique du code

Inclusions héritées de la catégorie M81.8 :
- Ostéoporose sénile

## À ne pas décrire

Affections relevant d'autres codes (hérité du chapitre XIII) :

certaines affections dont l'origine se situe dans la période périnatale (P00-P96)
certaines lésions de l’articulation temporomandibulaire (K07.6)
certaines maladies infectieuses et parasitaires (A00-B99)
complications de la grossesse, de l'accouchement et de la puerpéralité (O00-O99)
lésions traumatiques, empoisonnements et certaines autres conséquences de causes externes (S00-T98)
maladies endocriniennes, nutritionnelles et métaboliques (E00-E90)
malformations congénitales et anomalies chromosomiques (Q00-Q99)
symptômes, signes et résultats anormaux d'examens cliniques et de laboratoire, non classés ailleurs (R00-R99)
syndrome de loge musculaire (T79.6)
tumeurs (C00-D48)

Affections relevant d'autres codes (hérité de la catégorie M81) :

ostéoporose avec fracture pathologique (M80.-)

## Notes de la CIM-10
- Localisation ostéoarticulaire Les subdivisions suivantes sont données pour indiquer la localisation de l'atteinte et permettre de choisir les catégories appropriées du chapitre XIII. Les extensions locales ou les adaptations pour diverses spécialités peuvent faire appel à un nombre de caractères différents; il est donc conseillé de placer le caractère identifiant la subdivision à un endroit clairement identifiable (par exemple dans une case additionnelle). D'autres subdivisions pour les atteintes du genou, les dorsopathies et les lésions biomécaniques non classées ailleurs sont données en note respectivement en M23, avant M40 et avant M99. *(note du bloc M81.8)*

</fiche_code>

<fiche_code code="H28.0">

# H28.0 — Cataracte diabétique (avec le quatrième caractère .3)

Statut MCO (kit ATIH 2025) : codable en MCO, pas de restriction.

## Position dans la classification
- Chapitre VII : Maladies de l'œil et de ses annexes
- Bloc H25-H28 : Affections du cristallin

## À ne pas décrire

Affections relevant d'autres codes (hérité du chapitre VII) :

certaines affections dont l'origine se situe dans la période périnatale (P00-P96)
certaines maladies infectieuses et parasitaires (A00-B99)
complications de la grossesse, de l'accouchement et de la puerpéralité (O00-O99)
lésions traumatiques, empoisonnements et certaines autres conséquences de causes externes (S00-T98)
maladies endocriniennes, nutritionnelles et métaboliques (E00-E90)
malformations congénitales et anomalies chromosomiques (Q00-Q99)
symptômes, signes et résultats anormaux d'examens cliniques et de laboratoire, non classés ailleurs (R00-R99)
tumeurs (C00-D48)

## Formulations cliniques alternatives
- Cataracte chez le diabétique

</fiche_code>

<fiche_code code="E11.30">

# E11.30 — Diabète sucré de type 2 - "Avec complications oculaires" - "diabète sucré de type 2 insulinotraité"

Statut MCO (kit ATIH 2025) : codable en MCO, pas de restriction.

## Position dans la classification
- Chapitre IV : Maladies endocriniennes, nutritionnelles et métaboliques
- Bloc E10-E14 : Diabète sucré

## Périmètre clinique du code

Inclusions héritées de la catégorie E11.3 :
- Cataracte (H28.0)   diabétique
Rétinopathie (H36.0)   diabétique
- diabète (sucré) (avec obésité) (sans obésité) (de) adulte
- diabète (sucré) (avec obésité) (sans obésité) (de) :
 - adulte
 - maturité
 - non cétosique
 - non insulinodépendant du sujet jeune
 - stable
- diabète (sucré) (avec obésité) (sans obésité) (de) maturité
- diabète (sucré) (avec obésité) (sans obésité) (de) non cétosique
- diabète (sucré) (avec obésité) (sans obésité) (de) non insulino-dépendant du sujet jeune
- diabète (sucré) (avec obésité) (sans obésité) (de) stable
- diabète (sucré) (avec obésité) (sans obésité) (de) type II

## À ne pas décrire

Affections relevant d'autres codes (hérité du chapitre IV) :

anomalies endocriniennes et métaboliques transitoires spécifiques au fœtus et au nouveau-né (P70-P74)
complications de la grossesse, de l'accouchement et de la puerpéralité (O00-O99)
symptômes, signes et résultats anormaux d'examens cliniques et de laboratoire, non cl
[... tronqué à 6000 caractères]

============================ PREFIX (assistant) — 8 caractère(s) ============================
{"CR": "

In [14]:
client = mistral_client()  # échoue ici, clairement, si MISTRAL_API_KEY absente
cr = generate(
    TD, client=client, transport=TRANSPORT, max_workers=MAX_WORKERS,
    only=ONLY, **PARAMS_GEN,
)
print(cr.usage)

Run Mistral sync_20260925_123004_005132 — 15 requête(s) synchrone(s), modèle mistral-large-latest, 3 appel(s) en parallèle, JSONL : /Users/remi/GitHub/Stream/generation/runs/07/batches/crh_generation/sync_input_20260925_123004_005132.jsonl
  1/15 — 0001 : ok
  2/15 — 0000 : ok
  3/15 — 0002 : ok
  4/15 — 0003 : ok
  5/15 — 0004 : ok
  6/15 — 0005 : ok
  7/15 — 0006 : ok
  8/15 — 0008 : ok
  9/15 — 0007 : ok
  10/15 — 0010 : ok
  11/15 — 0011 : ok
  12/15 — 0009 : ok
  13/15 — 0012 : ok
  14/15 — 0013 : ok
  15/15 — 0014 : ok
Usage(n_requests=15, input_tokens=121232, output_tokens=29507, total_tokens=150739, input_cost_usd=0.060616, output_cost_usd=0.044260499999999994, total_cost_usd=0.1048765)

In [19]:
# Lecture des CR : rendu markdown inline du premier scénario, puis un aperçu
# .md à côté de chaque .txt du test (ex. 0007/crh_generation.md, versionné —
# « Markdown: Open Preview », ⇧⌘V). afficher_crh(TD, "0007") pour un autre.
CRH = "0005"   # numéro du dossier à relire, ou None pour le premier
_names = scenario_dirs(TD)
if _names:
    afficher_crh(TD, CRH or _names[0], OUT_FILE)
else:
    print("Pas encore de dossiers scénario dans", TD)
ecrire_apercus_md(TD, OUT_FILE)

### Compte rendu d'hospitalisation

**Hôpital Saint-Louis - Assistance Publique Hôpitaux de Paris**
**Service de CARDIOLOGIE**

**Nom :** Parant
**Prénom :** Jeannette
**Date de naissance :** 04/03/1942
**Âge :** 84 ans

---

### Motif d’hospitalisation
Mme Jeannette Parant, 84 ans, a été hospitalisée le 30/11/2026 pour exploration et prise en charge d’une douleur thoracique récurrente, survenant à l’effort et parfois au repos, associée à une sensation d’oppression. Ces symptômes évoquent un angor d’effort, dans un contexte d’hypertension artérielle connue et de fibrillation auriculaire paroxystique.

---

### Antécédents
- **Médicaux :**
  - Hypertension artérielle essentielle, suivie depuis plusieurs années.
  - Fibrillation auriculaire paroxystique, connue depuis 2020.
  - Sténose aortique calcifiée, non rhumatismale, diagnostiquée en 2022.
  - Hypothyroïdie, sous traitement substitutif.
  - Sinusite maxillaire chronique, évoluant depuis plusieurs années.
  - Dénutrition modérée, objectivée par un IMC à 21,6 kg/m² et une perte de poids récente.
  - Tabagisme actif (12 cigarettes/jour, 36 paquets-années).
- **Chirurgicaux :** Aucun antécédent chirurgical notable.
- **Familiaux :** Pas d’antécédent familial de cardiopathie ischémique ou de mort subite.
- **Allergies :** Aucune allergie médicamenteuse connue.

---

### Mode de vie
Mme Parant est retraitée, vivant à domicile de manière autonome. Elle fume activement 12 cigarettes par jour depuis plus de 50 ans (36 paquets-années). Elle ne consomme pas d’alcool. Son alimentation est déséquilibrée, avec des apports protéino-énergétiques insuffisants, contribuant à sa dénutrition modérée.

---

### Histoire de la maladie
Depuis quelques semaines, Mme Parant présente des épisodes de douleur thoracique constrictive, survenant initialement à l’effort (montée d’escaliers, marche rapide) et plus récemment au repos. Ces symptômes s’accompagnent d’une sensation d’oppression thoracique et de palpitations. Elle a consulté son médecin traitant, qui a suspecté un angor d’effort dans un contexte d’hypertension artérielle mal contrôlée et de fibrillation auriculaire paroxystique. Une hospitalisation a été décidée pour exploration coronarienne et ajustement thérapeutique.

---

### Examen clinique
À l’admission, Mme Parant est apyrétique, avec une tension artérielle à 160/90 mmHg, une fréquence cardiaque irrégulière à 88 battements/minute, et une saturation en oxygène à 96 % en air ambiant. Son poids est de 52 kg pour une taille de 155 cm (IMC = 21,6 kg/m²). L’auscultation cardiaque révèle un souffle systolique éjectionnel au foyer aortique, irradiant vers les carotides, compatible avec une sténose aortique serrée. Les pouls périphériques sont présents et symétriques. L’examen pulmonaire est sans particularité, en dehors d’une légère diminution du murmure vésiculaire à droite, évoquant une séquelle de sinusite maxillaire chronique. L’abdomen est souple, sans hépatomégalie ni signe d’insuffisance cardiaque droite. Les membres inférieurs ne présentent pas d’œdème.

---

### Examens complémentaires
- **Biologie :**
  - NFS : légère anémie normocytaire (Hb = 11,2 g/dL), sans anomalie des leucocytes ni des plaquettes.
  - Ionogramme sanguin : kaliémie à 4,1 mmol/L, natrémie à 138 mmol/L.
  - Créatinine : 102 µmol/L (DFG estimé à 45 mL/min/1,73 m²).
  - Bilan hépatique : normal.
  - TSH : 6,2 mUI/L (sous traitement substitutif), confirmant un équilibre suboptimal de l’hypothyroïdie.
  - Gaz du sang artériel : légère hypoxémie (PaO₂ = 72 mmHg) avec normocapnie.
  - Troponine ultrasensible : négative à deux reprises.
- **ECG :** Fibrillation auriculaire à réponse ventriculaire rapide (90 battements/minute), sans signe d’ischémie aiguë.
- **Échocardiographie transthoracique :** Sténose aortique serrée (surface aortique estimée à 0,8 cm²), avec un gradient moyen transvalvulaire à 45 mmHg. Fraction d’éjection ventriculaire gauche conservée (60 %). Légère hypertrophie ventriculaire gauche.
- **Coronarographie (01/12/2026) :** Réalisée par voie radiale. Mise en évidence d’une sténose serrée de l’artère interventriculaire antérieure proximale (70 %), ainsi que de lésions modérées sur la coronaire droite et la circonflexe. Une ventriculographie gauche a confirmé la bonne fonction systolique globale.

---

### Évolution pendant l'hospitalisation
#### Démarche diagnostique
L’exploration coronarienne a permis de confirmer le diagnostic d’angor d’effort, secondaire à une maladie coronarienne athéromateuse. La sténose aortique serrée, déjà connue, a été réévaluée et jugée non chirurgicale à ce stade, en raison de l’âge et des comorbidités. La fibrillation auriculaire paroxystique a été documentée à plusieurs reprises, sans épisode prolongé nécessitant une cardioversion.

#### Traitements
- **Traitement médicamenteux :**
  - Introduction d’un bêta-bloquant (bisoprolol 2,5 mg/jour) pour ralentir la fréquence cardiaque et réduire la consommation myocardique en oxygène.
  - Poursuite du traitement antihypertenseur (inhibiteur calcique et diurétique thiazidique).
  - Optimisation du traitement de l’hypothyroïdie (augmentation de la lévothyroxine à 75 µg/jour).
  - Introduction d’un antiagrégant plaquettaire (clopidogrel 75 mg/jour) en prévention secondaire.
  - Anticoagulation par antivitamine K (warfarine, INR cible 2-3) pour la fibrillation auriculaire.
  - Supplémentation nutritionnelle (compléments hyperprotéinés) pour corriger la dénutrition modérée.
- **Prise en charge des comorbidités :**
  - Consultation ORL pour évaluation de la sinusite maxillaire chronique, avec proposition d’un traitement local (lavages de nez).
  - Sevrage tabagique initié, avec proposition d’un suivi spécialisé en consultation de tabacologie.
  - Surveillance régulière de la fonction rénale et de l’équilibre thyroïdien.

Mme Parant a bien toléré les explorations et les ajustements thérapeutiques. Les douleurs thoraciques ont disparu sous traitement médical. Elle a été éduquée sur les signes d’alerte nécessitant une consultation en urgence (douleur thoracique, dyspnée, palpitations).

---

### Conclusion
Mme Jeannette Parant, 84 ans, a été hospitalisée pour exploration d’un angor d’effort dans un contexte d’hypertension artérielle, de fibrillation auriculaire paroxystique et de sténose aortique serrée. La coronarographie a révélé une sténose significative de l’artère interventriculaire antérieure, justifiant une prise en charge médicamenteuse optimisée. La dénutrition modérée et l’hypothyroïdie ont également été prises en charge. Elle sort ce jour (03/12/2026) avec un traitement adapté et un suivi rapproché en cardiologie.

**Dr Fernando Brando**
Service de Cardiologie
Hôpital Saint-Louis - AP-HP


---

## Formulations

```json
{
  "diagnostics": {
    "Autres formes d'angine de poitrine (I20.8)": [
      "angor d’effort",
      "angor d’effort dans un contexte d’hypertension artérielle mal contrôlée et de fibrillation auriculaire paroxystique",
      "angor d’effort, secondaire à une maladie coronarienne athéromateuse"
    ],
    "Hypertension essentielle (primitive) (I10)": [
      "hypertension artérielle essentielle",
      "hypertension artérielle mal contrôlée",
      "hypertension artérielle"
    ],
    "Malnutrition protéino-énergétique modérée (E44.0)": [
      "dénutrition modérée",
      "apports protéino-énergétiques insuffisants, contribuant à sa dénutrition modérée"
    ],
    "Douleur thoracique, sans précision (R07.4)": [
      "douleur thoracique récurrente",
      "douleur thoracique constrictive",
      "sensation d’oppression thoracique"
    ],
    "Fibrillation auriculaire paroxystique (I48.0)": [
      "fibrillation auriculaire paroxystique",
      "fibrillation auriculaire paroxystique, connue depuis 2020"
    ],
    "Autres résultats anormaux précisés des examens chimiques du sang (R79.8)": [
      "légère hypoxémie (PaO₂ = 72 mmHg) avec normocapnie",
      "TSH : 6,2 mUI/L (sous traitement substitutif)"
    ],
    "Hypothyroïdie, sans précision (E03.9)": [
      "hypothyroïdie",
      "équilibre suboptimal de l’hypothyroïdie"
    ],
    "Sténose (de la valvule) aortique (non rhumatismale) (I35.0)": [
      "sténose aortique calcifiée, non rhumatismale",
      "sténose aortique serrée",
      "rétrécissement aortique calcifié serré"
    ],
    "Sinusite maxillaire (chronique) (J32.0)": [
      "sinusite maxillaire chronique",
      "séquelle de sinusite maxillaire chronique"
    ],
    "Dépendance envers un respirateur : ventilation par masque nasal (Z99.1+1)": [],
    "Syndrome de dépendance au tabac, utilisation continue (F17.25)": [
      "tabagisme actif (12 cigarettes/jour, 36 paquets-années)"
    ]
  },
  "informations": {
    "Date entrée": [
      "30/11/2026"
    ],
    "Date de sortie": [
      "03/12/2026"
    ],
    "Service d'hospitalisation": [
      "CARDIOLOGIE"
    ],
    "Nom/Prénom du patient": [
      "Parant Jeannette"
    ],
    "Nom/Prénom du médecin": [
      "Fernando Brando"
    ],
    "Âge": [
      "84 ans"
    ],
    "Sexe": [
      "Féminin"
    ],
    "État général": [
      "Mme Parant est apyrétique, avec une tension artérielle à 160/90 mmHg, une fréquence cardiaque irrégulière à 88 battements/minute, et une saturation en oxygène à 96 % en air ambiant."
    ],
    "Poids": [
      "52 kg pour une taille de 155 cm (IMC = 21,6 kg/m²)"
    ],
    "Statut gestationnel": [],
    "Gestité": [],
    "NFS": [
      "légère anémie normocytaire (Hb = 11,2 g/dL), sans anomalie des leucocytes ni des plaquettes"
    ],
    "Créatinine": [
      "102 µmol/L (DFG estimé à 45 mL/min/1,73 m²)"
    ],
    "Bilan hépatique": [
      "normal"
    ],
    "Traitements": [
      "Introduction d’un bêta-bloquant (bisoprolol 2,5 mg/jour)",
      "Poursuite du traitement antihypertenseur (inhibiteur calcique et diurétique thiazidique)",
      "Optimisation du traitement de l’hypothyroïdie (augmentation de la lévothyroxine à 75 µg/jour)",
      "Introduction d’un antiagrégant plaquettaire (clopidogrel 75 mg/jour)",
      "Anticoagulation par antivitamine K (warfarine, INR cible 2-3)",
      "Supplémentation nutritionnelle (compléments hyperprotéinés)"
    ]
  }
}
```

/Users/remi/GitHub/Stream/generation/runs/07/0000/crh_generation.md
/Users/remi/GitHub/Stream/generation/runs/07/0001/crh_generation.md
/Users/remi/GitHub/Stream/generation/runs/07/0002/crh_generation.md
/Users/remi/GitHub/Stream/generation/runs/07/0003/crh_generation.md
/Users/remi/GitHub/Stream/generation/runs/07/0004/crh_generation.md
/Users/remi/GitHub/Stream/generation/runs/07/0005/crh_generation.md
/Users/remi/GitHub/Stream/generation/runs/07/0006/crh_generation.md
/Users/remi/GitHub/Stream/generation/runs/07/0007/crh_generation.md
/Users/remi/GitHub/Stream/generation/runs/07/0008/crh_generation.md
/Users/remi/GitHub/Stream/generation/runs/07/0009/crh_generation.md
/Users/remi/GitHub/Stream/generation/runs/07/0010/crh_generation.md
/Users/remi/GitHub/Stream/generation/runs/07/0011/crh_generation.md
/Users/remi/GitHub/Stream/generation/runs/07/0012/crh_generation.md
/Users/remi/GitHub/Stream/generation/runs/07/0013/crh_generation.md
/Users/remi/GitHub/Stream/generation/runs/07/0014/crh_generation.md

## 4. Vérificateur (optionnel) et bilan

Verdict nourri par les CR de la section 3 — depuis le disque (`load_reports`,
le disque fait foi ; `strict=False` charge les scénarios déjà servis et
`only=` restreint le run à ceux-là). Les prompts partagés du vérificateur sont
posés une fois (`write_prompts`) ; le contrôle à sec accepte un contexte
placeholder sans run réel.

Bilan : journal **append-only** des coûts (`committed_usd` = total engagé,
`current_usd` = coût de l'état courant), stats du journal CSV global, puis
les contrôles mécaniques hors modèle (`scripts/check_crh.py`,
`scripts/reancre_crh.py`, stdlib uniquement).

In [8]:
prompts_verificateur(TD, VERIF_SYSTEM, VERIF_USER)
ctx = contexte_verificateur(TD, OUT_FILE)
dry_verif = generate(TD, client=None, dry_run=True, context=ctx, **PARAMS_VERIF)
show_first_prompt(dry_verif)

SKIP — prompt_system_verif.txt déjà présent dans tous les dossiers.
SKIP — user_verification.txt déjà présent dans tous les dossiers.
Scénario : 0000 — famille : medical_outpatient

============================ PROMPT SYSTÈME — 260 caractère(s) ============================
Tu es un médecin DIM. On te fournit un compte rendu
hospitalier généré automatiquement. Vérifie sa cohérence clinique et sa
conformité aux règles de codage, puis rends un verdict structuré :
CONFORME ou NON CONFORME, suivi de la liste des anomalies constatées.

============================ PROMPT USER — 5560 caractère(s) ============================
Vérifie le compte rendu suivant et rends ton verdict.

### COMPTE RENDU À VÉRIFIER

{"CR": "### Hôpital Haut-Lévêque - CHU de Bordeaux\nService d'hospitalisation : Hospitalisation ambulatoire\n\n**Nom :** Schambil\n**Prénom :** Claudia\n**Date de naissance :** 10/06/1963\n**Âge :** 63 ans\n\n---

### Motif d'hospitalisation
Patiente de 63 ans adressée pour une séance de chimiothérapie dans le cadre de la prise en charge d'une ostéoporose sénile touchant le rachis dorsal et lombaire. Cette hospitalisation en ambulatoire vise à poursuivre le traitement prévu.

---

### Antécédents
- **Médicaux :**
  - Diabète de type 2 insulinotraité, compliqué d'une rétinopathie diabétique et d'une cataracte bilatérale chez la diabétique.
  - Ostéoporose sénile avec atteinte vertébrale dorsale et lombaire.
  - Anémie mixte : carence martiale chronique et anémie associée à une insuffisance rénale modérée.
  - Surpoids modéré.
- **Chirurgicaux :** Appendicectomie dans l’enfance.
- **Familiaux :** Aucun antécédent notable.
- **Allergies :** Aucune allergie médicamenteuse connue.

---

### Mode de vie
Patiente retraitée, vivant à domicile de manière autonome. Elle ne fume pas et ne consomme pas d’alcool. Son activité physique est limitée en raison de douleurs rachidiennes chroniques. Son indice de masse corporelle est à 26,1 kg/m² (taille : 166 cm, poids : 72 kg), en lien avec un surpoids dû à un excès calorique.

---

### Histoire de la maladie
Claudia Schambil est suivie depuis plusieurs années pour un diabète de type 2 insulinodépendant, compliqué d’une rétinopathie diabétique et d’une cataracte bilatérale, pour laquelle une chirurgie a été réalisée il y a deux ans. Par ailleurs, elle présente une ostéoporose sénile diagnostiquée il y a cinq ans, avec des tassements vertébraux dorsaux et lombaires documentés. Son suivi hématologique a révélé une anémie mixte : une carence martiale chronique, associée à une anémie liée à son insuffisance rénale modérée. Un traitement par chimiothérapie a été initié il y a trois mois pour stabiliser l’évolution de son ostéoporose. La séance d’aujourd’hui s’inscrit dans la continuité de ce protocole.

---

### Examen clinique
À l’admission, la patiente est apyrétique, avec une tension artérielle à 130/80 mmHg et une fréquence cardiaque régulière à 78 battements par minute. Son poids est stable à 72 kg. L’examen clinique met en évidence une légère pâleur cutanéo-muqueuse, sans signe de décompensation cardiaque ni de déficit neurologique. Les réflexes ostéotendineux sont présents et symétriques. On note une sensibilité à la palpation des vertèbres dorsales et lombaires, sans signe inflammatoire local. L’examen ophtalmologique récent confirme la stabilité de la rétinopathie diabétique et l’absence de complication post-chirurgicale de la cataracte.

---

### Examens complémentaires
- **Bilan biologique :**
  - NFS : Hémoglobine à 10,2 g/dL, VGM à 78 fL, ferritinémie basse à 12 µg/L, confirmant une anémie ferriprive chronique. La créatininémie est à 110 µmol/L (DFG estimé à 50 mL/min), en lien avec une insuffisance rénale modérée.
  - Bilan hépatique : Normal.
  - HbA1c : 7,8 %, témoignant d’un équilibre glycémique suboptimal.
- **Imagerie :**
  - Radiographies du rachis dorsal et lombaire : Tassements vertébraux anciens, sans signe de fracture récente.

---

### Conclusion
Patiente de 63 ans présentant une ostéoporose sénile avec atteinte vertébrale, un diabète de type 2 insulinotraité compliqué de rétinopathie et de cataracte, ainsi qu’une anémie mixte (carence martiale et insuffisance rénale). La séance de chimiothérapie s’est déroulée sans complication. La sortie est autorisée ce jour, avec poursuite du traitement habituel et suivi régulier en endocrinologie, rhumatologie et hématologie.

**Dr Jean Rimbert**",
"formulations": {
    "diagnostics": {
        "Autres ostéoporoses - Autres localisations (M81.88)": ["ostéoporose sénile touchant le rachis dorsal et lombaire", "ostéoporose sénile avec atteinte vertébrale dorsale et lombaire"],
        "Cataracte diabétique (H28.0)": ["cataracte bilatérale chez la diabétique"],
        "Diabète sucré de type 2 insulinotraité, avec complications oculaires (E11.30)": ["diabète de type 2 insulinotraité, compliqué d'une rétinopathie diabétique", "diabète de type 2 insulinodépendant"],
        "Anémie au cours d'autres maladies chroniques classées ailleurs (D63.8)": ["anémie associée à une insuffisance rénale modérée", "anémie liée à son insuffisance rénale modérée"],
        "Anémie par carence en fer, sans précision (D50.9)": ["anémie ferriprive chronique", "carence martiale chronique"],
        "Surpoids dû à un excès calorique, de l'adulte ou de l'enfant (E66.03)": ["surpoids modéré", "surpoids dû à un excès calorique"]
    },
    "informations": {
        "Date entrée": ["12/08/2026"],
        "Date de sortie": ["12/08/2026"],
        "Service d'hospitalisation": ["Hospitalisation ambulatoire"],
        "Nom/Prénom du médecin": ["Jean Rimbert"],
        "Nom/Prénom du patient": ["Schambil Claudia"],
        "Poids": ["72 kg"],
        "Âge": ["63 ans"],
        "Sexe": ["Féminin"],
        "État général": ["légère pâleur cutanéo-muqueuse, sans signe de décompensation cardiaque ni de déficit neurologique"],
        "NFS": ["Hémoglobine à 10,2 g/dL, VGM à 78 fL, ferritinémie basse à 12 µg/L"],
        "Créatinine": ["créatininémie est à 110 µmol/L (DFG estimé à 50 mL/min)"],
        "Bilan hépatique": ["Normal"],
        "Traitements": ["poursuite du traitement habituel"]
    }
}}

### FIN DU COMPTE RENDU

============================ PREFIX (assistant) — 0 caractère(s) ============================

In [9]:
client = mistral_client()

cr_disque = load_reports(TD, OUT_FILE, strict=False)
if cr_disque.height == 0:
    raise RuntimeError(f"Aucun {OUT_FILE} sur disque : lancer d'abord le run réel (section 3).")

verdicts = generate(
    TD, client=client, transport=TRANSPORT, max_workers=MAX_WORKERS,
    context=cr_disque, only=cr_disque["scenario"].to_list(), **PARAMS_VERIF,
)
print(verdicts.usage)

Run Mistral sync_20260925_152932_367142 — 15 requête(s) synchrone(s), modèle mistral-large-latest, 3 appel(s) en parallèle, JSONL : /Users/remi/GitHub/Stream/generation/runs/07/batches/verdict/sync_input_20260925_152932_367142.jsonl
  1/15 — 0001 : ok
  2/15 — 0000 : ok
  3/15 — 0002 : ok
  4/15 — 0004 : ok
  5/15 — 0003 : ok
  6/15 — 0007 : ok
  7/15 — 0006 : ok
  8/15 — 0005 : ok
  9/15 — 0008 : ok
  10/15 — 0010 : ok
  11/15 — 0009 : ok
  12/15 — 0011 : ok
  13/15 — 0013 : ok
  14/15 — 0012 : ok
  15/15 — 0014 : ok
Usage(n_requests=15, input_tokens=31074, output_tokens=23470, total_tokens=54544, input_cost_usd=0.015537, output_cost_usd=0.035205, total_cost_usd=0.050742)

In [10]:
bilan(TD, out_file=OUT_FILE)

=== 01 — /Users/remi/GitHub/Stream/generation/runs/01 ===

shape: (2, 4)
┌────────────────────┬────────┬───────────────┬─────────────┐
│ out                ┆ n_runs ┆ committed_usd ┆ current_usd │
│ ---                ┆ ---    ┆ ---           ┆ ---         │
│ str                ┆ i64    ┆ f64           ┆ f64         │
╞════════════════════╪════════╪═══════════════╪═════════════╡
│ crh_generation.txt ┆ 10     ┆ 0.090834      ┆ 0.045261    │
│ TOTAL              ┆ 10     ┆ 0.090834      ┆ 0.045261    │
└────────────────────┴────────┴───────────────┴─────────────┘

=== 02 — /Users/remi/GitHub/Stream/generation/runs/02 ===

shape: (3, 4)
┌────────────────────┬────────┬───────────────┬─────────────┐
│ out                ┆ n_runs ┆ committed_usd ┆ current_usd │
│ ---                ┆ ---    ┆ ---           ┆ ---         │
│ str                ┆ i64    ┆ f64           ┆ f64         │
╞════════════════════╪════════╪═══════════════╪═════════════╡
│ crh_generation.txt ┆ 2      ┆ 0.0647135     ┆ 0.033556    │
│ verdict.txt        ┆ 1      ┆ 0.015932      ┆ 0.015932    │
│ TOTAL              ┆ 3      ┆ 0.080646      ┆ 0.049488    │
└────────────────────┴────────┴───────────────┴─────────────┘

=== 03 — /Users/remi/GitHub/Stream/generation/runs/03 ===

shape: (2, 4)
┌────────────────────┬────────┬───────────────┬─────────────┐
│ out                ┆ n_runs ┆ committed_usd ┆ current_usd │
│ ---                ┆ ---    ┆ ---           ┆ ---         │
│ str                ┆ i64    ┆ f64           ┆ f64         │
╞════════════════════╪════════╪═══════════════╪═════════════╡
│ crh_generation.txt ┆ 2      ┆ 0.047232      ┆ 0.047232    │
│ TOTAL              ┆ 2      ┆ 0.047232      ┆ 0.047232    │
└────────────────────┴────────┴───────────────┴─────────────┘

=== 04 — /Users/remi/GitHub/Stream/generation/runs/04 ===

shape: (2, 4)
┌────────────────────┬────────┬───────────────┬─────────────┐
│ out                ┆ n_runs ┆ committed_usd ┆ current_usd │
│ ---                ┆ ---    ┆ ---           ┆ ---         │
│ str                ┆ i64    ┆ f64           ┆ f64         │
╞════════════════════╪════════╪═══════════════╪═════════════╡
│ crh_generation.txt ┆ 2      ┆ 0.0435085     ┆ 0.0435085   │
│ TOTAL              ┆ 2      ┆ 0.0435085     ┆ 0.0435085   │
└────────────────────┴────────┴───────────────┴─────────────┘

=== 05 — /Users/remi/GitHub/Stream/generation/runs/05 ===

shape: (2, 4)
┌────────────────────┬────────┬───────────────┬─────────────┐
│ out                ┆ n_runs ┆ committed_usd ┆ current_usd │
│ ---                ┆ ---    ┆ ---           ┆ ---         │
│ str                ┆ i64    ┆ f64           ┆ f64         │
╞════════════════════╪════════╪═══════════════╪═════════════╡
│ crh_generation.txt ┆ 2      ┆ 0.089658      ┆ 0.085633    │
│ TOTAL              ┆ 2      ┆ 0.089658      ┆ 0.085633    │
└────────────────────┴────────┴───────────────┴─────────────┘

=== 06 — /Users/remi/GitHub/Stream/generation/runs/06 ===

shape: (2, 4)
┌────────────────────┬────────┬───────────────┬─────────────┐
│ out                ┆ n_runs ┆ committed_usd ┆ current_usd │
│ ---                ┆ ---    ┆ ---           ┆ ---         │
│ str                ┆ i64    ┆ f64           ┆ f64         │
╞════════════════════╪════════╪═══════════════╪═════════════╡
│ crh_generation.txt ┆ 1      ┆ 0.0853195     ┆ 0.0853195   │
│ TOTAL              ┆ 1      ┆ 0.0853195     ┆ 0.0853195   │
└────────────────────┴────────┴───────────────┴─────────────┘

=== 07 — /Users/remi/GitHub/Stream/generation/runs/07 ===

shape: (3, 4)
┌────────────────────┬────────┬───────────────┬─────────────┐
│ out                ┆ n_runs ┆ committed_usd ┆ current_usd │
│ ---                ┆ ---    ┆ ---           ┆ ---         │
│ str                ┆ i64    ┆ f64           ┆ f64         │
╞════════════════════╪════════╪═══════════════╪═════════════╡
│ crh_generation.txt ┆ 2      ┆ 0.11144       ┆ 0.1048765   │
│ verdict.txt        ┆ 1      ┆ 0.050742      ┆ 0.050742    │
│ TOTAL              ┆ 3      ┆ 0.162182      ┆ 0.1556185   │
└────────────────────┴────────┴───────────────┴─────────────┘

generation/usage_log.csv — 45 ligne(s)
Coût et tokens par (test, out) :

shape: (3, 6)
┌──────┬────────────────────┬──────────┬──────────────┬───────────────┬──────────┐
│ test ┆ out                ┆ n_lignes ┆ input_tokens ┆ output_tokens ┆ cost_usd │
│ ---  ┆ ---                ┆ ---      ┆ ---          ┆ ---           ┆ ---      │
│ str  ┆ str                ┆ u32      ┆ i64          ┆ i64           ┆ f64      │
╞══════╪════════════════════╪══════════╪══════════════╪═══════════════╪══════════╡
│ 06   ┆ crh_generation.txt ┆ 14       ┆ 100625       ┆ 23338         ┆ 0.085318 │
│ 07   ┆ crh_generation.txt ┆ 16       ┆ 129106       ┆ 31258         ┆ 0.11144  │
│ 07   ┆ verdict.txt        ┆ 15       ┆ 31074        ┆ 23470         ┆ 0.05074  │
└──────┴────────────────────┴──────────┴──────────────┴───────────────┴──────────┘

Test courant 07 — par template :

shape: (6, 5)
┌───────────────────────────┬──────────┬──────────────┬───────────────┬──────────┐
│ template                  ┆ n_lignes ┆ input_tokens ┆ output_tokens ┆ cost_usd │
│ ---                       ┆ ---      ┆ ---          ┆ ---           ┆ ---      │
│ str                       ┆ u32      ┆ i64          ┆ i64           ┆ f64      │
╞═══════════════════════════╪══════════╪══════════════╪═══════════════╪══════════╡
│ delivery_inpatient_hospit ┆ 2        ┆ 11587        ┆ 4524          ┆ 0.012579 │
│ delivery_inpatient_urg    ┆ 2        ┆ 12324        ┆ 4053          ┆ 0.012242 │
│ medical_inpatient         ┆ 14       ┆ 76539        ┆ 25741         ┆ 0.07688  │
│ medical_outpatient        ┆ 7        ┆ 33350        ┆ 11477         ┆ 0.03389  │
│ surgery_inpatient         ┆ 4        ┆ 20956        ┆ 7315          ┆ 0.02145  │
│ surgery_outpatient        ┆ 2        ┆ 5424         ┆ 1618          ┆ 0.005139 │
└───────────────────────────┴──────────┴──────────────┴───────────────┴──────────┘

[0000]
    ECHEC  gras interdit (11 occurrence(s)) : **Nom :**, **Prénom :**, **Date de naissance :**, **Âge :**
    ECHEC  formulation fantôme [diagnostics/Autres ostéoporoses - Autres localisations (M81.88)] : « ostéoporose sénile avec atteinte vertébrale dorsale et lomba »
    ECHEC  formulation fantôme [diagnostics/Diabète sucré de type 2 insulinotraité, avec complications oculaires (E11.30)] : « diabète de type 2 insulinotraité, compliqué d'une rétinopath »
    ECHEC  formulation fantôme [diagnostics/Surpoids dû à un excès calorique, de l'adulte ou de l'enfant (E66.03)] : « surpoids modéré »
    ECHEC  formulation fantôme [informations/Date entrée] : « 12/08/2026 »
    ECHEC  formulation fantôme [informations/Date de sortie] : « 12/08/2026 »
    ECHEC  formulation fantôme [informations/Nom/Prénom du patient] : « Schambil Claudia »
    ECHEC  formulation fantôme [informations/Sexe] : « Féminin »
    AVERT  mention IPP absente de l'en-tête
    AVERT  maladie chronique mentionnée : diabète (à confronter au scénario)
[0001]
    ECHEC  gras interdit (4 occurrence(s)) : **Nom :**, **Prénom :**, **Date de naissance :**, **Date de l’intervention :**
    ECHEC  formulation fantôme [diagnostics/Stérilité de la femme d'autres origines (N97.8)] : « incapacité de mener une grossesse à terme »
    ECHEC  formulation fantôme [informations/Nom/Prénom du patient] : « Ingegno Adrienne »
    ECHEC  formulation fantôme [informations/Sexe] : « Féminin »
    AVERT  clés absentes du dictionnaire : Date entrée, Date de sortie, Service d'hospitalisation, Nom/Prénom du médecin, Poids
    AVERT  mention IPP absente de l'en-tête
[0002]
    ECHEC  gras interdit (14 occurrence(s)) : **Hôpital de la Timone - Assistance Publ, **Service de Néonatologie**, **Patient :**, **Médicaux :**
    ECHEC  formulation fantôme [informations/Nom/Prénom du patient] : « Courteboeuf Asmae »
    ECHEC  formulation fantôme [informations/Traitements] : « surveillance clinique rapprochée avec monitorage continu de  »
    AVERT  mention IPP absente de l'en-tête
    AVERT  maladie chronique mentionnée : hypertension (à confronter au scénario)
[0003]
    ECHEC  gras interdit (26 occurrence(s)) : **Hôpital Saint-Louis - Assistance Publi, **Service d'OBSTETRIQUE**, **Identification de la patiente**, **Médicaux**
    ECHEC  formulation fantôme [diagnostics/Naissance unique, enfant vivant (Z37.0)] : « naissance d'un nouveau-né vivant de sexe féminin »
    ECHEC  formulation fantôme [informations/Nom/Prénom du patient] : « Barbeyron Noelle »
    ECHEC  formulation fantôme [informations/Sexe] : « Féminin »
    ECHEC  formulation fantôme [informations/Poids] : « 3250 grammes (nouveau-né) »
    AVERT  clés absentes du dictionnaire : Nom/Prénom du médecin, Traitements
    AVERT  mention IPP absente de l'en-tête
    AVERT  maladie chronique mentionnée : diabète (à confronter au scénario)
    AVERT  maladie chronique mentionnée : hypertension (à confronter au scénario)
[0004]
    ECHEC  gras interdit (7 occurrence(s)) : **Médicaux**, **Chirurgicaux**, **Familiaux**, **Allergies**
    ECHEC  formulation fantôme [diagnostics/Iso-immunisation ABO du fœtus et du nouveau-né (P55.1)] : « incompatibilité ABO diagnostiquée en période néonatale »
    ECHEC  formulation fantôme [informations/Nom/Prénom du patient] : « Vanquickenborne Julien »
    ECHEC  formulation fantôme [informations/Nom/Prénom du médecin] : « Ghislaine Boisson »
    ECHEC  formulation fantôme [informations/Sexe] : « masculin »
    AVERT  mention IPP absente de l'en-tête
[0005]
    ECHEC  gras interdit (17 occurrence(s)) : **Hôpital Saint-Louis - Assistance Publi, **Service de CARDIOLOGIE**, **Nom :**, **Prénom :**
    ECHEC  formulation fantôme [diagnostics/Hypertension essentielle (primitive) (I10)] : « hypertension artérielle essentielle »
    ECHEC  formulation fantôme [diagnostics/Fibrillation auriculaire paroxystique (I48.0)] : « fibrillation auriculaire paroxystique, connue depuis 2020 »
    ECHEC  formulation fantôme [diagnostics/Sténose (de la valvule) aortique (non rhumatismale) (I35.0)] : « sténose aortique calcifiée, non rhumatismale »
    ECHEC  formulation fantôme [diagnostics/Sténose (de la valvule) aortique (non rhumatismale) (I35.0)] : « rétrécissement aortique calcifié serré »
    ECHEC  formulation fantôme [diagnostics/Syndrome de dépendance au tabac, utilisation continue (F17.25)] : « tabagisme actif (12 cigarettes/jour, 36 paquets-années) »
    ECHEC  formulation fantôme [informations/Nom/Prénom du patient] : « Parant Jeannette »
    ECHEC  formulation fantôme [informations/Sexe] : « Féminin »
    AVERT  mention IPP absente de l'en-tête
    AVERT  maladie chronique mentionnée : fibrillation (à confronter au scénario)
    AVERT  maladie chronique mentionnée : hypertension (à confronter au scénario)
[0006]
    ECHEC  gras interdit (11 occurrence(s)) : **Hôpital Larrey - Centre hospitalier un, **Service : HEPATO-GASTRO-ENTEROLOGIE**, **Patient :**, **Médicaux :**
    ECHEC  formulation fantôme [diagnostics/Diabète sucré de type 2 non insulinotraité ou sans précision, sans complication (E11.98)] : « diabète de type 2 non insulinotraité »
    ECHEC  formulation fantôme [diagnostics/Surpoids dû à un excès calorique, de l'adulte ou de l'enfant (E66.03)] : « surpoids modéré »
    ECHEC  formulation fantôme [informations/Date de sortie] : « 12/06/2024 »
    ECHEC  formulation fantôme [informations/Créatinine] : « normale »
    AVERT  mention IPP absente de l'en-tête
    AVERT  score standardisé présent : ECOG
    AVERT  maladie chronique mentionnée : diabète (à confronter au scénario)
    ECHEC  taille du scénario (164 cm) absent du CR
[0007]
    ECHEC  gras interdit (20 occurrence(s)) : **Service de Néphrologie**, **Compte rendu d'hospitalisation**, **Nom :**, **Prénom :**
    ECHEC  formulation fantôme [diagnostics/Tumeur maligne secondaire du poumon (C780)] : « métastases pulmonaires secondaires »
    ECHEC  formulation fantôme [diagnostics/Présence d'implants d'articulations orthopédiques (Z966)] : « prothèse totale de hanche gauche »
    ECHEC  formulation fantôme [diagnostics/Obésité due à un excès calorique de l'adulte avec indice de masse corporelle [IMC] égal ou supérieur à 30 kg/m² et inférieur à 35 kg/m², ou obésité due à un excès calorique de l'enfant (E6604)] : « obésité modérée (IMC à 30,4 kg/m²) »
    ECHEC  formulation fantôme [diagnostics/Malnutrition protéino-énergétique modérée (E440)] : « dénutrition protéino-énergétique modérée »
    ECHEC  formulation fantôme [diagnostics/Malnutrition protéino-énergétique modérée (E440)] : « dénutrition protéino-énergétique modérée »
    ECHEC  formulation fantôme [diagnostics/Lucite polymorphe (L564)] : « antécédent de lucite polymorphe »
    ECHEC  formulation fantôme [diagnostics/Carence en vitamine D, sans précision (E559)] : « carence en vitamine D documentée »
    ECHEC  formulation fantôme [diagnostics/Carence en vitamine D, sans précision (E559)] : « vitamine D : 12 ng/mL »
    ECHEC  formulation fantôme [diagnostics/Hypothyroïdie, sans précision (E039)] : « hypothyroïdie sous traitement substitutif »
    ECHEC  formulation fantôme [informations/Date entrée] : « 20/07/2026 »
    ECHEC  formulation fantôme [informations/Date de sortie] : « 12/08/2026 »
    ECHEC  formulation fantôme [informations/Nom/Prénom du patient] : « Sanchez Tebar Ourdia »
    ECHEC  formulation fantôme [informations/Sexe] : « Féminin »
    ECHEC  formulation fantôme [informations/Créatinine] : « créatininémie : 280 µmol/L »
    ECHEC  formulation fantôme [informations/Traitements] : « ajustement de la posologie de lévothyroxine »
    ECHEC  formulation fantôme [informations/Traitements] : « vitamine D per os (100 000 UI en dose de charge, puis 800 UI »
    ECHEC  formulation fantôme [informations/Traitements] : « régime hypercalorique et hyperprotéiné, avec complémentation »
    AVERT  mention IPP absente de l'en-tête
    AVERT  maladie chronique mentionnée : hypertension (à confronter au scénario)
    ECHEC  taille du scénario (154 cm) absent du CR
[0008]
    AVERT  JSON réparé : 1 accolade(s) fermante(s) manquante(s) en fin de fichier
    ECHEC  gras interdit (6 occurrence(s)) : **Compte rendu d'hospitalisation**, **Patient :**, **Médicaux :**, **Chirurgicaux :**
    ECHEC  formulation fantôme [informations/Nom/Prénom du patient] : « Dischert Chantal »
    ECHEC  formulation fantôme [informations/Sexe] : « Féminin »
    ECHEC  formulation fantôme [informations/État général] : « La patiente est apyrétique, avec une tension artérielle à 12 »
    ECHEC  formulation fantôme [informations/Traitements] : « un traitement par IPP à double dose a été instauré pour une  »
[0009]
    ECHEC  gras interdit (3 occurrence(s)) : **Biologie**, **Échographie obstétricale**, **Monitoring fœtal**
    ECHEC  formulation fantôme [diagnostics/Soins maternels pour iso-immunisation anti-Rh (O360)] : « immunisation RH »
    ECHEC  formulation fantôme [diagnostics/Naissance unique, enfant vivant (Z370)] : « naissance d'un enfant vivant de sexe féminin »
    ECHEC  formulation fantôme [diagnostics/Accouchement (unique) spontané par présentation du sommet (O800)] : « accouchement par voie basse spontanée en présentation du som »
    ECHEC  formulation fantôme [informations/Nom/Prénom du patient] : « Moreau Megann »
    ECHEC  formulation fantôme [informations/Sexe] : « Féminin »
    ECHEC  formulation fantôme [informations/État général] : « La patiente présentait des contractions utérines irrégulière »
    AVERT  clés absentes du dictionnaire : Nom/Prénom du médecin, Traitements
    AVERT  mention IPP absente de l'en-tête
[0010]
    AVERT  JSON réparé : 1 accolade(s) fermante(s) manquante(s) en fin de fichier
    ECHEC  gras interdit (10 occurrence(s)) : **Compte rendu d'hospitalisation**, **Patient :**, **Médicaux :**, **Chirurgicaux :**
    ECHEC  formulation fantôme [informations/Nom/Prénom du patient] : « Bauden Sirius »
    ECHEC  formulation fantôme [informations/Sexe] : « Masculin »
    AVERT  mention IPP absente de l'en-tête
    ECHEC  taille du scénario (189 cm) absent du CR
[0011]
    ECHEC  gras interdit (15 occurrence(s)) : **Service de Médecine Interne**, **Compte rendu d'hospitalisation**, **Patient :**, **Dates d'hospitalisation :**
    ECHEC  formulation fantôme [diagnostics/Schizophrénie paranoïde - continue (F20.00)] : « schizophrénie paranoïde continue »
    ECHEC  formulation fantôme [diagnostics/Cirrhoses du foie, autres et sans précision (K74.6)] : « cirrhose hépatique mixte »
    ECHEC  formulation fantôme [diagnostics/Obésité due à un excès calorique de l'adulte avec indice de masse corporelle [IMC] égal ou supérieur à 30 kg/m² et inférieur à 35 kg/m² (E66.04)] : « obésité modérée (IMC à 34,4 kg/m²) »
    ECHEC  formulation fantôme [informations/Nom/Prénom du patient] : « Clemot Yolande »
    ECHEC  formulation fantôme [informations/Sexe] : « Féminin »
    AVERT  mention IPP absente de l'en-tête
    AVERT  maladie chronique mentionnée : hypertension (à confronter au scénario)
[0012]
    ECHEC  formulation fantôme [diagnostics/Hypothyroïdie après un acte à visée diagnostique et thérapeutique (E890)] : « hypothyroïdie post-thyroïdectomie totale »
    ECHEC  formulation fantôme [diagnostics/Tachycardie, sans précision (R000)] : « tachycardie sinusale occasionnelle »
    ECHEC  formulation fantôme [informations/Date entrée] : « 04/01/2024 »
    ECHEC  formulation fantôme [informations/Date de sortie] : « 08/01/2024 »
    ECHEC  formulation fantôme [informations/Service d'hospitalisation] : « CHIR.PLAST.RECONSTR. »
    ECHEC  formulation fantôme [informations/Sexe] : « Féminin »
    ECHEC  formulation fantôme [informations/État général] : « Patiente apyrétique, avec une fréquence cardiaque à 95 batte »
    ECHEC  formulation fantôme [informations/Comorbidités] : « tachycardie sinusale occasionnelle »
    ECHEC  formulation fantôme [informations/NFS] : « NFS dans les limites de la normale »
    AVERT  clés absentes du dictionnaire : Nom/Prénom du médecin, Traitements
    AVERT  mention IPP absente de l'en-tête
    AVERT  mention « Nom » absente de l'en-tête
    AVERT  mention « Prénom » absente de l'en-tête
    AVERT  mention « Date de naissance » absente de l'en-tête
    ECHEC  service du scénario (CHIR.PLAST.RECONSTR.) absent du CR
[0013]
    ECHEC  gras interdit (13 occurrence(s)) : **Service de Néonatologie**, **Compte rendu d'hospitalisation**, **Identification du patient :**, **Médicaux :**
    ECHEC  formulation fantôme [diagnostics/Foetus et nouveau-né affectés par un accouchement par extracteur pneumatique [ventouse] (P033)] : « extraction par ventouse »
    ECHEC  formulation fantôme [diagnostics/Examen spécial de dépistage des affections des oreilles (Z1351)] : « test des otoémissions acoustiques automatisées (OEAA) »
    ECHEC  formulation fantôme [informations/Date de sortie] : « 16/06/2026 »
    ECHEC  formulation fantôme [informations/Service d'hospitalisation] : « NEONATOLOGIE »
    ECHEC  formulation fantôme [informations/Nom/Prénom du patient] : « Perrin Sohan »
    ECHEC  formulation fantôme [informations/Sexe] : « masculin »
    ECHEC  formulation fantôme [informations/Traitements] : « alimentation entérale exclusive au lait maternel »
    AVERT  mention IPP absente de l'en-tête
[0014]
    ECHEC  formulation fantôme [diagnostics/Tachycardie, sans précision (R000)] : « tachycardie à 110/min »
    ECHEC  formulation fantôme [informations/Sexe] : « Féminin »
    AVERT  clés absentes du dictionnaire : Nom/Prénom du médecin, Bilan hépatique, Traitements
    AVERT  mention IPP absente de l'en-tête

Bilan : 100 échec(s), 34 avertissement(s) sur 15 scénario(s)
[0000]
    RÉANCRÉE  [Autres ostéoporoses - Autres localisations (M81.88)] (0.98)
      dico  : « ostéoporose sénile avec atteinte vertébrale dorsale et lombaire »
      texte : « Ostéoporose sénile avec atteinte vertébrale dorsale et lombaire. »
    RÉANCRÉE  [Diabète sucré de type 2 insulinotraité, avec complications oculaires (E11.30)] (0.99)
      dico  : « diabète de type 2 insulinotraité, compliqué d'une rétinopathie diabéti »
      texte : « Diabète de type 2 insulinotraité, compliqué d'une rétinopathie diabéti »
    RÉANCRÉE  [Surpoids dû à un excès calorique, de l'adulte ou de l'enfant (E66.03)] (0.90)
      dico  : « surpoids modéré »
      texte : « Surpoids modéré. »
    ORPHELINE [Date entrée] (meilleur score 0.50)
      dico  : « 12/08/2026 »
    ORPHELINE [Date de sortie] (meilleur score 0.50)
      dico  : « 12/08/2026 »
    ORPHELINE [Nom/Prénom du patient] (meilleur score 0.71)
      dico  : « Schambil Claudia »
    ORPHELINE [Sexe] (meilleur score 0.59)
      dico  : « Féminin »
    bilan : 17 exacte(s), 3 réancrée(s), 4 orpheline(s)
[0001]
    ORPHELINE [Stérilité de la femme d'autres origines (N97.8)] (meilleur score 0.41)
      dico  : « incapacité de mener une grossesse à terme »
    ORPHELINE [Nom/Prénom du patient] (meilleur score 0.71)
      dico  : « Ingegno Adrienne »
    ORPHELINE [Sexe] (meilleur score 0.46)
      dico  : « Féminin »
    bilan : 7 exacte(s), 0 réancrée(s), 3 orpheline(s)
[0002]
    RÉANCRÉE  [Nom/Prénom du patient] (0.80)
      dico  : « Courteboeuf Asmae »
      texte : « Courteboeuf - »
    RÉANCRÉE  [Traitements] (0.85)
      dico  : « surveillance clinique rapprochée avec monitorage continu de la fréquen »
      texte : « surveillance clinique rapprochée a été mise en place, avec monitorage  »
    bilan : 14 exacte(s), 2 réancrée(s), 0 orpheline(s)
[0003]
    RÉANCRÉE  [Naissance unique, enfant vivant (Z37.0)] (0.97)
      dico  : « naissance d'un nouveau-né vivant de sexe féminin »
      texte : « Naissance d'un nouveau-né vivant de sexe féminin, »
    RÉANCRÉE  [Nom/Prénom du patient] (0.78)
      dico  : « Barbeyron Noelle »
      texte : « Barbeyron Prénom : Noelle »
    RÉANCRÉE  [Sexe] (0.80)
      dico  : « Féminin »
      texte : « féminin, »
    ORPHELINE [Poids] (meilleur score 0.74)
      dico  : « 3250 grammes (nouveau-né) »
    bilan : 32 exacte(s), 3 réancrée(s), 1 orpheline(s)
[0004]
    RÉANCRÉE  [Iso-immunisation ABO du fœtus et du nouveau-né (P55.1)] (0.97)
      dico  : « incompatibilité ABO diagnostiquée en période néonatale »
      texte : « Incompatibilité ABO diagnostiquée en période néonatale. »
    RÉANCRÉE  [Nom/Prénom du patient] (0.83)
      dico  : « Vanquickenborne Julien »
      texte : « Vanquickenborne Prénom : Julien »
    ORPHELINE [Nom/Prénom du médecin] (meilleur score 0.50)
      dico  : « Ghislaine Boisson »
    ORPHELINE [Sexe] (meilleur score 0.57)
      dico  : « masculin »
    bilan : 22 exacte(s), 2 réancrée(s), 2 orpheline(s)
[0005]
    RÉANCRÉE  [Hypertension essentielle (primitive) (I10)] (0.96)
      dico  : « hypertension artérielle essentielle »
      texte : « Hypertension artérielle essentielle, »
    RÉANCRÉE  [Fibrillation auriculaire paroxystique (I48.0)] (0.97)
      dico  : « fibrillation auriculaire paroxystique, connue depuis 2020 »
      texte : « Fibrillation auriculaire paroxystique, connue depuis 2020. »
    RÉANCRÉE  [Sténose (de la valvule) aortique (non rhumatismale) (I35.0)] (0.97)
      dico  : « sténose aortique calcifiée, non rhumatismale »
      texte : « Sténose aortique calcifiée, non rhumatismale, »
    RÉANCRÉE  [Syndrome de dépendance au tabac, utilisation continue (F17.25)] (0.97)
      dico  : « tabagisme actif (12 cigarettes/jour, 36 paquets-années) »
      texte : « Tabagisme actif (12 cigarettes/jour, 36 paquets-années). »
    ORPHELINE [Sténose (de la valvule) aortique (non rhumatismale) (I35.0)] (meilleur score 0.71)
      dico  : « rétrécissement aortique calcifié serré »
    ORPHELINE [Nom/Prénom du patient] (meilleur score 0.72)
      dico  : « Parant Jeannette »
    ORPHELINE [Sexe] (meilleur score 0.59)
      dico  : « Féminin »
    bilan : 34 exacte(s), 4 réancrée(s), 3 orpheline(s)
[0006]
    RÉANCRÉE  [Diabète sucré de type 2 non insulinotraité ou sans précision, sans complication (E11.98)] (0.96)
      dico  : « diabète de type 2 non insulinotraité »
      texte : « Diabète de type 2 non insulinotraité, »
    RÉANCRÉE  [Surpoids dû à un excès calorique, de l'adulte ou de l'enfant (E66.03)] (0.90)
      dico  : « surpoids modéré »
      texte : « Surpoids modéré. »
    RÉANCRÉE  [Date de sortie] (0.86)
      dico  : « 12/06/2024 »
      texte : « 11/06/2024, »
    RÉANCRÉE  [Créatinine] (0.86)
      dico  : « normale »
      texte : « normal. »
    bilan : 17 exacte(s), 4 réancrée(s), 0 orpheline(s)
[0007]
    RÉANCRÉE  [Tumeur maligne secondaire du poumon (C780)] (0.97)
      dico  : « métastases pulmonaires secondaires »
      texte : « Métastases pulmonaires secondaires »
    RÉANCRÉE  [Présence d'implants d'articulations orthopédiques (Z966)] (0.97)
      dico  : « prothèse totale de hanche gauche »
      texte : « Prothèse totale de hanche gauche »
    RÉANCRÉE  [Obésité due à un excès calorique de l'adulte avec indice de masse corporelle [IMC] égal ou supérieur à 30 kg/m² et inférieur à 35 kg/m², ou obésité due à un excès calorique de l'enfant (E6604)] (0.96)
      dico  : « obésité modérée (IMC à 30,4 kg/m²) »
      texte : « Obésité modérée (IMC à 30,4 kg/m²). »
    RÉANCRÉE  [Malnutrition protéino-énergétique modérée (E440)] (0.96)
      dico  : « dénutrition protéino-énergétique modérée »
      texte : « Dénutrition protéino-énergétique modérée. »
    RÉANCRÉE  [Malnutrition protéino-énergétique modérée (E440)] (0.96)
      dico  : « dénutrition protéino-énergétique modérée »
      texte : « Dénutrition protéino-énergétique modérée. »
    RÉANCRÉE  [Lucite polymorphe (L564)] (0.95)
      dico  : « antécédent de lucite polymorphe »
      texte : « Antécédent de lucite polymorphe. »
    RÉANCRÉE  [Carence en vitamine D, sans précision (E559)] (0.95)
      dico  : « carence en vitamine D documentée »
      texte : « Carence en vitamine D documentée. »
    RÉANCRÉE  [Carence en vitamine D, sans précision (E559)] (0.95)
      dico  : « vitamine D : 12 ng/mL »

### Préparer les entrées du juge (optionnel)

Après un run réel : le nettoyage d'export (`scripts/nettoie_dictionnaire.py`,
sortie `export_dict/` du test) ne garde du dictionnaire de formulations que
les passages présents verbatim dans le CR ; puis `juge_io.ecrire_entrees_juge`
écrit `entrees_juge.jsonl` — une ligne par code du scénario (code, libellé,
fiche, passages propres). Ces entrées servent aujourd'hui aux **verdicts
manuels** (preuve directe du diagnostic dans le texte, oui/non) et demain à
l'**encodeur** qui les rendra automatiquement ; leurs verdicts nourrissent
`prepare_regeneration`. Le contrat d'entrée et de sortie fait foi dans la
docstring de `scripts/juge_io.py`.

In [11]:
entrees_juge = preparer_entrees_juge(TD, out_file=OUT_FILE)

[0000]
    bilan : 17 gardée(s), 3 réancrée(s), 4 supprimée(s)
[0001]
    bilan : 7 gardée(s), 0 réancrée(s), 3 supprimée(s)
[0002]
    bilan : 14 gardée(s), 2 réancrée(s), 0 supprimée(s)
[0003]
    bilan : 32 gardée(s), 3 réancrée(s), 1 supprimée(s)
[0004]
    bilan : 22 gardée(s), 2 réancrée(s), 2 supprimée(s)
[0005]
    bilan : 34 gardée(s), 4 réancrée(s), 3 supprimée(s)
[0006]
    bilan : 17 gardée(s), 4 réancrée(s), 0 supprimée(s)
[0007]
    bilan : 36 gardée(s), 14 réancrée(s), 3 supprimée(s)
[0008]
    bilan : 11 gardée(s), 2 réancrée(s), 2 supprimée(s)
[0009]
    bilan : 30 gardée(s), 6 réancrée(s), 0 supprimée(s)
[0010]
    bilan : 27 gardée(s), 0 réancrée(s), 2 supprimée(s)
[0011]
    bilan : 24 gardée(s), 4 réancrée(s), 1 supprimée(s)
[0012]
    bilan : 18 gardée(s), 5 réancrée(s), 4 supprimée(s)
[0013]
    bilan : 21 gardée(s), 3 réancrée(s), 4 supprimée(s)
[0014]
    bilan : 30 gardée(s), 1 réancrée(s), 1 supprimée(s)

Bilan global : 393 formulation(s) exportée(s), 30 supprimée(s), sur 15 scénario(s)
Export : /Users/remi/GitHub/Stream/generation/runs/07/export_dict
Entrées juge : 88 code(s) sur 15 scénario(s) — 87 avec fiche, 3 sans passage — écrit : /Users/remi/GitHub/Stream/generation/runs/07/entrees_juge.jsonl
  0000  M8188    2 passage(s)  fiche oui  — Autres ostéoporoses - Autres localisations
  0000  H280     1 passage(s)  fiche oui  — Cataracte diabétique (E10-E14 avec le quatrième chiffre .3)
  0000  E1130    2 passage(s)  fiche oui  — Diabète sucré de type 2 insulinotraité, avec complications oculaires
  0000  D638     2 passage(s)  fiche oui  — Anémie au cours d'autres maladies chroniques classées ailleurs
  0000  D509     2 passage(s)  fiche oui  — Anémie par carence en fer, sans précision

# Annexe — Lire le bilan d'un test : le lexique des contrôles

*Annexe d'information pour la section 4 du notebook. Ce qui fait foi reste
les scripts (`scripts/check_crh.py`, `scripts/reancre_crh.py`,
`scripts/juge_io.py`) et leurs docstrings. Exemples tirés du test 07.*

---

## Le principe : deux objets vérifiés, trois étages de lecture

Chaque génération produit **deux objets** :

1. **le CRH** — le texte du compte rendu ;
2. **le dictionnaire d'annotation** — pour chaque code CIM-10 (section
   *diagnostics*) et chaque donnée du scénario (section *informations*),
   le modèle cite **l'extrait exact du texte** qui le prouve. C'est ce
   dictionnaire qui fera du corpus un jeu d'entraînement annoté.

Le bilan se lit en **trois étages**, et un chiffre brut ne se lit jamais
sans son étage de traitement :

| Étage | Outil | Question posée |
|---|---|---|
| 1. Contrôles | `check_crh` | le CRH et son dictionnaire respectent-ils le contrat ? |
| 2. Réancrage | `reancre_crh` | les citations inexactes sont-elles récupérables ? |
| 3. Jugement | entrées juge (`juge_io`) | chaque code a-t-il une **vraie preuve** dans le texte ? |

---

## Étage 1 — les sorties de `check_crh`

### Les ECHEC

**`gras interdit (N occurrences)`**
Le CRH contient du texte entre `**…**` (mise en forme markdown), interdit
car un vrai CRH est du texte brut. Presque toujours des étiquettes de
structure (`**Nom :**`, `**Médicaux :**`).
→ *Destination : nettoyage d'export (suppression mécanique). Jamais de
régénération pour ça — zéro coût qualité.*

**`formulation fantôme [section/clé] : « extrait »`**
L'extrait cité par le dictionnaire **ne se trouve pas mot pour mot** dans
le texte : le modèle a cité de mémoire en reformulant. Exemple (07/0014) :
cité « tachycardie à 110/min », écrit « tachycardie à 110 ». C'est un
défaut du *dictionnaire*, pas du texte — le CRH peut être excellent.
→ *Destination : le réancrage (étage 2) trie et récupère. Lecture
utile : les fantômes de la section `informations` (Sexe, dates, noms —
le texte dit « Mme », le dictionnaire cite « Féminin ») sont un défaut de
contrat des métadonnées ; ceux de la section `diagnostics` se réancrent
presque tous.*

**`code absent du texte`** (`code_absent_texte`)
Un code du scénario n'a **aucune entrée** au dictionnaire : le modèle ne
l'a ni raconté ni annoté. L'échec le plus grave — le CRH n'exprime pas
son codage.
→ *Destination : RÉGÉNÉRATION (bloc correctif à formulation imposée,
tirée de la fiche du code).*

**`fidélité poids/taille`** (`fidelite_poids_taille`)
Le scénario fournit des valeurs exactes (52 kg, 155 cm) ; le texte doit
les restituer telles quelles. Échec = valeur absente ou modifiée.
→ *Destination : RÉGÉNÉRATION.*

**`service du scénario (X) absent du CR`** (`fidelite_service`)
Quand le scénario fournit une ligne « - Service : X », X doit apparaître
dans le CRH (casse, accents et espaces indifférents). Échec = le modèle
l'a remplacé ou développé (« CHIR.PLAST.RECONSTR. » → « Chirurgie
Plastique et Reconstructrice »).
→ *Destination : même famille que poids/taille — fidélité aux données
fournies.*

**`json invalide` / `fichier absent`**
Le retour du modèle n'était pas le JSON attendu, ou le fichier manque.
Quasi disparu depuis le prefill `{"CR": "` ; le chargeur répare les
défauts mineurs (et le signale en avertissement `json réparé`).

### Les AVERT (informations — jamais bloquants)

**`clés absentes du dictionnaire : X, Y`** — le gabarit attend certaines
clés d'informations (Dates, Service, Médecin, Traitements…) ; toutes ne
sont pas là. Indicatif : la complétude des *codes* a son propre contrôle.

**`clé orpheline`** — l'inverse : une entrée du dictionnaire porte un
code qui n'est **pas** au scénario (le modèle a codé en plus). Parfois
légitime — à l'œil du DIM.

**`mention IPP / Nom / Prénom / Date de naissance absente de
l'en-tête`** — mentions administratives attendues par le gabarit.
Avertissement (et non échec) tant que l'identité n'est pas fournie par le
scénario : on ne sanctionne pas le modèle pour une donnée qu'on ne lui
donne pas. Repassera en contrôle de fidélité le jour venu.

**`maladie chronique mentionnée : diabète (à confronter au scénario)`**
Le texte mentionne une maladie chronique surveillée (diabète, HTA,
fibrillation…) : vérifier qu'un code du scénario la justifie. Le garde
existe pour attraper la chronique *inventée* sans code ; quand le code
est là (I10 pour « hypertension »), c'est un faux positif bénin.

---

## Étage 2 — les sorties de `reancre_crh`

Le réancrage reprend chaque formulation fantôme et cherche dans le texte
un passage quasi identique (seuil 0,75) :

**`EXACTE`** — l'extrait cité est mot pour mot dans le texte.
L'annotation est parfaite. *(07 : 340/423, soit 80 %.)*

**`RÉANCRÉE (score)`** — un quasi-identique existe au-dessus du seuil :
l'extrait cité est **remplacé par l'extrait exact** du texte,
l'annotation est récupérée. *(07 : 53, soit 12 %.)*

**`ORPHELINE (meilleur score X)`** — rien d'assez proche : l'entrée sera
**supprimée à l'export** (tracée dans `supprimees`). Le score dit si
c'était loin (0,59 : vraiment rien) ou frôlé (0,73 : juste sous le
seuil — matière à relecture humaine). *(07 : 30, soit 7 %.)*

**La règle de lecture** : le chiffre brut des fantômes (83 sur le 07) ne
veut rien dire seul — après réancrage il devient 30 vraies orphelines,
dont la majorité en section `informations` (métadonnées), pas en
`diagnostics`.

---

## Étage 3 — les entrées juge (`entrees_juge.jsonl`)

Une ligne JSONL **par code de scénario** :
`{scenario, code, libelle, fiche, passages}` — les passages sont les
formulations *nettoyées* (exactes + réancrées) de ce code.

**La question posée au juge** (relecture manuelle aujourd'hui, encodeur
entraîné demain) : *au moins un de ces passages est-il un équivalent
direct du code ?* — réponse `preuve_directe: true/false`, avec le
`passage_retenu` qui devient l'ancre d'annotation du code.

Pourquoi cet étage existe : un extrait peut matcher **exactement** dans
le texte sans rien prouver. Cas d'école (07/0005) : le code Z99.1
(ventilation par masque nasal) a une entrée au dictionnaire dont
l'extrait est bien dans le texte — mais le texte ne parle **jamais** de
ventilation. Le contrôle mécanique passe ; seul un jugement d'équivalence
médicale voit que la preuve est fausse. Verdict `false` → régénération.

**Cas limites** : `passages: []` (toutes les preuves du code étaient
orphelines) → verdict `false` obligatoire ; `fiche: null` (pas de
référentiel pour juger) → relecture humaine.

---

## `verdict.txt` — l'ancien vérificateur LLM (optionnel, payant)

Un second appel au modèle qui relit le CRH selon **sa propre doctrine**
— il peut par exemple exiger qu'un « diagnostic principal soit clairement
identifié », ce qu'aucun CRH réel ne fait (c'est le travail du codeur).
Ses « NON CONFORME » se lisent avec distance. La chaîne mécanique +
juge le remplace ; il reste disponible comme contre-lecture ponctuelle.

---

## La grille de synthèse : qui va où

| Sortie | Gravité | Destination |
|---|---|---|
| gras | forme | nettoyage d'export |
| formulation fantôme | annotation | réancrage → export propre |
| orpheline (après réancrage) | annotation | supprimée à l'export, tracée |
| code absent du texte | contenu | **régénération** |
| fidélité poids/taille/service | contenu | **régénération** |
| verdict juge `preuve_directe: false` | contenu | **régénération** |
| clé orpheline, chroniques, mentions | information | œil du DIM |
| json invalide/réparé | forme | chargeur réparateur / re-run si besoin |

**En une phrase** : le gras et les fantômes se *nettoient*, les codes
absents et les infidélités se *régénèrent*, les avertissements se
*relisent* — et un bilan de 100 échecs peut être parfaitement sain une
fois chaque compteur rangé dans sa colonne.

## Documentation — le pipeline de données AP-HP

Les fichiers d'entrée et leurs producteurs, les transformations dans l'ordre
(substitution des DP, `agean`, racine, typologie, spécialité, enrichissement,
contrôle des fiches) et le contenu du scénario final sont décrits dans
[docs/pipeline_donnees_aphp.md](../docs/pipeline_donnees_aphp.md) — une seule
adresse fait foi, rien n'est recopié ici.